Repository networkx/networkx, pull requests merged in 2018-05, with the labels that each got.

#2961 Allow bipartite configuration model for empty graph
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/bipartite/tests/test_generators.py
Labels: Maintenance

#2963 Add test case for not complete random bipartite graph.
  networkx/algorithms/bipartite/tests/test_generators.py
Labels: Enhancement

#2962 Fix a few bugs to allow bipartite generators accept empty lists.
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/bipartite/tests/test_generators.py
Labels: Enhancement

#2984 Order the output of columns in doctests for pandas
  networkx/convert_matrix.py
Labels: Maintenance

#2976 Add bipartite layout
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#2982 Add is_perfect_matching function
  doc/reference/algorithms/matching.rst
  networkx/algorithms/matching.py
  networkx/algorithms/tests/test_matching.py
Labels: Enhancement

#2987 Update docs for draw_networkx_labels
  networkx/drawing/nx_pylab.py
Labels: Documentation

#2929 upload gztar sdist and universal wheel Fixes #2928
  RELEASE.rst
Labels: Maintenance
