Repository networkx/networkx, pull requests merged in 2018-12, with the labels that each got.

#3171 Import ABCs from collections.abc
  networkx/algorithms/approximation/kcomponents.py
  networkx/algorithms/lowest_common_ancestors.py
  networkx/classes/coreviews.py
  networkx/classes/graph.py
  networkx/classes/reportviews.py
Labels: Maintenance

#3261 Fix typo in docstring
  networkx/generators/directed.py
Labels: Documentation

#3269 Fix docstring broken link to Graphviz
  networkx/drawing/nx_pydot.py
Labels: Documentation

#3271 Improve execution time of eigenvector centrality.
  networkx/algorithms/centrality/eigenvector.py
Labels: Enhancement

#3278 replace deprecated fresh_copy with __class__
  networkx/classes/digraph.py
  networkx/classes/function.py
Labels: Maintenance

#3279 fix frozen function
  networkx/classes/function.py
Labels: Maintenance
