Repository networkx/networkx, pull requests merged in 2018-08, with the labels that each got.

#3104 Update docstrings in gml to warn about underscores.
  networkx/readwrite/gml.py
Labels: Documentation

#3098 Add option to use Bellman-Ford in generic shortest-path functions
  doc/release/release_dev.rst
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
Labels: Documentation, Enhancement

#3108 Speed up kcut and kcomponent tests
  networkx/algorithms/connectivity/tests/test_kcomponents.py
  networkx/algorithms/connectivity/tests/test_kcutsets.py
Labels: Documentation

#3110 Clarify documentation for eigenvector_centrality. Fixes #2966.
  networkx/algorithms/centrality/eigenvector.py
Labels: Documentation

#3040 LR planarity checking
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/planarity.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/planarity.py
  networkx/algorithms/tests/test_planarity.py
Labels: Enhancement

#3114 Clarify documentation for predecessors() and successors(). Fixes #3113.
  networkx/classes/digraph.py
Labels: Documentation

#3056 Update dependencies and test 3.7 on xenial
  .appveyor.yml
  .travis.yml
  INSTALL.rst
  doc/news.rst
  requirements/default.txt
  requirements/doc.txt
  requirements/extras.txt
  requirements/test.txt
  setup.py
  tools/travis/build_docs.sh
  tools/travis/linux_install.sh
Labels: Maintenance

#3111 In 'from_pandas_adjacency', use column names rather than column order.
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: Maintenance

#3121 Fix scale_free_graph restriction
  networkx/generators/directed.py
  networkx/generators/tests/test_directed.py
Labels: Maintenance

#3119 Sparse Spanners using Baswana-Sen
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/sparsifiers.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/sparsifiers.py
  networkx/algorithms/tests/test_sparsifiers.py
Labels: Enhancement

#3124 Fix fluidc to fluid typo in autodoc structure for rst files.
  doc/reference/algorithms/community.rst
Labels: Documentation

#3123 Remove duplicate import, fixes #3120
  networkx/algorithms/__init__.py
Labels: Maintenance

#3131 Handle negatively weighted edges in bellman-ford, fixes #3130
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: Defect
