Repository networkx/networkx, pull requests merged in 2018-10, with the labels that each got.

#3178 Fix tiny typo in the document about from/to_pandas_edgelist.
  networkx/convert_matrix.py
Labels: Documentation

#3179 Fixes #3174, cb.is_numlike is deprecated in matplotlib
  networkx/drawing/nx_pylab.py
Labels: Maintenance

#3138 Add targets argument to all_simple_paths
  networkx/algorithms/simple_paths.py
  networkx/algorithms/tests/test_simple_paths.py
Labels: Enhancement

#3193 Speed up simple_cycles
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_cycles.py
Labels: Enhancement

#3194 Added dual Barabasi-Albert model
  networkx/generators/random_graphs.py
  networkx/generators/tests/test_random_graphs.py
Labels: Enhancement

#3205 implemented node_attr_dict_factory and graph_attr_dict_factory.
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Enhancement
