Repository networkx/networkx, pull requests merged in 2018-07, with the labels that each got.

#2905 Add stochastic block models to generators
  networkx/generators/community.py
  networkx/generators/tests/test_community.py
Labels: Enhancement

#3051 Fix graph_clique_number for clique-less graphs
  networkx/algorithms/clique.py
  networkx/algorithms/tests/test_clique.py
Labels: Enhancement

#3053 Adjust pandas printing to help travis
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: Maintenance

#3054 Pull request to set up python3.7 testing on travis
  .travis.yml
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/connectivity/edge_kcomponents.py
  networkx/algorithms/traversal/edgebfs.py
  networkx/algorithms/traversal/edgedfs.py
  networkx/generators/classic.py
  networkx/readwrite/sparse6.py
Labels: Maintenance

#3035 Use pyyaml updates
  requirements/extras.txt
Labels: Maintenance

#3055 update docs for transitive_reduction to show example using line_graph
  networkx/algorithms/dag.py
Labels: Documentation

#3049 Enumerate all topological sorts of a digraph
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: Enhancement

#3062 Speedup transitive_reduction
  networkx/algorithms/dag.py
Labels: Maintenance

#3069 add binary mode to open_file for view_pygraphviz.
  networkx/drawing/nx_agraph.py
Labels: Defect

#3070 Degree centrality bug fix.
  networkx/algorithms/centrality/degree_alg.py
  networkx/algorithms/centrality/tests/test_degree_centrality.py
Labels: Defect

#3068 faster, type-preserving from_pandas_edgelist
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: Enhancement

#3071 allow open_file to handle pathlib objects
  networkx/utils/decorators.py
  networkx/utils/tests/test_decorators.py
Labels: Enhancement

#3074 In all_simple_paths(). Replace list with OrderedDict for speedup
  networkx/algorithms/simple_paths.py
  networkx/algorithms/tests/test_simple_paths.py
Labels: Enhancement

#3073 Simplify the Graphview and SubGraphView system
  doc/reference/classes/digraph.rst
  doc/reference/classes/graph.rst
  doc/reference/classes/multidigraph.rst
  doc/reference/classes/multigraph.rst
  networkx/algorithms/clique.py
  networkx/algorithms/connectivity/edge_kcomponents.py
  networkx/algorithms/minors.py
  networkx/algorithms/operators/binary.py
  networkx/algorithms/operators/unary.py
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/tree/mst.py
  networkx/classes/coreviews.py
  networkx/classes/digraph.py
  networkx/classes/function.py
  networkx/classes/graph.py
  networkx/classes/graphviews.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/classes/ordered.py
  networkx/classes/tests/test_graphviews.py
  networkx/classes/tests/test_subgraphviews.py
  networkx/drawing/tests/test_pydot.py
  networkx/generators/line.py
  networkx/relabel.py
Labels: Enhancement

#3075 Update release notes for upcoming release
  doc/release/release_dev.rst
Labels: Documentation

#3076 [WIP] Added function to eulerize simple graphs to algorithms.euler
  CONTRIBUTORS.rst
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Enhancement

#3077 Depth-limited Breadth First Search
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/tests/test_bfs.py
Labels: Enhancement

#3080 Allow individual extras selection
  setup.py
Labels: Maintenance

#3082 Stop pydot expansion of graph attributes upon repeated to_from
  networkx/drawing/nx_agraph.py
  networkx/drawing/tests/test_agraph.py
Labels: Maintenance

#3083 Add test for random number generators leaving global RNGs untouched
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/asyn_fluid.py
  networkx/algorithms/community/tests/test_asyn_fluid.py
  networkx/tests/test_all_random_functions.py
Labels: Maintenance

#3039 Fix bugs in all_node_cuts, address #3025
  networkx/algorithms/connectivity/kcutsets.py
  networkx/algorithms/connectivity/tests/test_kcutsets.py
Labels: Defect

#3087 Numpy matrix edge fix issue 3086
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
Labels: Defect

#3092 Minor fix on paragraph #18 (proposal)
  doc/README.md
Labels: Documentation

#3091 Update docs with all functions left out of rst files
  INSTALL.rst
  doc/reference/algorithms/assortativity.rst
  doc/reference/algorithms/bridges.rst
  doc/reference/algorithms/centrality.rst
  doc/reference/algorithms/dag.rst
  doc/reference/algorithms/distance_measures.rst
  doc/reference/algorithms/euler.rst
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/isolates.rst
  doc/reference/algorithms/lowest_common_ancestors.rst
  doc/reference/algorithms/operators.rst
  doc/reference/algorithms/shortest_paths.rst
  doc/reference/algorithms/similarity.rst
  doc/reference/algorithms/smallworld.rst
  doc/reference/algorithms/smetric.rst
  doc/reference/algorithms/traversal.rst
  doc/reference/classes/index.rst
  doc/reference/convert.rst
  doc/reference/drawing.rst
  doc/reference/functions.rst
  doc/reference/generators.rst
  doc/reference/linalg.rst
  doc/reference/readwrite/gexf.rst
  doc/reference/readwrite/graphml.rst
  doc/reference/readwrite/json_graph.rst
  doc/reference/readwrite/pajek.rst
  doc/release/report_functions_without_rst_generated.py
  networkx/algorithms/smallworld.py
  networkx/classes/graph.py
  networkx/classes/graphviews.py
  networkx/drawing/nx_agraph.py
  networkx/generators/community.py
  networkx/linalg/modularitymatrix.py
Labels: Documentation

#3089 Add percolation centrality
  doc/reference/algorithms/centrality.rst
  networkx/algorithms/centrality/__init__.py
  networkx/algorithms/centrality/percolation.py
  networkx/algorithms/centrality/tests/test_percolation_centrality.py
Labels: Enhancement

#3095 make bellman_ford use same pred dict sentinal value as dijkstra
  doc/release/release_dev.rst
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: Maintenance

#3097 Add docstring to module for similarity
  networkx/algorithms/similarity.py
Labels: Documentation

#3101 Fix adjlist factory bug in DiGraph
  networkx/classes/digraph.py
  networkx/classes/tests/test_special.py
Labels: Defect
