Repository networkx/networkx, pull requests merged in 2019-11, with the labels that each got.

#3707 Use canonical url to help search engines
  doc/conf.py
Labels: Documentation, Enhancement

#3715 Remove old Python 2 code
  networkx/algorithms/clique.py
  networkx/algorithms/flow/networksimplex.py
  networkx/drawing/tests/test_pydot.py
  networkx/readwrite/gml.py
  networkx/readwrite/gpickle.py
  networkx/readwrite/graphml.py
  networkx/readwrite/json_graph/jit.py
Labels: Maintenance

#3713 K-truss is defined for edges being in (k-2) triangles and not for k triangles
  networkx/algorithms/core.py
  networkx/algorithms/tests/test_core.py
Labels: Defect, Maintenance

#3722 Enable optional tests on Python 3.8
  .travis.yml
Labels: Maintenance

#3724 Fix test_numpy_type to pass under Python 3.8
  .travis.yml
  networkx/readwrite/tests/test_gexf.py
Labels: Maintenance

#3723 Add links to data files
  examples/basic/plot_read_write.py
  examples/drawing/plot_atlas.py
  examples/drawing/plot_chess_masters.py
  examples/drawing/plot_circular_tree.py
  examples/drawing/plot_giant_component.py
  examples/drawing/plot_knuth_miles.py
  examples/drawing/plot_lanl_routes.py
  examples/drawing/plot_sampson.py
  examples/drawing/plot_spectral_grid.py
  examples/drawing/plot_unix_email.py
  examples/graph/plot_karate_club.py
  examples/graph/plot_roget.py
  examples/graph/plot_words.py
  examples/javascript/force.py
  examples/pygraphviz/plot_write_dotfile.py
  examples/subclass/plot_printgraph.py
Labels: Documentation

#3734 Sample code for subgraph copy: add parenthesis to is_multigraph
  networkx/classes/graph.py
Labels: Documentation

#3735 Fixed typo
  networkx/algorithms/connectivity/disjoint_paths.py
Labels: Documentation
