Repository networkx/networkx, pull requests merged in 2019-09, with the labels that each got.

#3566 Fix wrong title
  doc/reference/algorithms/smallworld.rst
Labels: Documentation

#3568 Fix typo in all_pairs_node_connectivity method's doctring in connectivity.py
  networkx/algorithms/approximation/connectivity.py
Labels: Documentation

#3569 Fix and Improve multiple docstrings in graph.py
  networkx/classes/graph.py
Labels: Documentation

#3570 Improved graph class selection table
  doc/reference/classes/index.rst
Labels: Documentation

#3534 Add spiral layout for graph drawing
  doc/reference/drawing.rst
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#3579 Handle k==n within the Watts-Strogatz graph generator
  networkx/generators/random_graphs.py
  networkx/generators/tests/test_random_graphs.py
Labels: Maintenance

#3400 Floyd-Warshall Optimization
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/shortest_paths/tests/test_dense.py
Labels: Enhancement

#3512 Prim from list to set
  networkx/algorithms/tree/mst.py
  networkx/algorithms/tree/tests/test_mst.py
Labels: Enhancement

#3588 Fix issue 3491
  networkx/readwrite/edgelist.py
  networkx/readwrite/tests/test_edgelist.py
Labels: Enhancement

#3596 Remove Py2 future imports
  examples/drawing/plot_directed.py
  examples/graph/plot_roget.py
  networkx/__init__.py
  networkx/algorithms/approximation/dominating_set.py
  networkx/algorithms/approximation/tests/test_clique.py
  networkx/algorithms/assortativity/connectivity.py
  networkx/algorithms/bipartite/redundancy.py
  networkx/algorithms/bipartite/tests/test_redundancy.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/eigenvector.py
  networkx/algorithms/centrality/harmonic.py
  networkx/algorithms/centrality/load.py
  networkx/algorithms/centrality/percolation.py
  networkx/algorithms/centrality/reaching.py
  networkx/algorithms/centrality/tests/test_betweenness_centrality.py
  networkx/algorithms/centrality/tests/test_percolation_centrality.py
  networkx/algorithms/centrality/tests/test_reaching.py
  networkx/algorithms/cluster.py
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/community/tests/test_quality.py
  networkx/algorithms/connectivity/connectivity.py
  networkx/algorithms/cuts.py
  networkx/algorithms/efficiency.py
  networkx/algorithms/isomorphism/temporalisomorphvf2.py
  networkx/algorithms/link_prediction.py
  networkx/algorithms/richclub.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/similarity.py
  networkx/algorithms/sparsifiers.py
  networkx/algorithms/structuralholes.py
  networkx/algorithms/swap.py
  networkx/algorithms/tests/test_boundary.py
  networkx/algorithms/tests/test_cuts.py
  networkx/algorithms/tests/test_efficiency.py
  networkx/algorithms/tests/test_wiener.py
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/triads.py
  networkx/algorithms/wiener.py
  networkx/classes/function.py
  networkx/classes/graph.py
  networkx/drawing/layout.py
  networkx/generators/classic.py
  networkx/generators/community.py
  networkx/generators/degree_seq.py
  networkx/generators/directed.py
  networkx/generators/geometric.py
  networkx/generators/joint_degree_seq.py
  networkx/generators/lattice.py
  networkx/generators/random_graphs.py
  networkx/generators/stochastic.py
  networkx/linalg/modularitymatrix.py
  networkx/readwrite/tests/test_graph6.py
  networkx/release.py
  networkx/tests/test_all_random_functions.py
  networkx/utils/contextmanagers.py
  networkx/utils/tests/test_contextmanager.py
Labels: Maintenance

#3574 add internet_as_graph generator
  doc/reference/generators.rst
  networkx/generators/__init__.py
  networkx/generators/internet_as_graphs.py
  networkx/generators/tests/test_internet_as_graphs.py
  networkx/tests/test_all_random_functions.py
Labels: Enhancement

#3598 remove cyclical references from OutEdgeDataView
  networkx/classes/reportviews.py
Labels: Maintenance

#3390 Add minimum source and target margin to draw_networkx_edges.
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Enhancement

#3599 fix to_directed function
  networkx/classes/function.py
Labels: Defect

#3606 Fixes #3573:GEXF output problem
  networkx/readwrite/gexf.py
  networkx/readwrite/tests/test_gexf.py
Labels: Maintenance

#3604 Global efficiency attempt to speed up
  doc/reference/algorithms/efficiency_measures.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/efficiency_measures.py
  networkx/generators/tests/test_degree_seq.py
Labels: Maintenance

#3603 Bugfix: Added flexibility in reading values for label and id
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: Enhancement

#3267 Add method floyd-warshall to average_shortest_path_length
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
Labels: Enhancement

#3608 Replaced is with == and minor pycodestyle fixes
  networkx/convert_matrix.py
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
Labels: Maintenance

#3609 Fix many documentation based Issues
  networkx/__init__.py
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/betweenness_subset.py
  networkx/algorithms/community/community_utils.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/community/tests/test_utils.py
  networkx/testing/__init__.py
  networkx/testing/test.py
  networkx/tests/README
Labels: Documentation, Maintenance

#3611 Resolve many documentation issues
  doc/release/migration_guide_from_1.x_to_2.0.rst
  examples/drawing/plot_knuth_miles.py
  networkx/algorithms/centrality/closeness.py
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/depth_first_search.py
  networkx/algorithms/traversal/edgebfs.py
  networkx/drawing/layout.py
Labels: Documentation
