Repository networkx/networkx, pull requests merged in 2019-10, with the labels that each got.

#3613 Transitive_closure now finds self-loops when cycles present
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: Defect

#3183 Add support for initializing pagerank_scipy
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
Labels: Enhancement

#3614 Add last 7 lines of Gomory-hu algorithm Fixes #3293
  networkx/algorithms/flow/gomory_hu.py
Labels: Defect

#3399 Implemented Euler Path functions
  doc/reference/algorithms/euler.rst
  doc/reference/algorithms/index.rst
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Documentation, Enhancement

#3619 Fix the direction of edges in label_propagation.py
  networkx/algorithms/community/label_propagation.py
Labels: Defect

#3620 Removed unused import of random module
  networkx/algorithms/approximation/clustering_coefficient.py
Labels: Maintenance

#3626 Fix operation order in partial_duplication_graph
  networkx/generators/duplication.py
Labels: Defect

#3629 Keep shells with 1 node away from origin in shell_layout
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Defect

#3628 Allow jit_graph to read json string or json object
  networkx/readwrite/json_graph/jit.py
  networkx/readwrite/json_graph/tests/test_jit.py
Labels: Enhancement

#3621 Fix typo within incode documentation
  networkx/algorithms/coloring/greedy_coloring.py
Labels: Documentation

#3631 pycodestyle and update docs for greedy_coloring.py+tests
  networkx/algorithms/coloring/greedy_coloring.py
  networkx/algorithms/coloring/tests/test_coloring.py
Labels: Documentation

#3634 Handle edgeattr in from_pandas_edgelist when no columns match request
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: Defect

#3622 Make draft of release notes for v2.4
  doc/release/contribs.py
  doc/release/release_2.4.rst
  doc/release/release_dev.rst
Labels: Documentation, Maintenance

#3635 Use recent pypy
  .travis.yml
  tools/travis/osx_install.sh
Labels: Maintenance

#3636 add check of attr type before converting inf/nan in GEXF
  networkx/readwrite/gexf.py
  networkx/readwrite/tests/test_gexf.py
Labels: Defect

#3638 Fix sphinx errors And add links to single_source_dijkstra in docs for dijkstra_path/length
  CONTRIBUTORS.rst
  doc/reference/algorithms/centrality.rst
  doc/reference/algorithms/dispersion.rst
  doc/reference/algorithms/index.rst
  doc/release/index.rst
  examples/graph/dot_atlas.py
  networkx/algorithms/bipartite/basic.py
  networkx/algorithms/centrality/voterank_alg.py
  networkx/algorithms/isomorphism/ismags.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/generators/cographs.py
  networkx/generators/harary_graph.py
Labels: Documentation

#3627 Document `subgraph_view` function with support for filter functions
  doc/reference/functions.rst
  networkx/classes/function.py
  networkx/classes/graphviews.py
Labels: Documentation

#3648 Test Python 3.8 with AppVeyor
  .appveyor.yml
  tools/appveyor/install.ps1
Labels: Maintenance

#3650 Remove remaining SkipTests
  networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality.py
  networkx/readwrite/tests/test_shp.py
Labels: Maintenance

#3645 fix documentation notes (#3644)
  networkx/algorithms/clique.py
Labels: Documentation

#3651 Test Py 3.8.0 on AppVeyor
  tools/appveyor/install.ps1
Labels: Maintenance

#3660 Drop support for Python 3.5
  .appveyor.yml
  .travis.yml
  INSTALL.rst
  doc/release/release_dev.rst
  examples/advanced/plot_parallel_betweenness.py
  networkx/__init__.py
  networkx/release.py
  setup.py
Labels: Maintenance

#3661 Fix Docs Typo in networkx.drawing.nx_pylab.draw_spectral
  networkx/drawing/nx_pylab.py
Labels: Documentation

#3670 Use itertools accumulate
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
  networkx/algorithms/richclub.py
  networkx/algorithms/tree/operations.py
  networkx/generators/classic.py
  networkx/generators/geometric.py
  networkx/utils/misc.py
Labels: Maintenance

#3678 Enable tests
  networkx/algorithms/bipartite/tests/test_spectral_bipartivity.py
  networkx/algorithms/community/tests/test_asyn_fluid.py
  networkx/algorithms/node_classification/tests/test_harmonic_function.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
  networkx/algorithms/tests/test_bridges.py
  networkx/algorithms/tests/test_chains.py
  networkx/algorithms/tests/test_euler.py
  networkx/algorithms/traversal/tests/test_beamsearch.py
  networkx/algorithms/traversal/tests/test_bfs.py
  networkx/algorithms/traversal/tests/test_dfs.py
  networkx/algorithms/tree/tests/test_mst.py
  networkx/algorithms/tree/tests/test_recognition.py
  networkx/classes/tests/test_ordered.py
  networkx/classes/tests/test_special.py
  networkx/generators/tests/test_duplication.py
  networkx/generators/tests/test_random_graphs.py
  networkx/readwrite/tests/test_graph6.py
  networkx/readwrite/tests/test_sparse6.py
  networkx/utils/tests/test_decorators.py
Labels: Defect, Maintenance

#3646 `contracted_nodes` copy flag added
  networkx/algorithms/minors.py
  networkx/algorithms/tests/test_minors.py
Labels: Enhancement

#3681 Enable ThinGraph tests
  networkx/classes/tests/test_digraph.py
  networkx/classes/tests/test_graph.py
  networkx/classes/tests/test_special.py
Labels: Defect, Maintenance

#3647 Optimize _single_shortest_path_length
  networkx/algorithms/shortest_paths/unweighted.py
Labels: Maintenance

#3676 Fix issue 3431: Return error in case of bad input to make_small_graph
  networkx/generators/small.py
  networkx/generators/tests/test_small.py
Labels: Defect

#3689 Fix typo: Laplacion -> Laplacian
  networkx/drawing/layout.py
Labels: Documentation

#3690 Add tests
  .coveragerc
  networkx/algorithms/isomorphism/temporalisomorphvf2.py
  networkx/algorithms/minors.py
  networkx/linalg/tests/test_attrmatrix.py
  networkx/linalg/tests/test_graphmatrix.py
  networkx/linalg/tests/test_laplacian.py
  networkx/linalg/tests/test_modularity.py
  networkx/readwrite/adjlist.py
  networkx/readwrite/tests/test_adjlist.py
Labels: Maintenance

#3666 Lukes algorithm implementation
  doc/reference/algorithms/community.rst
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/lukes.py
  networkx/algorithms/community/tests/test_lukes.py
Labels: Enhancement

#3693 Remove shim that worked around using starmap
  doc/conf.py
  examples/advanced/plot_parallel_betweenness.py
Labels: Defect

#3698 Add colormap and color limits to LineCollection
  networkx/drawing/nx_pylab.py
Labels: Defect

#3697 WIP: Fix matplotlib deprecation
  networkx/drawing/tests/test_pylab.py
  requirements/extras.txt
Labels: Maintenance

#3691 Add NumFOCUS CoC
  CODE_OF_CONDUCT.rst
  doc/developer/code_of_conduct.rst
  doc/developer/index.rst
Labels: Maintenance

#3699 Update docs to be more accurate about speed of G.neighbors
  networkx/classes/graph.py
Labels: Documentation
