Repository networkx/networkx, pull requests merged in 2019-06, with the labels that each got.

#3458 Replace cb.iterable with np.iterable
  networkx/drawing/nx_pylab.py
Labels: Maintenance

#3476 Don't remove ticks of other pyplot axes
  networkx/drawing/nx_pylab.py
Labels: Defect

#3468 Fix typo in "G>raph Modelling Language"
  networkx/readwrite/gml.py
Labels: Documentation

#3462 Naive k-truss algorithm implementation.
  doc/reference/algorithms/core.rst
  networkx/algorithms/core.py
  networkx/algorithms/tests/test_core.py
Labels: Enhancement

#3385 New Feature - Resistance Distance
  .gitignore
  CONTRIBUTORS.rst
  doc/reference/algorithms/distance_measures.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: Enhancement

#3454 No multigraphs for betweenness
  networkx/algorithms/centrality/betweenness.py
Labels: Defect

#3465 Wheels are python 3 only
  setup.cfg
Labels: Maintenance

#3487 Fix deprecation warning with Python 3.7
  networkx/drawing/nx_pylab.py
Labels: Maintenance

#3484 Fix dfs_preorder_nodes docstring saying "edges" instead of "nodes"
  networkx/algorithms/traversal/depth_first_search.py
Labels: Documentation

#3437 Added group closeness and group degree centralities
  doc/reference/algorithms/centrality.rst
  networkx/algorithms/centrality/group.py
  networkx/algorithms/centrality/tests/test_group.py
Labels: Enhancement

#3495 Correct docstring errors in traversal
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/depth_first_search.py
Labels: Documentation

#3494 Fixes Issue #3493 - Bug in lexicographical_topological_sort()
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: Defect

#3377 AT-free graph recognition
  CONTRIBUTORS.rst
  doc/reference/algorithms/asteroidal.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/asteroidal.py
  networkx/algorithms/tests/test_asteroidal.py
Labels: Enhancement
