Repository networkx/networkx, pull requests merged in 2019-05, with the labels that each got.

#3415 Fix spring_layout bug with fixed nodes
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Defect

#3411 Move LFR_benchmark to generators
  doc/reference/algorithms/community.rst
  doc/reference/generators.rst
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/community_generators.py
  networkx/algorithms/community/tests/test_generators.py
  networkx/generators/community.py
  networkx/generators/tests/test_community.py
  networkx/tests/test_all_random_functions.py
Labels: Maintenance

#2939 Add barycenter algorithm
  doc/reference/algorithms/distance_measures.rst
  doc/release/release_dev.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: Enhancement

#3401 Add bethe hessian matrix
  doc/reference/linalg.rst
  networkx/linalg/__init__.py
  networkx/linalg/bethehessianmatrix.py
  networkx/linalg/spectrum.py
  networkx/linalg/tests/test_bethehessian.py
  networkx/linalg/tests/test_spectrum.py
Labels: Enhancement

#3409 Binomial trees generator
  doc/reference/generators.rst
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: Enhancement

#3395 Fix edge_color inconsistency with node_color and description.
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Documentation, Enhancement

#3421 Adding module for group centrality measures
  doc/reference/algorithms/centrality.rst
  networkx/algorithms/centrality/__init__.py
  networkx/algorithms/centrality/group.py
  networkx/algorithms/centrality/tests/test_group.py
Labels: Enhancement

#3423 Improve edgelist See Also
  networkx/readwrite/edgelist.py
Labels: Documentation

#3424 Typo fix
  networkx/classes/graph.py
Labels: Documentation

#3429 Minor fix in documentation
  doc/reference/drawing.rst
Labels: Documentation

#3425 Fix centrality betweeness subset
  networkx/algorithms/centrality/betweenness_subset.py
  networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py
Labels: Defect

#3222 Add two versions of Simrank similarity
  doc/reference/algorithms/similarity.rst
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
Labels: Enhancement

#3438 [Linealg] Reorder and complete doc
  doc/reference/linalg.rst
Labels: Documentation

#3447 Additional topo_order parameter for functions that rely on topological_sort
  networkx/algorithms/components/semiconnected.py
  networkx/algorithms/dag.py
Labels: Enhancement

#3435 Implemented subgraph monomorphism
  networkx/algorithms/isomorphism/isomorphvf2.py
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
Labels: Enhancement

#3451 Set seed in random_degree_sequence_graph docstring test
  networkx/generators/degree_seq.py
Labels: Maintenance
