Repository networkx/networkx, pull requests merged in 2019-08, with the labels that each got.

#3514 Restore checking PyPy3
  .travis.yml
  networkx/algorithms/bipartite/projection.py
  networkx/algorithms/chordal.py
  networkx/algorithms/community/kclique.py
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_clique.py
  networkx/algorithms/tests/test_covering.py
  networkx/algorithms/tests/test_cycles.py
  networkx/algorithms/tests/test_matching.py
  networkx/algorithms/tests/test_planar_drawing.py
Labels: Maintenance

#3535 Linear prufer coding
  networkx/algorithms/tree/coding.py
Labels: Enhancement

#3507 Fix inverse_line_graph.
  networkx/generators/line.py
  networkx/tests/test_line.py
Labels: Defect

#3508 Fix A* returning wrong solution
  networkx/algorithms/shortest_paths/astar.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
Labels: Defect

#3527 Implement minimum weight full matching of bipartite graphs
  CONTRIBUTORS.rst
  networkx/algorithms/bipartite/matching.py
  networkx/algorithms/bipartite/tests/test_matching.py
Labels: Enhancement

#3353 Get chordal graph for #1054
  networkx/algorithms/chordal.py
  networkx/algorithms/tests/test_chordal.py
Labels: Enhancement

#3445 Faster transitive closure computation for DAGs
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
  networkx/algorithms/traversal/breadth_first_search.py
Labels: Enhancement

#3536 Write mixed-type attributes correctly in write_graphml_lxml
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_graphml.py
Labels: Maintenance

#3538 Fixes some edge cases for inverse_line_graph().
  networkx/generators/line.py
  networkx/generators/tests/test_line.py
  networkx/tests/test_line.py
Labels: Enhancement

#3444 Incremental Closeness Centrality (undirected, unweighted graphs)
  doc/reference/algorithms/centrality.rst
  networkx/algorithms/centrality/closeness.py
  networkx/algorithms/centrality/tests/test_closeness_centrality.py
Labels: Enhancement

#3545 Fixes bug in networkx.algorithms.community.label_propagation.asyn_lpa_communities
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/tests/test_label_propagation.py
Labels: Defect

#3540 When exporting to GML, write non 32-bit numbers as strings.
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: Maintenance

#3554 Try to bug Fix #3552
  networkx/drawing/nx_pylab.py
Labels: Defect

#3551 add Directed Joint Degree Graph generator
  doc/reference/generators.rst
  networkx/generators/joint_degree_seq.py
  networkx/generators/tests/test_joint_degree_seq.py
Labels: Enhancement

#3557 typo
  networkx/algorithms/hierarchy.py
Labels: Documentation

#3555 Fix a few documentation issues for the bipartite algorithm reference
  doc/reference/algorithms/bipartite.rst
  networkx/algorithms/bipartite/matching.py
Labels: Documentation

#3542 explicitly stated i.j convention in to_numpy_array
  networkx/convert_matrix.py
Labels: Documentation

#3564 Fix a typo in docstring for get_edge_data
  networkx/classes/graph.py
Labels: Documentation
