Repository networkx/networkx, pull requests merged in 2019-12, with the labels that each got.

#3741 fix citation links
  doc/citing.rst
Labels: Documentation

#3738 remove f strings from setup.py for clear error message < py3.6
  setup.py
Labels: Maintenance

#3649 3511 gml list support
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: Enhancement

#3747 added linestyle as argument
  networkx/drawing/nx_pylab.py
Labels: Defect

#3752 Link to files needed for example
  examples/javascript/force.py
Labels: Documentation

#3760 Remove unused variable so grid_graph() supports dim=tuple
  networkx/generators/lattice.py
Labels: Defect

#3757 Sudoku generator issue 3756
  doc/reference/generators.rst
  networkx/generators/__init__.py
  networkx/generators/sudoku.py
  networkx/generators/tests/test_sudoku.py
Labels: Enhancement

#3764 Fix scaling of single node shells in shall_layout
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Defect

#3742 Adding triadic analysis functions
  .gitignore
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
Labels: Enhancement
