Repository networkx/networkx, pull requests merged in 2020-12, with the labels that each got.

#4403 Don't import nx from networkx
  examples/basic/plot_properties.py
  examples/graph/plot_degree_sequence.py
  examples/graph/plot_erdos_renyi.py
  examples/graph/plot_roget.py
  networkx/algorithms/centrality/tests/test_reaching.py
Labels: Maintenance

#4378 Modify and document behavior of nodelist param in draw_networkx_edges.
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Documentation, Enhancement

#4408 Add circuit plot
  examples/applications/plot_circuits.py
Labels: Documentation

#4409 Add words graph plot
  examples/graph/plot_words.py
Labels: Documentation

#4410 DOC: Remove repeated words
  doc/release/api_1.6.rst
  doc/release/release_2.0.rst
  networkx/algorithms/approximation/tests/test_approx_clust_coeff.py
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/centrality/subgraph_alg.py
  networkx/algorithms/connectivity/disjoint_paths.py
  networkx/algorithms/connectivity/edge_kcomponents.py
  networkx/algorithms/connectivity/tests/test_edge_kcomponents.py
  networkx/algorithms/isomorphism/isomorphvf2.py
  networkx/algorithms/minors.py
  networkx/algorithms/operators/binary.py
  networkx/algorithms/planar_drawing.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/algorithms/simple_paths.py
  networkx/classes/graph.py
  networkx/drawing/nx_pylab.py
  networkx/generators/atlas.py
  networkx/generators/stochastic.py
  networkx/linalg/algebraicconnectivity.py
  networkx/linalg/laplacianmatrix.py
  networkx/utils/rcm.py
Labels: Maintenance

#4411 Add plot for rcm example
  examples/algorithms/plot_rcm.py
  requirements/example.txt
Labels: Documentation

#4398 fix small index iteration bug in kernighan_lin algorithm
  networkx/algorithms/community/kernighan_lin.py
Labels: Defect

#4412 Use str dunder
  examples/drawing/plot_atlas.py
  examples/drawing/plot_lanl_routes.py
  examples/graph/dot_atlas.py
  examples/graph/plot_roget.py
  examples/graph/plot_words.py
Labels: Maintenance

#4326 Use xetex for uft8 latex backend
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
  .travis.yml
  doc/conf.py
Labels: Documentation, Enhancement, Maintenance

#4407 DOC: geospatial example using lines
  examples/geospatial/plot_geopandas.py
  examples/geospatial/plot_lines.py
  examples/geospatial/plot_pysal.py
  examples/geospatial/rivers.geojson
  requirements/example.txt
Labels: Documentation

#4366 add plotting examples for geospatial examples
  examples/geospatial/cholera_cases.gpkg
  examples/geospatial/nuts1.geojson
  examples/geospatial/plot_delaunay.py
  examples/geospatial/plot_points.py
  examples/geospatial/plot_polygons.py
  examples/geospatial/schools.dbf
  examples/geospatial/schools.prj
  examples/geospatial/schools.sbn
  examples/geospatial/schools.sbx
  examples/geospatial/schools.shp
  examples/geospatial/schools.shp.xml
  examples/geospatial/schools.shx
  requirements/example.txt
Labels: Documentation

#4418 Increase coverage in graphviews.py
  networkx/classes/tests/test_graphviews.py
Labels: Maintenance

#4422 Refactor gallery
  doc/conf.py
  examples/algorithms/plot_circuits.py
  examples/algorithms/plot_decomposition.py
  examples/algorithms/plot_dedensification.py
  examples/algorithms/plot_rcm.py
  examples/applications/README.txt
  examples/drawing/plot_atlas.py
  examples/drawing/plot_circular_tree.py
  examples/drawing/plot_giant_component.py
  examples/drawing/plot_lanl_routes.py
  examples/drawing/plot_multipartite_graph.py
  examples/external/README.txt
  examples/external/force/README.txt
  examples/external/force/force.css
  examples/external/force/force.html
  examples/external/force/force.js
  examples/external/javascript_force.py
  examples/external/plot_jit.py
  examples/external/plot_pygraphviz.py
  examples/geospatial/plot_delaunay.py
  examples/geospatial/plot_osmnx.py
  examples/graph/dot_atlas.py
  examples/graph/plot_expected_degree_sequence.py
  examples/javascript/README.txt
  examples/jit/README.txt
  examples/pygraphviz/README.txt
  examples/pygraphviz/plot_pygraphviz_attributes.py
  examples/pygraphviz/plot_pygraphviz_draw.py
  examples/pygraphviz/plot_pygraphviz_simple.py
  examples/pygraphviz/plot_write_dotfile.py
  examples/subclass/plot_antigraph.py
  examples/subclass/plot_printgraph.py
Labels: Documentation, Maintenance

#4413 Safer repr format of variables
  networkx/algorithms/clique.py
  networkx/classes/graph.py
  networkx/convert_matrix.py
  networkx/generators/spectral_graph_forge.py
  networkx/linalg/algebraicconnectivity.py
  networkx/readwrite/gml.py
Labels: Maintenance

#4424 Updates to docs and imports for classic.py
  networkx/generators/classic.py
Labels: Documentation

#4429 Remove advanced example section
  examples/advanced/README.txt
  examples/advanced/plot_heavy_metal_umlaut.py
  examples/algorithms/plot_iterated_dynamical_systems.py
  examples/algorithms/plot_parallel_betweenness.py
  examples/drawing/plot_eigenvalues.py
Labels: Maintenance

#4431 Add coreview objects to documentation
  doc/reference/classes/index.rst
  networkx/classes/coreviews.py
Labels: Documentation

#4430 Add gallery example for drawing self-loops.
  examples/drawing/plot_selfloops.py
Labels: Documentation

#4404 Add igraph example
  examples/external/plot_igraph.py
  requirements/example.txt
Labels: Documentation

#4427 Collect graphviz examples
  doc/conf.py
  examples/graphviz/README.txt
  examples/graphviz/lanl_routes.edgelist
  examples/graphviz/plot_001_pygraphviz.py
  examples/graphviz/plot_atlas.py
  examples/graphviz/plot_circular_tree.py
  examples/graphviz/plot_decomposition.py
  examples/graphviz/plot_giant_component.py
  examples/graphviz/plot_lanl_routes.py
Labels: Documentation

#4395 NXEP 3: Allow generators to yield from edgelists
  doc/developer/nxeps/index.rst
  doc/developer/nxeps/nxep-0003.rst
Labels: Documentation, Enhancement

#4417 Update geospatial readme
  doc/Makefile
  examples/geospatial/README.txt
  examples/geospatial/extended_description.rst
Labels: Documentation

#4438 Improves description bfs_predecessors and bfs_successors.
  networkx/algorithms/traversal/breadth_first_search.py
Labels: Documentation

#4428 Deprecate jit
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  examples/external/plot_jit.py
  networkx/conftest.py
  networkx/readwrite/json_graph/jit.py
Labels: Maintenance

#4450 JavaScript example: fix link
  examples/external/javascript_force.py
Labels: Documentation

#4449 Deprecate consume
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
  networkx/conftest.py
  networkx/utils/misc.py
Labels: Maintenance

#4447 DOC: Switch from napoleon to numpydoc sphinx extension
  doc/conf.py
  networkx/algorithms/approximation/clique.py
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/centrality/load.py
  networkx/algorithms/chordal.py
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/lukes.py
  networkx/algorithms/components/biconnected.py
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/connectivity/edge_kcomponents.py
  networkx/algorithms/d_separation.py
  networkx/algorithms/euler.py
  networkx/algorithms/graph_hashing.py
  networkx/algorithms/hybrid.py
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/moral.py
  networkx/algorithms/node_classification/hmn.py
  networkx/algorithms/node_classification/lgc.py
  networkx/algorithms/non_randomness.py
  networkx/algorithms/operators/unary.py
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/unweighted.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/algorithms/similarity.py
  networkx/classes/coreviews.py
  networkx/classes/digraph.py
  networkx/classes/function.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/drawing/layout.py
  networkx/drawing/nx_pydot.py
  networkx/drawing/nx_pylab.py
  networkx/generators/geometric.py
  networkx/generators/internet_as_graphs.py
  networkx/generators/interval_graph.py
  networkx/generators/mycielski.py
  networkx/generators/random_graphs.py
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/pajek.py
  requirements/doc.txt
Labels: Documentation, Maintenance

#4455 Correct networkxsimplex docstring re: multigraph
  networkx/algorithms/flow/networksimplex.py
Labels: Documentation

#4138 Maxcut heuristics
  doc/reference/algorithms/approximation.rst
  networkx/algorithms/approximation/__init__.py
  networkx/algorithms/approximation/maxcut.py
  networkx/algorithms/approximation/tests/test_maxcut.py
Labels: Enhancement

#4461 binomial_tree() with "create_using parameter
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: Enhancement

#4467 Reorganize tests
  .github/workflows/lint.yml
  .github/workflows/test-default.yml
  .github/workflows/test-extra.yml
  .github/workflows/test-prereleases.yml
  .github/workflows/test.yml
Labels: Maintenance

#4469 Drop Py3.6 support per NEP 29
  .appveyor.yml
  .github/workflows/test.yml
  INSTALL.rst
  doc/release/release_dev.rst
  networkx/__init__.py
  networkx/release.py
  setup.py
Labels: Maintenance

#4294 Add random_ordered_tree and forest_str
  networkx/generators/trees.py
  networkx/readwrite/__init__.py
  networkx/readwrite/tests/test_text.py
  networkx/readwrite/text.py
Labels: Enhancement

#4448 Deprecate iterable
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/generators/lattice.py
  networkx/utils/misc.py
Labels: Maintenance

#4466 Allow relabel_nodes mapping to have non-node keys that get ignored
  doc/release/release_dev.rst
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Enhancement

#4474 Fixed docs + added decorator for k_components
  networkx/algorithms/approximation/kcomponents.py
Labels: Defect

#4477 Update docs for clustering Fixes #4348
  networkx/algorithms/cluster.py
Labels: Documentation

#4425 Handle self-loops for single self-loop (drawing)
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Defect

#4482 Update GH actions links in README
  README.rst
Labels: Maintenance

#4488 Reenable tests
  networkx/algorithms/centrality/tests/test_katz_centrality.py
  networkx/algorithms/isomorphism/tests/test_ismags.py
  networkx/algorithms/tests/test_threshold.py
Labels: Maintenance

#4494 Update Sphinx
  requirements/doc.txt
Labels: Maintenance

#4495 Update pre-commit
  requirements/developer.txt
Labels: Maintenance
