Repository networkx/networkx, pull requests merged in 2020-02, with the labels that each got.

#3807 option for partially-periodic lattices (networkx #3586)
  networkx/generators/lattice.py
  networkx/generators/tests/test_lattice.py
Labels: Enhancement

#3798 Prevent KeyError on subgraph_is_monomorphic
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
  networkx/algorithms/isomorphism/vf2userfunc.py
Labels: Defect

#3804 Trophic Levels #3736
  doc/reference/algorithms/centrality.rst
  networkx/algorithms/centrality/__init__.py
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/centrality/trophic.py
Labels: Enhancement

#3810 UnionFind's union doesn't accurately track set sizes
  networkx/utils/tests/test_unionfind.py
  networkx/utils/union_find.py
Labels: Defect

#3816 Remove whitespace
  networkx/classes/digraph.py
Labels: Documentation

#3822 reconsider the lobster generator
  networkx/generators/random_graphs.py
  networkx/generators/tests/test_random_graphs.py
Labels: Defect

#3838 Fix typo
  networkx/readwrite/gexf.py
Labels: Documentation

#3840 fix typo
  networkx/algorithms/traversal/breadth_first_search.py
Labels: Documentation
