Repository networkx/networkx, pull requests merged in 2020-11, with the labels that each got.

#4310 Improve readwrite test coverage
  networkx/readwrite/json_graph/tests/test_tree.py
  networkx/readwrite/tests/test_edgelist.py
Labels: Maintenance

#4312 Fix typo
  networkx/readwrite/gexf.py
Labels: Documentation

#4240 adds dedensification function
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/summarization.rst
  examples/algorithms/plot_dedensification.py
  networkx/algorithms/__init__.py
  networkx/algorithms/summarization.py
  networkx/algorithms/tests/test_summarization.py
Labels: Enhancement

#4340 TST: improve multigraph test coverage to 100%
  networkx/classes/tests/test_multigraph.py
Labels: Maintenance

#4330 Add rainbow coloring example to gallery.
  examples/drawing/plot_rainbow_coloring.py
Labels: Documentation

#4303 Test on Python 3.9
  .appveyor.yml
  .github/workflows/testing.yml
  .travis.yml
  INSTALL.rst
  networkx/release.py
  requirements/default.txt
Labels: Maintenance

#4342 Sphinx33
  doc/release/index.rst
  examples/algorithms/plot_dedensification.py
  examples/drawing/plot_degree.py
  networkx/algorithms/minors.py
  requirements/doc.txt
Labels: Maintenance

#4333 Fix bug where changing a yielded component set breaks the component finding routine.
  networkx/algorithms/components/strongly_connected.py
  networkx/algorithms/components/tests/test_strongly_connected.py
  networkx/algorithms/components/tests/test_weakly_connected.py
  networkx/algorithms/components/weakly_connected.py
Labels: Defect

#4304 Updates to slicing error message for reportviews
  networkx/classes/reportviews.py
  networkx/classes/tests/test_reportviews.py
Labels: Maintenance

#4317 Eulerian path fix
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Defect, Enhancement

#4284 Add FutureWarning in preparation for simplifying cytoscape function signatures.
  doc/developer/deprecations.rst
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
Labels: Maintenance

#4296 Move a few imports inside functions to improve import speed of the library
  networkx/__init__.py
  networkx/generators/community.py
  networkx/generators/geometric.py
  networkx/generators/intersection.py
  networkx/generators/lattice.py
  networkx/linalg/algebraicconnectivity.py
  networkx/readwrite/gexf.py
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_graphml.py
Labels: Maintenance

#4287 Cleanup algebraicconnectivity
  networkx/linalg/algebraicconnectivity.py
  networkx/linalg/tests/test_algebraic_connectivity.py
  networkx/linalg/tests/test_laplacian.py
Labels: Maintenance

#4320 Use GH actions for Linux CI
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/test-default.yml
  .github/workflows/test-extra.yml
  .github/workflows/test-prereleases.yml
  .travis.yml
  tools/travis/before_install.sh
  tools/travis/script.sh
Labels: Maintenance

#4345 Fix
  .github/workflows/deploy-docs.yml
  .travis.yml
Labels: Defect, Maintenance

#4321 Update to_dict_of_dict edge_data
  networkx/convert.py
  networkx/tests/test_convert.py
Labels: Documentation, Maintenance

#4339 Update adjacency_iter to adjacency
  examples/subclass/plot_antigraph.py
Labels: Defect

#4346 Test and document missing nodes/edges in set_{node/edge}_attributes
  networkx/classes/function.py
  networkx/classes/tests/test_function.py
Labels: Documentation, Maintenance

#4344 Update test euler
  doc/release/release_dev.rst
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Enhancement

#4298 Deprecate nx_shp
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
  .travis.yml
  doc/conf.py
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  examples/geospatial/README.txt
  examples/geospatial/plot_geopandas.py
  examples/geospatial/plot_osmnx.py
  examples/geospatial/plot_pysal.py
  networkx/readwrite/nx_shp.py
  requirements/example.txt
  tools/travis/build_docs.sh
Labels: Enhancement, Maintenance

#4351 Refactor and improve test coverage for restricted_view and selfloop_edges
  networkx/classes/tests/test_function.py
Labels: Maintenance

#4297 Enable mayavi in sphinx gallery.
  .circleci/config.yml
  doc/conf.py
  examples/3d_drawing/plot_mayavi2_spring.py
  requirements/example.txt
Labels: Documentation

#4356 Use bidirection_dijkstra as default in weighted shortest_path
  networkx/algorithms/shortest_paths/generic.py
Labels: Enhancement

#4359 Add unit tests for utils.misc.flatten
  networkx/utils/misc.py
  networkx/utils/tests/test_misc.py
Labels: Maintenance

#4355 Improve test coverage for coreviews.py
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/classes/coreviews.py
  networkx/classes/tests/test_coreviews.py
Labels: Enhancement

#4358 Update tutorial.rst - Fixes #4249
  doc/tutorial.rst
Labels: Documentation

#4365 Bugfix for issue 4336, moving try/except and adding else clause
  networkx/utils/misc.py
Labels: Defect

#4361 Added nodelist attribute to triadic_census
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
Labels: Enhancement

#4360 API: always use list of FancyArrowPatch rather than LineCollection
  doc/release/release_dev.rst
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Defect, Enhancement

#4370 MNT: make the self-loop appear in all cases
  networkx/drawing/nx_pylab.py
Labels: Enhancement

#4372 Add additional libraries to intersphinx mapping
  doc/conf.py
  networkx/drawing/nx_pylab.py
Labels: Documentation, Maintenance

#4319 Make nx.pagerank a wrapper around different implementations, use scipy one by default
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
  networkx/conftest.py
Labels: Enhancement, Maintenance

#4373 MAINT: remove deprecated numpy type aliases.
  networkx/readwrite/tests/test_graphml.py
  networkx/tests/test_convert_numpy.py
Labels: Maintenance

#4385 Skip memory leak test for PyPy
  networkx/classes/tests/test_graph.py
Labels: Defect

#4383 add OSMnx usage example
  examples/geospatial/plot_osmnx.py
Labels: Documentation, Enhancement

#4384 Update docstring for to_pandas_edgelist and add edgekey parameter
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
  networkx/tests/test_convert_scipy.py
Labels: Enhancement

#4375 TST: Boost test coverage of nx_pylab module
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Maintenance

#4273 Fixed issue where edge attributes were being silently overwritten during node contraction
  networkx/algorithms/minors.py
  networkx/algorithms/tests/test_minors.py
Labels: Defect

#4388 CI: Fix CircleCI doc buiild failure
  .circleci/config.yml
  requirements/example-requirements.txt
Labels: Maintenance

#4306 Improve test coverage of convert module
  networkx/convert.py
  networkx/tests/test_convert.py
Labels: Maintenance

#4269 Add gene-gene network
  examples/algorithms/WormNet.v3.benchmark.txt
  examples/algorithms/plot_betweenness_centrality.py
Labels: Documentation, Enhancement

#4391 Ignore expected warnings
  networkx/conftest.py
Labels: Maintenance

#4390 Use matrix multiplication operator
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/centrality/flow_matrix.py
  networkx/algorithms/centrality/subgraph_alg.py
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/communicability_alg.py
  networkx/algorithms/node_classification/hmn.py
  networkx/algorithms/node_classification/lgc.py
  networkx/algorithms/node_classification/utils.py
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_threshold.py
  networkx/convert.py
  networkx/drawing/tests/test_layout.py
  networkx/generators/random_graphs.py
  networkx/generators/spectral_graph_forge.py
  networkx/linalg/algebraicconnectivity.py
  networkx/linalg/laplacianmatrix.py
  networkx/linalg/tests/test_algebraic_connectivity.py
  networkx/readwrite/tests/test_gexf.py
  networkx/utils/misc.py
Labels: Maintenance

#4392 code and doc fix for square_clustering algorithm in cluster.py
  networkx/algorithms/cluster.py
  networkx/algorithms/tests/test_cluster.py
Labels: Defect

#4393 Remove xml import checks
  networkx/algorithms/community/centrality.py
  networkx/algorithms/flow/capacityscaling.py
  networkx/algorithms/flow/networksimplex.py
  networkx/algorithms/minors.py
  networkx/algorithms/traversal/beamsearch.py
  networkx/classes/graph.py
  networkx/conftest.py
  networkx/readwrite/gexf.py
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_gexf.py
  networkx/readwrite/tests/test_graphml.py
  networkx/utils/misc.py
Labels: Maintenance

#4396 fix typo in NXEP template
  doc/developer/nxeps/nxep-template.rst
Labels: Documentation

#3886 Add Panther algorithm per #3849
  doc/reference/algorithms/similarity.rst
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
Labels: Enhancement

#4399 Pagerank followup
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
Labels: Documentation
