Repository networkx/networkx, pull requests merged in 2020-08, with the labels that each got.

#4123 Build pdf
  .circleci/config.yml
  tools/travis/build_docs.sh
  tools/travis/deploy_docs.sh
Labels: Maintenance

#4121 DOC: Suggestions and improvments from tutorial readthrough
  INSTALL.rst
  doc/reference/glossary.rst
  doc/tutorial.rst
Labels: Documentation

#4124 Enable 3.9-dev on travis
  .travis.yml
Labels: Maintenance

#4125 Fix parse_edgelist behavior with multiple attributes
  networkx/readwrite/edgelist.py
  networkx/readwrite/tests/test_edgelist.py
Labels: Defect

#4131 CI: hypothetical fix for CI latex installation issues
  .circleci/config.yml
Labels: Maintenance

#4132 Updated draw_networkx to accept numpy array for edgelist
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Defect

#4067 Add tree isomorphism
  doc/reference/algorithms/isomorphism.rst
  networkx/algorithms/isomorphism/__init__.py
  networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
  networkx/algorithms/isomorphism/tree_isomorphism.py
Labels: Enhancement

#4136 MAINT: Switch to abc-based isinstance checks in to_networkx_graph
  networkx/convert.py
Labels: Maintenance

#4145 Use dict instead of OrderedDict since dict is ordered by default from Python 3.6
  networkx/algorithms/simple_paths.py
Labels: Enhancement

#4128 MAINT: fixups to parse_edgelist.
  networkx/readwrite/edgelist.py
Labels: Maintenance

#4147 Update apt-get on circleci image
  .circleci/config.yml
Labels: Maintenance

#4154 new function rescale_layout_dict to rescale a dict-based layout
  doc/reference/drawing.rst
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#4066 relabel_nodes now preserves edges in multigraphs
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Defect

#4156 MAINT,TST: Improve coverage of nx_agraph module
  networkx/drawing/nx_agraph.py
  networkx/drawing/tests/test_agraph.py
Labels: Maintenance

#4160 Get steiner_tree to work with MultiGraphs by postprocessing
  networkx/algorithms/approximation/steinertree.py
  networkx/algorithms/approximation/tests/test_steinertree.py
Labels: Enhancement

#4004 junction_tree for #1012
  doc/credits.rst
  doc/reference/algorithms/tree.rst
  examples/algorithms/plot_decomposition.py
  networkx/algorithms/__init__.py
  networkx/algorithms/tree/__init__.py
  networkx/algorithms/tree/decomposition.py
  networkx/algorithms/tree/tests/test_decomposition.py
Labels: Enhancement

#4155 API: Add `show` kwarg to view_pygraphviz.
  doc/developer/deprecations.rst
  networkx/drawing/nx_agraph.py
  networkx/drawing/tests/test_agraph.py
Labels: Enhancement

#4162 Prepare for turning chordal_graph_cliques into a generator
  doc/developer/deprecations.rst
  networkx/algorithms/chordal.py
Labels: Enhancement

#4161 Docs update
  doc/developer/deprecations.rst
  doc/reference/algorithms/assortativity.rst
  doc/reference/algorithms/bipartite.rst
  doc/reference/algorithms/centrality.rst
  doc/reference/algorithms/chordal.rst
  doc/reference/algorithms/community.rst
  doc/reference/algorithms/dag.rst
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/simple_paths.rst
  doc/reference/algorithms/threshold.rst
  doc/reference/algorithms/traversal.rst
  doc/reference/algorithms/triads.rst
  doc/reference/classes/index.rst
  doc/reference/linalg.rst
  doc/release/report_functions_without_rst_generated.sh
  examples/advanced/plot_parallel_betweenness.py
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/bipartite/matching.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/betweenness_subset.py
  networkx/algorithms/centrality/trophic.py
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
  networkx/algorithms/cuts.py
Labels: Documentation

#4163 Remove unnecessary nx imports from doctests
  networkx/algorithms/bipartite/__init__.py
  networkx/algorithms/bipartite/matching.py
  networkx/algorithms/bipartite/redundancy.py
  networkx/algorithms/centrality/reaching.py
  networkx/algorithms/community/__init__.py
  networkx/algorithms/cycles.py
  networkx/algorithms/d_separation.py
  networkx/algorithms/distance_regular.py
  networkx/algorithms/flow/boykovkolmogorov.py
  networkx/algorithms/flow/capacityscaling.py
  networkx/algorithms/flow/dinitz_alg.py
  networkx/algorithms/flow/edmondskarp.py
  networkx/algorithms/flow/maxflow.py
  networkx/algorithms/flow/mincost.py
  networkx/algorithms/flow/networksimplex.py
  networkx/algorithms/flow/preflowpush.py
  networkx/algorithms/flow/shortestaugmentingpath.py
  networkx/algorithms/graph_hashing.py
  networkx/algorithms/isomorphism/ismags.py
  networkx/algorithms/link_prediction.py
  networkx/algorithms/minors.py
  networkx/algorithms/node_classification/__init__.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/algorithms/similarity.py
  networkx/algorithms/tournament.py
  networkx/algorithms/traversal/edgebfs.py
  networkx/algorithms/traversal/edgedfs.py
  networkx/algorithms/wiener.py
  networkx/classes/function.py
  networkx/classes/graphviews.py
  networkx/drawing/nx_pylab.py
  networkx/generators/classic.py
  networkx/generators/joint_degree_seq.py
  networkx/generators/line.py
  networkx/generators/social.py
  networkx/generators/spectral_graph_forge.py
  networkx/generators/sudoku.py
  networkx/linalg/bethehessianmatrix.py
  networkx/linalg/modularitymatrix.py
Labels: Maintenance

#3763 MultiGraph from graphml with explicit edge ids #3470
  networkx/classes/multigraph.py
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_graphml.py
Labels: Enhancement

#3347 Add edge label in GEXF writer as an optional attribute
  networkx/readwrite/gexf.py
  networkx/readwrite/tests/test_gexf.py
Labels: Enhancement

#4159 First Draft of Release Notes for v2.5
  doc/release/release_dev.rst
Labels: Documentation

#4166 Update deprecations in release notes
  doc/release/release_dev.rst
Labels: Documentation

#4167 DOC: Update docstrings for public functions in threshold module
  networkx/algorithms/threshold.py
Labels: Documentation

#4174 DOC,BLD: Fix doc build warning from markup error.
  networkx/readwrite/graphml.py
Labels: Documentation

#4176 fix issue #4173: cytoscape_graph(input_data) did modify the original data
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
Labels: Defect

#4182 Some docstring fixes for draw_networkx_edge_labels() in nx_pylab.py + one typo
  networkx/drawing/nx_pylab.py
Labels: Documentation, Enhancement
