Repository networkx/networkx, pull requests merged in 2020-05, with the labels that each got.

#3947 Update astar.py to fix docstring for the commit #3799
  networkx/algorithms/shortest_paths/astar.py
Labels: Documentation

#3952 Use keywords for positional arguments
  networkx/generators/community.py
Labels: Defect

#3959 fix documentation
  networkx/algorithms/structuralholes.py
  networkx/linalg/graphmatrix.py
Labels: Documentation

#3960 Add option for named key ids to GraphML writing.
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_graphml.py
Labels: Enhancement

#3783 Correct handling of zero-weight edges in all_shortest_paths
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: Enhancement

#3965 Fix Graph Documentation Typo
  networkx/classes/graph.py
Labels: Documentation

#3954 Fix: documentation of simrank_similarity_numpy
  networkx/algorithms/similarity.py
Labels: Documentation

#3935 Fix for #3930 (source & target columns not overwritten when converting to pd.DataFrame)
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: Defect, Enhancement

#3973 Fixes documentation issue #3811
  networkx/algorithms/communicability_alg.py
Labels: Documentation

#3961 Fix simrank_similarity with directed graph input
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
Labels: Defect

#3970 Correct VoteRank Algorithm to align with reference paper and avoid negative voting ability
  networkx/algorithms/centrality/voterank_alg.py
Labels: Defect

#3858 implemented faster sweep algorithm for kernighan_lin_bisection
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/tests/test_kernighan_lin.py
Labels: Enhancement
