Repository networkx/networkx, pull requests merged in 2020-10, with the labels that each got.

#4134 CI: Configure circleCI to deploy docs.
  .circleci/config.yml
  .travis.yml
Labels: Maintenance

#4193 MAINT: Refactor nx.info
  networkx/classes/function.py
  networkx/classes/tests/test_function.py
  networkx/convert_matrix.py
Labels: Enhancement

#4177 Fix indexing in kernighan_lin_bisection
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/tests/test_kernighan_lin.py
Labels: Defect

#4229 Add GH fingerprint
  .circleci/config.yml
Labels: Maintenance

#4218 NXEP: Add discussion to NXEP 2.
  doc/developer/nxeps/nxep-0002.rst
Labels: NXEP

#4237 MAINT,TST: Replace hash function for test of weighted astar #4236
  networkx/algorithms/shortest_paths/tests/test_weighted.py
Labels: Defect

#4238 MAINT: Deprecate numpy matrix conversion functions
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
Labels: Maintenance

#4234 Add roadmap
  doc/developer/nxeps/nxep-0002.rst
  doc/developer/roadmap.rst
Labels: Documentation

#4241 Add nx.info to str dunder for graph classes
  networkx/classes/function.py
  networkx/classes/graph.py
  networkx/classes/tests/historical_tests.py
  networkx/classes/tests/test_graph.py
Labels: Enhancement

#4245 DOC: Minor reformatting of contract_nodes docstring.
  networkx/algorithms/minors.py
Labels: Documentation

#4257 Fix betweenness_centrality doc paper links
  networkx/algorithms/centrality/betweenness.py
Labels: Documentation

#4246 Updated has_eulerian_path
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Enhancement

#4258 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Maintenance

#4260 Use seed to make plot fixed
  examples/basic/plot_read_write.py
Labels: Documentation, Enhancement

#4265 Replace degree_histogram and degree_rank with a single example
  examples/drawing/plot_degree.py
  examples/drawing/plot_degree_histogram.py
  examples/drawing/plot_degree_rank.py
Labels: Documentation, Enhancement

#4251 Update Knuth miles example.
  .circleci/config.yml
  .travis.yml
  examples/drawing/plot_knuth_miles.py
  requirements/README.md
  requirements/example.txt
Labels: Documentation, Enhancement

#4264 Update "four_grids" gallery example
  examples/drawing/plot_four_grids.py
Labels: Documentation, Enhancement

#4266 Improve legibility of labels in plot_labels_and_colors example
  examples/drawing/plot_labels_and_colors.py
Labels: Documentation, Enhancement

#4252 Improve readibility of chess_example in gallery
  examples/drawing/plot_chess_masters.py
Labels: Documentation, Enhancement

#4274 Fixed issue where edge contraction was unpacking edges incorrectly
  networkx/algorithms/minors.py
  networkx/algorithms/tests/test_minors.py
Labels: Defect

#4276 Add seeds to gallery examples for reproducibility
  examples/advanced/plot_eigenvalues.py
  examples/advanced/plot_heavy_metal_umlaut.py
  examples/algorithms/plot_beam_search.py
  examples/algorithms/plot_blockmodel.py
  examples/algorithms/plot_davis_club.py
  examples/algorithms/plot_krackhardt_centrality.py
  examples/basic/plot_properties.py
  examples/drawing/plot_directed.py
  examples/drawing/plot_edge_colormap.py
  examples/drawing/plot_ego_graph.py
  examples/drawing/plot_node_colormap.py
  examples/drawing/plot_random_geometric_graph.py
  examples/drawing/plot_sampson.py
  examples/drawing/plot_simple_path.py
  examples/drawing/plot_unix_email.py
  examples/drawing/plot_weighted_graph.py
  examples/graph/plot_degree_sequence.py
  examples/graph/plot_erdos_renyi.py
  examples/graph/plot_football.py
  examples/jit/plot_rgraph.py
  examples/subclass/plot_antigraph.py
  examples/subclass/plot_printgraph.py
Labels: Documentation, Maintenance

#4268 Add a 3D plotting example with matplotlib to the gallery
  examples/3d_drawing/plot_basic.py
Labels: Documentation, Enhancement

#4279 Deprecate `utils.is_iterator`
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/utils/misc.py
Labels: Maintenance

#4280 Deprecate utils.is_list_of_ints
  doc/developer/deprecations.rst
  doc/reference/utils.rst
  doc/release/release_dev.rst
  networkx/utils/misc.py
Labels: Maintenance

#4278 Improve axes layout in plot_decomposition example
  examples/algorithms/plot_decomposition.py
Labels: Documentation, Enhancement

#4285 Homepage
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
  README.rst
  doc/Makefile
  doc/README.md
  doc/_templates/dev_banner.html
  doc/_templates/eol_banner.html
  doc/_templates/layout.html
  doc/conf.py
  doc/developer/gitwash/this_project.inc
  doc/developer/nxeps/nxep-0000.rst
  doc/news.rst
  doc/release/release_2.0.rst
  doc/release/release_2.1.rst
  doc/release/release_2.2.rst
  doc/release/release_2.3.rst
  doc/release/release_2.4.rst
  doc/release/release_2.5.rst
  doc/release/release_dev.rst
  doc/release/release_template.rst
  examples/pygraphviz/plot_write_dotfile.py
  networkx/__init__.py
  networkx/drawing/nx_pylab.py
  networkx/release.py
Labels: Documentation, Maintenance

#4286 Build docs for deployment on Travis CI
  .travis.yml
  tools/travis/deploy_docs.sh
  tools/travis/linux_install.sh
Labels: Documentation, Maintenance

#4291 Add simple graph w/ manual layout
  examples/basic/plot_simple_graph.py
Labels: Documentation, Enhancement

#4281 Deprecate nx_yaml
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/readwrite/nx_yaml.py
Labels: Maintenance

#4282 Deprecate gpickle
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/readwrite/gpickle.py
Labels: Maintenance

#4299 Improve relabel coverage, tweak docstrings
  networkx/algorithms/dag.py
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Enhancement, Maintenance

#4301 TST: Increase test coverage of convert_matrix
  networkx/tests/test_convert_numpy.py
  networkx/tests/test_convert_pandas.py
  networkx/tests/test_convert_scipy.py
Labels: Maintenance

#4300 Add descriptive error message for Node/EdgeView slicing. NEXP2
  networkx/classes/reportviews.py
  networkx/classes/tests/test_reportviews.py
Labels: Documentation, Enhancement

#4289 Don't import other people's version.py
  networkx/release.py
Labels: Maintenance

#4307 TST: Refactor exception handling to improve coverage
  networkx/classes/graph.py
  networkx/classes/tests/test_graph.py
Labels: Maintenance
