Repository networkx/networkx, pull requests merged in 2020-06, with the labels that each got.

#3982 Update CONTRIBUTORS.rst
  CONTRIBUTORS.rst
Labels: Documentation

#3983 Deprecate context_manager reversed in favor of reversed_view
  doc/reference/utils.rst
  networkx/algorithms/components/strongly_connected.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/tests/test_dominance.py
  networkx/conftest.py
  networkx/utils/contextmanagers.py
Labels: Enhancement

#3987 Update CONTRIBUTORS.rst
  CONTRIBUTORS.rst
Labels: Documentation

#3972 Enhancement for voterank
  networkx/algorithms/centrality/tests/test_voterank.py
  networkx/algorithms/centrality/voterank_alg.py
Labels: Enhancement

#3974 add d-separation algorithm
  CONTRIBUTORS.rst
  doc/reference/algorithms/d_separation.rst
  doc/reference/algorithms/index.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/d_separation.py
  networkx/algorithms/tests/test_d_separation.py
Labels: Enhancement

#3999 DOC: added see also section to find_cycle
  networkx/algorithms/cycles.py
Labels: Documentation

#4010 improve docs for subgraph_view filter_edge
  networkx/classes/graphviews.py
Labels: Documentation

#4000 Fix exception causes in dag.py
  networkx/algorithms/dag.py
Labels: Maintenance

#4012 Fix exception causes and messages in 12 modules
  examples/subclass/plot_antigraph.py
  networkx/algorithms/approximation/kcomponents.py
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/bipartite/cluster.py
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/bipartite/matching.py
  networkx/algorithms/bipartite/matrix.py
  networkx/algorithms/bipartite/spectral.py
  networkx/algorithms/centrality/current_flow_betweenness.py
  networkx/algorithms/centrality/current_flow_betweenness_subset.py
  networkx/algorithms/centrality/katz.py
  networkx/algorithms/centrality/second_order.py
  networkx/drawing/tests/test_pylab.py
Labels: Maintenance

#4013 Remove usage of deprecated np.int
  networkx/readwrite/gexf.py
  networkx/readwrite/graphml.py
Labels: Maintenance

#4017 fix a typo
  networkx/algorithms/community/asyn_fluid.py
Labels: Documentation

#3925 Add algorithms for regular graphs
  doc/reference/algorithms/index.rst
  doc/reference/algorithms/regular.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/regular.py
  networkx/algorithms/tests/test_regular.py
Labels: Enhancement

#4025 Typo Hand should be Hans
  networkx/algorithms/approximation/treewidth.py
Labels: Documentation
