Repository networkx/networkx, pull requests merged in 2021-08, with the labels that each got.

#4965 modularity_max: provide labels to get_edge_data
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
Labels: Defect

#4996 Bugfix - use node labels with get_edge_data() at greedy_modularity_community()
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
Labels: Defect

#5008 fix typo
  networkx/__init__.py
  networkx/readwrite/__init__.py
  networkx/readwrite/nx_yaml.py
Labels: Documentation, Maintenance

#5010 Minor docstring cleanup to fix warning during sphinx build
  networkx/utils/decorators.py
Labels: Maintenance

#5011 update docs to match implementation of geographical threshold graph
  networkx/generators/geometric.py
Labels: Documentation

#5022 Style changes
  doc/conf.py
  examples/graph/plot_football.py
  examples/graph/plot_words.py
  examples/graphviz_layout/plot_giant_component.py
  networkx/algorithms/flow/networksimplex.py
  networkx/algorithms/flow/tests/test_networksimplex.py
  networkx/algorithms/link_analysis/tests/test_hits.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/similarity.py
  networkx/algorithms/summarization.py
  networkx/algorithms/tests/test_cluster.py
  networkx/algorithms/tests/test_dag.py
  networkx/algorithms/tests/test_similarity.py
  networkx/algorithms/tests/test_summarization.py
  networkx/classes/tests/test_function.py
  networkx/classes/tests/test_multigraph.py
  networkx/drawing/tests/test_pylab.py
  networkx/generators/tests/test_trees.py
  networkx/linalg/tests/test_laplacian.py
  networkx/readwrite/tests/test_edgelist.py
  networkx/tests/test_convert_numpy.py
  networkx/utils/misc.py
  networkx/utils/tests/test_misc.py
Labels: Maintenance

#5021 Fix automatic documenting of class methods via autosummary
  doc/_templates/autosummary/class.rst
  doc/reference/algorithms/isomorphism.ismags.rst
  networkx/utils/decorators.py
Labels: Documentation

#5029 Add unit tests and examples / doctests for nx.descendants_at_distance
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/tests/test_bfs.py
Labels: Enhancement

#5019 [GSoC contribution] Adding examples to docstrings in dag.py
  networkx/algorithms/dag.py
Labels: Documentation

#4950 modularity_max: breaking the loop when given community size is reached
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
Labels: Enhancement

#4929 Louvain Community Detection Algorithm
  doc/reference/algorithms/community.rst
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/louvain.py
  networkx/algorithms/community/tests/test_louvain.py
Labels: Enhancement

#4924 Fix disconnected graph bug in link prediction CCPA and add tests
  networkx/algorithms/link_prediction.py
  networkx/algorithms/tests/test_link_prediction.py
Labels: Defect

#5032 Store `G.adj` as a local variable to speed up `complement_edges(G)`
  networkx/algorithms/connectivity/edge_augmentation.py
Labels: Enhancement

#5040 Mark two atsp tests as slow
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
Labels: Maintenance

#5048 Fix bug in selfloop drawing in draw_networkx_edges
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Defect, Visualization
