Repository networkx/networkx, pull requests merged in 2021-12, with the labels that each got.

#5208 Investigate pre-release test failures
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Maintenance

#5214 Remove assertion test method in favor of assert statements
  networkx/tests/test_convert_scipy.py
Labels: Maintenance

#5210 Remove unused variable in mycielski.py
  networkx/generators/mycielski.py
Labels: Maintenance

#5217 used queue instead of ordinary list
  networkx/algorithms/centrality/betweenness.py
Labels: Enhancement

#5219 Add FutureWarning about matrix->array output to `google_matrix`
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/conftest.py
Labels: Maintenance

#5218 A few `np.matrix` cleanups
  networkx/convert.py
  networkx/tests/test_convert_scipy.py
Labels: Maintenance

#5196 Remove internal laplacian function in favor of laplacian_matrix.
  networkx/algorithms/centrality/current_flow_betweenness.py
  networkx/algorithms/centrality/current_flow_closeness.py
  networkx/algorithms/centrality/flow_matrix.py
Labels: Maintenance

#5165 [MRG] Create plot_subgraphs.py example
  examples/algorithms/plot_subgraphs.py
Labels: Documentation

#4874 Add a drawing example regarding the solution of traveling salesman problem
  examples/drawing/plot_tsp.py
Labels: Documentation

#5037 Fixed inconsistent documentation for nbunch parameter in DiGraph.edges()
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Documentation

#5226 Compatibility updates from testing with numpy/scipy/pytest rc's
  networkx/algorithms/link_analysis/tests/test_hits.py
  networkx/algorithms/tests/test_node_classification_deprecations.py
  networkx/drawing/layout.py
  networkx/linalg/tests/test_algebraic_connectivity.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
  networkx/readwrite/json_graph/tests/test_tree.py
Labels: Maintenance

#5224 Replace internal `close` fn with `math.isclose`.
  networkx/algorithms/isomorphism/matchhelpers.py
  networkx/algorithms/isomorphism/tests/test_vf2userfunc.py
Labels: Maintenance

#5225 Touchups and suggestions for subgraph gallery example
  examples/algorithms/plot_subgraphs.py
Labels: Documentation

#5234 Use new package name
  requirements/example.txt
Labels: Maintenance

#5182 Add an FAQ about assigning issues.
  doc/developer/new_contributor_faq.rst
Labels: Documentation

#5243 Update dev deps
  .pre-commit-config.yaml
  requirements/developer.txt
Labels: Maintenance

#5244 Update minor doc issues with tex notation
  networkx/algorithms/structuralholes.py
Labels: Maintenance
