Repository networkx/networkx, pull requests merged in 2021-04, with the labels that each got.

#4724 Fix typo in function docstring
  networkx/algorithms/components/strongly_connected.py
Labels: Documentation

#4735 Updating average_clustering() documentation - Issue #4734
  networkx/algorithms/approximation/clustering_coefficient.py
Labels: Documentation

#4738 rm nx import from docstring example.
  networkx/algorithms/approximation/clustering_coefficient.py
Labels: Maintenance

#4714 CI: persist pip cache between circleci runs
  .circleci/config.yml
Labels: Maintenance

#4741 Use pydata sphinx theme
  doc/_static/networkx_banner.svg
  doc/_templates/docs-navbar.html
  doc/_templates/layout.html
  doc/conf.py
  requirements/doc.txt
Labels: Documentation, Maintenance

#4727 O(n^2) -> O(n) implementation for scale_free_graph
  networkx/generators/directed.py
Labels: Enhancement

#4748 TST: be more explicit about instance comparison.
  networkx/algorithms/bipartite/tests/test_edgelist.py
  networkx/classes/tests/historical_tests.py
  networkx/readwrite/tests/test_adjlist.py
  networkx/readwrite/tests/test_edgelist.py
Labels: Maintenance

#4753 MAINT: Add missing __all__'s to utils modules + test.
  networkx/utils/misc.py
  networkx/utils/random_sequence.py
  networkx/utils/tests/test__init.py
Labels: Maintenance

#4758 Add 2 articles as references for TSP projects
  doc/developer/projects.rst
Labels: Documentation
