Repository networkx/networkx, pull requests merged in 2021-05, with the labels that each got.

#4768 Improve reproducibilty of geometric graphs
  networkx/generators/geometric.py
Labels: Defect

#4773 Updated decorator requirement for #4718
  requirements/default.txt
Labels: Maintenance

#4794 Update documentation dependencies
  doc/conf.py
  requirements/doc.txt
Labels: Maintenance

#4795 Fix sphinx warnings during doc build.
  doc/developer/new_contributor_faq.rst
  doc/developer/projects.rst
  doc/developer/release.rst
Labels: Documentation, Maintenance

#4800 Remove mayavi and cartopy dependencies
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
  doc/conf.py
  examples/3d_drawing/mayavi2_spring.py
  requirements/example-requirements.txt
  requirements/example.txt
Labels: Documentation, Maintenance

#4801 Improve documentation look
  doc/_static/custom.css
  doc/_templates/dev_banner.html
  doc/_templates/layout.html
  doc/_templates/version.html
  doc/conf.py
Labels: Documentation, Maintenance

#4607 Add approximation algorithms for traveling salesman problem
  doc/reference/algorithms/approximation.rst
  doc/reference/algorithms/matching.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/approximation/__init__.py
  networkx/algorithms/approximation/maxcut.py
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/matching.py
  networkx/algorithms/tests/test_matching.py
  networkx/classes/graph.py
  networkx/tests/test_all_random_functions.py
Labels: Enhancement

#4463 adds implementation of SNAP summarization algorithm
  doc/reference/algorithms/summarization.rst
  examples/algorithms/plot_snap.py
  networkx/algorithms/summarization.py
  networkx/algorithms/tests/test_summarization.py
Labels: Enhancement

#4814 Update black
  .pre-commit-config.yaml
  networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality.py
  networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality_subset.py
  networkx/algorithms/centrality/tests/test_current_flow_closeness.py
  networkx/algorithms/chordal.py
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/connectivity/tests/test_edge_augmentation.py
  networkx/algorithms/connectivity/tests/test_edge_kcomponents.py
  networkx/algorithms/isomorphism/vf2userfunc.py
  networkx/algorithms/tests/test_simple_paths.py
  networkx/classes/function.py
  networkx/classes/tests/test_graph.py
  networkx/generators/line.py
  networkx/generators/small.py
  networkx/generators/tests/test_interval_graph.py
  networkx/generators/tests/test_joint_degree_seq.py
  networkx/readwrite/gml.py
  networkx/readwrite/graphml.py
  networkx/utils/misc.py
  requirements/developer.txt
Labels: Maintenance

#4744 Restructure documentation
  LICENSE.txt
  doc/bibliography.rst
  doc/citing.rst
  doc/conf.py
  doc/developer/about_us.rst
  doc/developer/index.rst
  doc/developer/team.rst
  doc/index.rst
  doc/license.rst
  doc/release/api_0.99.rst
  doc/release/api_1.0.rst
  doc/release/api_1.10.rst
  doc/release/api_1.11.rst
  doc/release/api_1.4.rst
  doc/release/api_1.5.rst
  doc/release/api_1.6.rst
  doc/release/api_1.7.rst
  doc/release/api_1.8.rst
  doc/release/api_1.9.rst
  doc/release/index.rst
  doc/release/old_release_log.rst
  doc/release/release_2.0.rst
  doc/release/release_2.1.rst
  doc/release/release_2.2.rst
  doc/release/release_2.3.rst
  doc/release/release_2.4.rst
  doc/release/release_2.5.rst
  doc/release/release_dev.rst
  doc/release/release_template.rst
  networkx/algorithms/graphical.py
Labels: Documentation, Maintenance

#4815 Pin upper bound on decorator for 2.6 release.
  requirements/default.txt
Labels: Maintenance

#4678 Fixed Code Quality Issues
  networkx/drawing/nx_agraph.py
  networkx/linalg/attrmatrix.py
Labels: Maintenance

#4786 Remove dictionary from signature of tree_graph and tree_data
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
  networkx/readwrite/json_graph/tests/test_tree.py
  networkx/readwrite/json_graph/tree.py
Labels: Maintenance

#4685 restructured networksimplex.py and added test_networksimplex.py
  networkx/algorithms/flow/networksimplex.py
  networkx/algorithms/flow/tests/test_networksimplex.py
Labels: Enhancement, Maintenance

#4625 Update requirements
  requirements/example.txt
  requirements/release.txt
  requirements/test.txt
Labels: Maintenance

#4817 Fix Sphinx errors
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/graphical.py
  networkx/algorithms/summarization.py
Labels: Documentation, Maintenance

#4757 [Feature] Topological Generations
  doc/reference/algorithms/dag.rst
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: Enhancement

#4659 Add an `initial` parameter to simple and dual Barábasi-Albert random graphs
  doc/release/release_dev.rst
  networkx/generators/random_graphs.py
  networkx/generators/tests/test_random_graphs.py
Labels: Enhancement

#4818 Link to guides
  doc/conf.py
  doc/developer/index.rst
  doc/index.rst
  doc/release/index.rst
Labels: Documentation, Maintenance

#4820 switch alias direction of spring_layout and fruchterman_reingold_layout
  networkx/drawing/layout.py
Labels: Documentation

#4821 Fix to_undirected doc typo
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Documentation

#4826 Deprecate preserve_random_state
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/utils/decorators.py
Labels: Maintenance

#4497 Fixes read/write_gml with nan/inf attributes
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: Enhancement, Maintenance

#4802 Remove pyyaml dependency via module getattr
  doc/developer/deprecations.rst
  doc/reference/readwrite/index.rst
  doc/reference/readwrite/yaml.rst
  networkx/__init__.py
  networkx/readwrite/__init__.py
  networkx/readwrite/nx_yaml.py
  networkx/readwrite/tests/test_getattr_nxyaml_removal.py
  networkx/readwrite/tests/test_yaml.py
  requirements/extra.txt
Labels: Maintenance

#4827 Use pytest.approx
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/assortativity/tests/test_connectivity.py
  networkx/algorithms/assortativity/tests/test_neighbor_degree.py
  networkx/algorithms/bipartite/tests/test_centrality.py
  networkx/algorithms/bipartite/tests/test_spectral_bipartivity.py
  networkx/algorithms/centrality/tests/test_betweenness_centrality.py
  networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py
  networkx/algorithms/centrality/tests/test_closeness_centrality.py
  networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality.py
  networkx/algorithms/centrality/tests/test_current_flow_betweenness_centrality_subset.py
  networkx/algorithms/centrality/tests/test_current_flow_closeness.py
  networkx/algorithms/centrality/tests/test_degree_centrality.py
  networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
  networkx/algorithms/centrality/tests/test_harmonic_centrality.py
  networkx/algorithms/centrality/tests/test_katz_centrality.py
  networkx/algorithms/centrality/tests/test_load_centrality.py
  networkx/algorithms/centrality/tests/test_percolation_centrality.py
  networkx/algorithms/centrality/tests/test_reaching.py
  networkx/algorithms/centrality/tests/test_second_order_centrality.py
  networkx/algorithms/centrality/tests/test_subgraph.py
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/community/tests/test_quality.py
  networkx/algorithms/flow/tests/test_maxflow_large_graph.py
  networkx/algorithms/link_analysis/tests/test_hits.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/tests/test_boundary.py
  networkx/algorithms/tests/test_communicability.py
  networkx/algorithms/tests/test_link_prediction.py
  networkx/algorithms/tests/test_structuralholes.py
  networkx/algorithms/tests/test_threshold.py
  networkx/conftest.py
  networkx/drawing/tests/test_layout.py
  networkx/generators/tests/test_internet_as_graphs.py
  networkx/linalg/tests/test_algebraic_connectivity.py
  networkx/readwrite/tests/test_graphml.py
  networkx/testing/utils.py
Labels: Maintenance

#4831 DOC: Clarify behaviour of k_crust(G, k)
  networkx/algorithms/core.py
Labels: Documentation

#4830 Limit number of threads used by OMP in circleci.
  .circleci/config.yml
Labels: Maintenance

#4833 Deprecate run
  INSTALL.rst
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/testing/test.py
  networkx/tests/README
Labels: Maintenance

#4572 Fix a few broken links in the html docs
  doc/developer/nxeps/nxep-0002.rst
  networkx/algorithms/assortativity/connectivity.py
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/bipartite/centrality.py
  networkx/algorithms/bipartite/cluster.py
Labels: Documentation, Maintenance

#4829 Refactor testing utilities
  doc/developer/deprecations.rst
  doc/reference/utils.rst
  doc/release/release_dev.rst
  networkx/algorithms/approximation/tests/test_steinertree.py
  networkx/algorithms/bipartite/tests/test_edgelist.py
  networkx/algorithms/bipartite/tests/test_matrix.py
  networkx/algorithms/bipartite/tests/test_project.py
  networkx/algorithms/minors/tests/test_contraction.py
  networkx/algorithms/operators/tests/test_all.py
  networkx/algorithms/operators/tests/test_binary.py
  networkx/algorithms/operators/tests/test_product.py
  networkx/algorithms/tests/test_boundary.py
  networkx/algorithms/tests/test_core.py
  networkx/algorithms/tests/test_dag.py
  networkx/algorithms/tests/test_link_prediction.py
  networkx/algorithms/tests/test_matching.py
  networkx/algorithms/tree/tests/test_coding.py
  networkx/algorithms/tree/tests/test_mst.py
  networkx/algorithms/tree/tests/test_operations.py
  networkx/classes/tests/historical_tests.py
  networkx/classes/tests/test_digraph.py
  networkx/classes/tests/test_function.py
  networkx/classes/tests/test_graph.py
  networkx/classes/tests/test_graphviews.py
  networkx/classes/tests/test_multidigraph.py
  networkx/classes/tests/test_multigraph.py
  networkx/conftest.py
  networkx/drawing/tests/test_agraph.py
  networkx/drawing/tests/test_pydot.py
  networkx/generators/tests/test_atlas.py
  networkx/generators/tests/test_classic.py
  networkx/generators/tests/test_ego.py
  networkx/generators/tests/test_interval_graph.py
  networkx/generators/tests/test_lattice.py
  networkx/generators/tests/test_line.py
  networkx/generators/tests/test_nonisomorphic_trees.py
  networkx/generators/tests/test_spectral_graph_forge.py
  networkx/generators/tests/test_trees.py
  networkx/readwrite/tests/test_adjlist.py
  networkx/readwrite/tests/test_edgelist.py
  networkx/readwrite/tests/test_gpickle.py
  networkx/readwrite/tests/test_graph6.py
  networkx/readwrite/tests/test_graphml.py
  networkx/readwrite/tests/test_p2g.py
  networkx/readwrite/tests/test_pajek.py
  networkx/readwrite/tests/test_sparse6.py
  networkx/testing/utils.py
  networkx/tests/test_convert.py
  networkx/tests/test_convert_numpy.py
  networkx/tests/test_convert_pandas.py
  networkx/tests/test_convert_scipy.py
  networkx/tests/test_relabel.py
  networkx/utils/misc.py
Labels: Maintenance

#4825 Fix edge drawing performance regression
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Visualization

#4828 Draft 2.6 release notes
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
Labels: Documentation

#4839 Fix bad import pattern
  networkx/algorithms/chains.py
  networkx/algorithms/smetric.py
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/readwrite/text.py
  networkx/tests/test_import.py
Labels: Maintenance

#4582 Add info about testing and examples
  CONTRIBUTING.rst
  networkx/conftest.py
Labels: Documentation

#4843 Remove unused `normalized` parameter from communicability_betweenness_centrality
  doc/release/release_dev.rst
  networkx/algorithms/centrality/subgraph_alg.py
  networkx/algorithms/centrality/tests/test_subgraph.py
Labels: Defect

#4823 add special processing of `multigraph_input` upon graph init
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/classes/tests/test_graph.py
  networkx/classes/tests/test_multigraph.py
  networkx/convert.py
  networkx/tests/test_convert.py
Labels: Defect

#4850 Add dtype argument to adjacency_matrix
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/centrality/katz.py
  networkx/linalg/graphmatrix.py
  networkx/linalg/tests/test_graphmatrix.py
  networkx/tests/test_convert_numpy.py
Labels: Enhancement, Maintenance

#4847 Use scipy to compute eigenvalues
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/link_analysis/hits_alg.py
  networkx/algorithms/link_analysis/tests/test_hits.py
Labels: Documentation, Enhancement

#4841 Default to NumPy for simrank_similarity
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
Labels: Enhancement

#4840 Remove "networkx" from top-level networkx namespace
  networkx/__init__.py
  networkx/algorithms/__init__.py
  networkx/classes/__init__.py
  networkx/linalg/__init__.py
  networkx/tests/test_import.py
Labels: Maintenance
