Repository networkx/networkx, pull requests merged in 2021-11, with the labels that each got.

#5153 Bugfix for issue 5123
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#5174 Test scipy and pandas on py3.10
  requirements/default.txt
Labels: Maintenance

#5166 Deprecate `hmn` and `lgc` modules from the `node_classification` package
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/node_classification/__init__.py
  networkx/algorithms/node_classification/tests/__init__.py
  networkx/algorithms/node_classification/tests/test_local_and_global_consistency.py
  networkx/algorithms/tests/test_node_classification.py
  networkx/algorithms/tests/test_node_classification_deprecations.py
Labels: Maintenance

#5173 Rm passing ax.transOffset to LineCollection when drawing undirected edges
  networkx/drawing/nx_pylab.py
Labels: Maintenance, Visualization

#5089 Add a function to find the negative cycle using bellman_ford
  doc/reference/algorithms/shortest_paths.rst
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: Enhancement

#5177 Add a Q&A to the contributor FAQ about algorithm acceptance policy.
  doc/developer/new_contributor_faq.rst
Labels: Documentation

#5180 Revert "Add temporary pyparsing pin to fix CI."
  requirements/extra.txt
Labels: Maintenance

#5183 Only compute shortest path lengths when used
  networkx/algorithms/link_prediction.py
Labels: Enhancement

#5187 CI: xfail pydot tests.
  networkx/drawing/tests/test_pydot.py
Labels: Maintenance

#5190 Remove unused internal solver from algebraicconnectivity
  networkx/linalg/algebraicconnectivity.py
Labels: Maintenance

#5191 Remove check/comment for scipy 1.1 behavior.
  networkx/convert_matrix.py
Labels: Maintenance

#5185 Test on Python 3.10
  INSTALL.rst
  requirements/default.txt
  setup.py
Labels: Maintenance

#5188 Add regression test for ancestors & descedants with undirected graphs
  networkx/algorithms/tests/test_dag.py
Labels: Maintenance

#5197 Improve `resistance_distance` implementation with advanced indexing
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: Enhancement

#5194 Fix missing import and tests for directed Laplacian functions
  networkx/linalg/laplacianmatrix.py
  networkx/linalg/tests/test_laplacian.py
Labels: Defect
