Repository networkx/networkx, pull requests merged in 2021-02, with the labels that each got.

#4545 Deprecate generate_unique_node
  CONTRIBUTING.rst
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/dag.py
  networkx/conftest.py
  networkx/generators/tests/test_trees.py
  networkx/generators/trees.py
  networkx/utils/misc.py
Labels: Maintenance

#4589 Check nodelist input to floyd_warshall
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/shortest_paths/tests/test_dense_numpy.py
Labels: Defect

#4583 Pygraphviz choco
  .github/workflows/test.yml
  networkx/drawing/tests/test_agraph.py
  requirements/extra.txt
Labels: Maintenance

#4536 Improve community metrics complexity and memory (coverage and perfor…
  doc/reference/algorithms/community.rst
  networkx/algorithms/community/quality.py
  networkx/algorithms/community/tests/test_quality.py
Labels: Enhancement

#4600 Use Pillow for viewing AGraph output and deprecate default_opener
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/drawing/nx_agraph.py
  networkx/drawing/tests/test_agraph.py
  networkx/utils/misc.py
Labels: Maintenance

#4593 Remove mktemp usage
  networkx/drawing/tests/test_agraph.py
  networkx/drawing/tests/test_pydot.py
Labels: Maintenance

#4556 Add an FAQ to the developer guide for new contributors
  CONTRIBUTING.rst
  doc/conf.py
  doc/developer/index.rst
  doc/developer/new_contributor_faq.rst
Labels: Documentation

#4573 Collect label propagation communities in one go
  doc/release/release_dev.rst
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/tests/test_label_propagation.py
Labels: Enhancement

#4599 Deprecate networkx.utils.empty_generator.
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/simple_paths.py
  networkx/conftest.py
  networkx/utils/misc.py
Labels: Maintenance

#4622 return earlier from `clique.graph_clique_number`
  networkx/algorithms/clique.py
Labels: Maintenance

#4620 More for projects page: TSP and Graph Isomorphism
  doc/developer/projects.rst
Labels: Documentation

#4610 adding weight description to centrality metrices
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/betweenness_subset.py
  networkx/algorithms/centrality/current_flow_betweenness.py
  networkx/algorithms/centrality/current_flow_betweenness_subset.py
  networkx/algorithms/centrality/current_flow_closeness.py
  networkx/algorithms/centrality/eigenvector.py
  networkx/algorithms/centrality/group.py
  networkx/algorithms/centrality/katz.py
  networkx/algorithms/centrality/load.py
  networkx/algorithms/centrality/percolation.py
Labels: Documentation

#4628 Add scipy-1.6.1 to blocklist.
  requirements/default.txt
Labels: Maintenance

#4617 Deprecate hub_matrix and authority_matrix
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/link_analysis/hits_alg.py
  networkx/conftest.py
Labels: Maintenance

#3260 Fix issue #3153: generalized modularity maximization
  doc/reference/algorithms/community.rst
  doc/release/release_dev.rst
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/community/tests/test_modularity_max.py
  networkx/algorithms/community/tests/test_quality.py
Labels: Enhancement

#4639 Improve doc example for find_cycle.
  networkx/algorithms/cycles.py
Labels: Maintenance

#4635 Correct and update Atlas example
  doc/credits.rst
  examples/graphviz_layout/plot_atlas.py
Labels: Defect, Documentation

#4642 Remove attr_dict from parameters list in the docstring
  networkx/classes/multidigraph.py
Labels: Defect, Documentation
