Repository networkx/networkx, pull requests merged in 2022-12, with the labels that each got.

#6240 Add dfs_labeled_edges reporting of reverse edges due to depth_limit.
  networkx/algorithms/traversal/depth_first_search.py
  networkx/algorithms/traversal/tests/test_dfs.py
Labels: Defect

#6237 Warn users about duplicate nodes in generator function input
  networkx/generators/classic.py
Labels: Documentation

#6234 Allow MultiDiGraphs for LCA
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/tests/test_lowest_common_ancestors.py
Labels: LCA

#6268 doc: update documentation when providing an iterator over current graph to add/remove_edges_from.
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multigraph.py
Labels: Documentation
