Repository networkx/networkx, pull requests merged in 2022-05, with the labels that each got.

#5605 improve docstring for read_doc, see issue #5604
  networkx/drawing/nx_pydot.py
Labels: Documentation

#5558 Added documentation for branching_weight() solving issue #5553
  networkx/algorithms/tree/branchings.py
Labels: Documentation

#5559 Added examples in connected and strongly connected functions
  networkx/algorithms/components/connected.py
  networkx/algorithms/components/strongly_connected.py
Labels: Documentation

#5622 Update GH actions
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/lint.yml
  .github/workflows/mypy.yml
  .github/workflows/test.yml
Labels: Maintenance

#5624 Remove `_mat_spect_approx` in favor of simpler procedure
  networkx/generators/spectral_graph_forge.py
Labels: Maintenance

#5623 Replace np.flip with indexing in layouts.
  networkx/drawing/layout.py
Labels: Maintenance

#5614 Cache edges, degree, adj properties of Graph classes
  networkx/algorithms/approximation/kcomponents.py
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/classes/reportviews.py
  networkx/classes/tests/test_digraph.py
  networkx/classes/tests/test_graph.py
  networkx/classes/tests/test_multidigraph.py
Labels: Enhancement

#5616 Disallow isolated nodes for Eulerian Path
  doc/release/release_dev.rst
  networkx/algorithms/euler.py
  networkx/algorithms/tests/test_euler.py
Labels: Defect

#5575 Fix triadic census
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
Labels: Defect

#5599 Adjust the usage of nodes_or_number decorator
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/bipartite/tests/test_generators.py
  networkx/generators/classic.py
  networkx/generators/geometric.py
  networkx/generators/tests/test_classic.py
  networkx/generators/tests/test_lattice.py
  networkx/utils/decorators.py
Labels: Enhancement

#5630 Use new ubuntu LTS release
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/test.yml
Labels: Maintenance

#5632 Build docs with Py 3.9
  .github/workflows/deploy-docs.yml
Labels: Maintenance

#5633 added example on moral graph
  networkx/algorithms/moral.py
Labels: Documentation

#5593 Added examples in weakly_connected.py
  networkx/algorithms/components/weakly_connected.py
Labels: Documentation

#5638 Rm unnecessary input validation from moral_graph.
  networkx/algorithms/moral.py
Labels: Maintenance

#5635 DOC: fix up links, remove references to directed graphs, add proper cites
  networkx/linalg/laplacianmatrix.py
Labels: Documentation

#5625 Added example under unary operators
  networkx/algorithms/operators/unary.py
Labels: Documentation

#5617 Added examples on matching
  networkx/algorithms/matching.py
Labels: Documentation

#5647 doc: fix typos in docstring and comment
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/connectivity/tests/test_edge_kcomponents.py
Labels: Documentation

#5648 DOC: remove a comment
  networkx/algorithms/shortest_paths/weighted.py
Labels: Documentation

#5652 Fix typo
  networkx/algorithms/dag.py
Labels: Documentation

#5657 Fix __setstate__ for OutEdgeView subclasses, read _adjdict from state
  networkx/classes/reportviews.py
  networkx/classes/tests/test_reportviews.py
Labels: Defect

#5660 Extract valid kwds from the function signature for draw_networkx_*
  networkx/drawing/nx_pylab.py
Labels: Defect

#5667 Error out when pydot fails to correctly parse node names
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
Labels: Maintenance
