Repository networkx/networkx, pull requests merged in 2022-11, with the labels that each got.

#6126 Added an example in all_pairs_node_connectivity
  networkx/algorithms/approximation/connectivity.py
  networkx/algorithms/connectivity/kcutsets.py
Labels: Documentation

#6165 Update pytest
  networkx/algorithms/bipartite/tests/test_matching.py
  networkx/algorithms/community/tests/test_kclique.py
  networkx/algorithms/flow/tests/test_maxflow.py
  networkx/algorithms/isomorphism/tests/test_match_helpers.py
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/tests/test_structuralholes.py
  networkx/algorithms/tree/tests/test_mst.py
  networkx/classes/tests/test_coreviews.py
  networkx/classes/tests/test_graphviews.py
  networkx/utils/tests/test_mapped_queue.py
  requirements/test.txt
Labels: Maintenance

#6000 plugin based backend infrastructure to use multiple computation backends
  doc/reference/classes/index.rst
  networkx/__init__.py
  networkx/algorithms/bipartite/basic.py
  networkx/algorithms/boundary.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/degree_alg.py
  networkx/algorithms/centrality/eigenvector.py
  networkx/algorithms/centrality/katz.py
  networkx/algorithms/cluster.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/components/connected.py
  networkx/algorithms/components/strongly_connected.py
  networkx/algorithms/components/weakly_connected.py
  networkx/algorithms/core.py
  networkx/algorithms/cuts.py
  networkx/algorithms/dag.py
  networkx/algorithms/dominating.py
  networkx/algorithms/isolate.py
  networkx/algorithms/link_analysis/hits_alg.py
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/algorithms/link_prediction.py
  networkx/algorithms/reciprocity.py
  networkx/algorithms/regular.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/simple_paths.py
  networkx/algorithms/smetric.py
  networkx/algorithms/structuralholes.py
  networkx/algorithms/tournament.py
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/triads.py
  networkx/classes/__init__.py
  networkx/classes/backends.py
  networkx/conftest.py
  networkx/generators/ego.py
Labels: Enhancement

#6160 Add ThinGraph example to Multi*Graph doc_strings
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Documentation

#6219 Minor Python 2 cleanup
  networkx/algorithms/bipartite/redundancy.py
Labels: Maintenance

#6168 Add example laplacian matrix
  networkx/linalg/laplacianmatrix.py
Labels: outreachy-review

#6222 Revert 6219 and delete comment.
  networkx/algorithms/bipartite/redundancy.py
Labels: Maintenance

#6223 Rm incorrect test case for connected edge swap
  networkx/algorithms/tests/test_swap.py
Labels: Defect

#5945 Hide edges with a weight of None in A*.
  networkx/algorithms/shortest_paths/astar.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: Enhancement
