Repository networkx/networkx, pull requests merged in 2022-02, with the labels that each got.

#5289 Adjust functions appearing in variables `__all__` but not in docs
  doc/reference/algorithms/clique.rst
  doc/reference/algorithms/cycles.rst
  doc/reference/algorithms/triads.rst
  networkx/algorithms/bipartite/projection.py
  networkx/algorithms/bipartite/tests/test_generators.py
  networkx/algorithms/clique.py
  networkx/algorithms/coloring/greedy_coloring.py
  networkx/algorithms/coloring/greedy_coloring_with_interchange.py
  networkx/algorithms/core.py
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_clique.py
  networkx/algorithms/tests/test_core.py
  networkx/conftest.py
Labels: Documentation

#5296 Update to stable version of black
  requirements/developer.txt
Labels: Maintenance

#5300 Add FutureWarning to `attr_matrix` to notify users of return type change
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/linalg/attrmatrix.py
Labels: Maintenance

#5304 Update test requirements
  requirements/test.txt
Labels: Maintenance

#5276 Update scipy
  requirements/default.txt
Labels: Maintenance

#5314 Update pygraphviz
  requirements/extra.txt
Labels: Maintenance

#5315 Document default dtype in to_numpy_recarray docstring.
  networkx/convert_matrix.py
Labels: Documentation

#5317 Remove unused import
  networkx/algorithms/d_separation.py
Labels: Maintenance

#5283 Deprecate `make_small_graph` and `make_small_undirected_graph`
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/generators/small.py
Labels: Maintenance

#5264 Update `draw_<layout>` docstrings with usage examples
  networkx/drawing/nx_pylab.py
Labels: Documentation

#5319 More numpy.matrix cleanups for NX2.7
  examples/algorithms/plot_rcm.py
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/similarity.py
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/convert.py
  networkx/linalg/laplacianmatrix.py
Labels: Maintenance

#5316 Add informative exception for drawing multiedge labels.
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Maintenance

#5049 Potential resolution to full paths to functions in docs
  doc/_templates/autosummary/base.rst
  doc/developer/nxeps/nxep-0002.rst
Labels: Documentation

#4579 Use pytest-mpl
  .circleci/config.yml
  .github/workflows/circleci.yml
  CONTRIBUTING.rst
  MANIFEST.in
  networkx/drawing/tests/baseline/test_house_with_colors.png
  networkx/drawing/tests/test_pylab.py
  requirements/test.txt
  setup.py
Labels: Enhancement, Maintenance

#5216 Keep omega within [-1, 1] bounds
  doc/release/release_dev.rst
  networkx/algorithms/smallworld.py
  networkx/algorithms/tests/test_smallworld.py
Labels: Enhancement

#5172 Add support for finding maximal cliques containing a set of nodes
  networkx/algorithms/clique.py
  networkx/algorithms/tests/test_clique.py
Labels: Enhancement

#5337 sampling from dict_keys objects is deprecated.
  networkx/generators/degree_seq.py
Labels: Maintenance

#5336 Add support for `numpy.random.Generator`
  networkx/utils/misc.py
  networkx/utils/tests/test_misc.py
Labels: Enhancement

#4897 Update matching functions for error validation and speed
  doc/release/release_dev.rst
  networkx/algorithms/matching.py
  networkx/algorithms/tests/test_matching.py
Labels: Enhancement, Maintenance

#5324 Add structured dtypes to `to_numpy_array`
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
Labels: Enhancement

#5330 Deprecate `to_numpy_recarray`
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
Labels: Maintenance

#5342 First pass at 2.7 release notes.
  doc/release/release_dev.rst
Labels: Documentation

#5345 Add pickle and yaml migration info
  doc/release/migration_guide_from_2.x_to_3.0.rst
Labels: Documentation

#5341 Deprecate info
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/classes/function.py
  networkx/conftest.py
Labels: Maintenance, Documentation

#5346 Fix pandas warning
  networkx/tests/test_convert_pandas.py
  requirements/default.txt
Labels: Maintenance

#5339 Test on 3.11-dev
  .github/workflows/test.yml
  requirements/test.txt
Labels: Maintenance

#5348 Update release process
  doc/developer/release.rst
  requirements/release.txt
Labels: Documentation

#5349 Update mentored project info with the expected time commitment
  doc/developer/projects.rst
Labels: Documentation

#5356 Update `convert_matrix` module docstring
  networkx/convert_matrix.py
Labels: Documentation

#5361 Remove stuff conda doesn't support
  .circleci/config.yml
  requirements/developer.txt
  requirements/doc.txt
  requirements/test.txt
Labels: Maintenance

#5354 Fixes equidistant parameter for spiral layout whenever passed as True explicitly
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#5364 Fix docs
  doc/reference/convert.rst
  doc/release/release_dev.rst
Labels: Maintenance, Documentation
