Repository networkx/networkx, pull requests merged in 2022-04, with the labels that each got.

#5444 Don't use graph6 with directed graphs (#5443)
  networkx/readwrite/graph6.py
  networkx/readwrite/tests/test_graph6.py
Labels: Maintenance

#5394 Fix min_weight_matching to convert edge weights without reciprocal
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/matching.py
  networkx/algorithms/tests/test_matching.py
Labels: Defect

#5454 Make sympy extra dep
  requirements/default.txt
  requirements/extra.txt
Labels: Maintenance

#5455 Optimize prim for mst
  networkx/algorithms/tree/mst.py
Labels: Enhancement

#5457 MAINT: Prim MST test didn't pass algorithm name to all unit tests
  networkx/algorithms/tree/tests/test_mst.py
Labels: Defect

#5456 Fixed wrong dict factory usage on MultiDiGraph
  networkx/classes/multidigraph.py
  networkx/classes/tests/test_graph.py
  networkx/classes/tests/test_multidigraph.py
  networkx/classes/tests/test_multigraph.py
Labels: Defect

#5407 added extra condition for fancy arrow colors
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Visualization

#5468 Update dependencies
  .pre-commit-config.yaml
  requirements/developer.txt
  requirements/doc.txt
  requirements/release.txt
  requirements/test.txt
Labels: Maintenance

#5476 DOCS: add some guidelines for references
  CONTRIBUTING.rst
Labels: Documentation

#5503 Rm incorrect reference from spiral_layout docstring.
  networkx/drawing/layout.py
Labels: Documentation

#5505 Add notes about NumPy/SciPy integration to NX 2->3 migration guide
  doc/release/migration_guide_from_2.x_to_3.0.rst
Labels: Documentation

#5513 Run black on docs
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.rst
  doc/developer/nxeps/nxep-0003.rst
  requirements/developer.txt
Labels: Documentation

#5524 Added examples in is_forest() and is_tree()
  networkx/algorithms/tree/recognition.py
Labels: Documentation

#5516 a hack to force self edges to be ignored on the first node inspected
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
Labels: Defect

#5548 PlanarEmbedding in autosummary instead of autoclass.
  doc/reference/algorithms/planarity.rst
Labels: Maintenance, Documentation

#5556 Fix doc build error in planarity
  networkx/algorithms/planarity.py
Labels: Maintenance

#5549 Fix min_edge_cover in special cases (#5538) and correct documentation
  networkx/algorithms/covering.py
  networkx/algorithms/tests/test_covering.py
Labels: Defect

#5544 Add is_planar function. Solves issue #5109
  doc/reference/algorithms/planarity.rst
  networkx/algorithms/planarity.py
Labels: Enhancement

#5519 Improve bridges documentation
  networkx/algorithms/bridges.py
Labels: Documentation

#5550 fix greedy_modularity when multiple components exist.
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
Labels: Defect

#5583 Add examples to compose operation
  networkx/algorithms/operators/binary.py
Labels: Documentation

#5589 Fix for MyPy 0.95
  networkx/algorithms/flow/tests/test_maxflow.py
Labels: Maintenance

#5529 Update MultiGraph.degree() docs: outdated return type
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Documentation

#5580 Update numpydoc
  requirements/doc.txt
Labels: Maintenance
