Repository networkx/networkx, pull requests merged in 2022-03, with the labels that each got.

#5370 Fix development banner
  doc/_templates/layout.html
  doc/developer/release.rst
Labels: Maintenance, Documentation

#5371 Simplify DelayedImportErrorModule
  networkx/lazy_imports.py
Labels: Maintenance

#5372 [nx_pylab] fix StopIteration, if empty dict is passed for labels.
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Defect

#5380 Add Generator support to create_py_random_state.
  networkx/utils/misc.py
  networkx/utils/tests/test_misc.py
Labels: Enhancement

#5359 NXEP 4: Updating the default numpy random number generator in NetworkX
  doc/developer/nxeps/nxep-0004.rst
Labels: Documentation

#5387 Updated MultiDiGraph documentation to include more examples of actually
  networkx/classes/multidigraph.py
Labels: Documentation

#5390 Updates to greedy_modularity_communities docs
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/community/modularity_max.py
Labels: Documentation

#5391 Finish up NXEP 4 first draft
  doc/developer/nxeps/nxep-0004.rst
Labels: Documentation

#5398 Correct typo in docstring (int -> float)
  networkx/classes/function.py
Labels: Documentation

#5424 Update sparse6 urls to use https
  networkx/readwrite/sparse6.py
Labels: Documentation

#5422 Deprecate extrema bounding
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: Maintenance

#5420 Add NXEP4 to developer toctree and fix broken links
  doc/developer/nxeps/index.rst
  doc/developer/nxeps/nxep-0004.rst
Labels: Documentation, NXEP

#5414 Minor improvements from general code readthrough
  networkx/algorithms/approximation/connectivity.py
  networkx/algorithms/approximation/kcomponents.py
  networkx/algorithms/asteroidal.py
  networkx/algorithms/chordal.py
  networkx/readwrite/nx_shp.py
  networkx/utils/contextmanagers.py
Labels: Maintenance

#5405 Ignore formatting changes with black, pep8 for git blame
  .git-blame-ignore-revs
Labels: Maintenance

#5427 Deprecate dict to numpy helpers
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/utils/misc.py
  networkx/utils/tests/test_misc.py
Labels: Maintenance

#5430 Deprecate `to_tuple`
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/readwrite/json_graph/node_link.py
  networkx/utils/misc.py
Labels: Maintenance

#5404 Fix average_neighbor_degree calculations for directed graph
  doc/release/release_dev.rst
  networkx/algorithms/assortativity/neighbor_degree.py
  networkx/algorithms/assortativity/tests/test_neighbor_degree.py
Labels: Defect

#5431 Parametrize tutte polynomial tests
  networkx/algorithms/tests/test_polynomials.py
Labels: Maintenance

#5440 Ignore black formatting
  .git-blame-ignore-revs
Labels: Maintenance

#5439 Update sphinx
  requirements/doc.txt
Labels: Maintenance

#5441 Use https links for conference.scipy.org
  doc/index.rst
Labels: Maintenance
