Repository networkx/networkx, pull requests merged in 2022-10, with the labels that each got.

#6014 Fix warnings from running tests in randomized order
  networkx/drawing/tests/test_pylab.py
  networkx/generators/tests/test_expanders.py
Labels: Maintenance

#6019 update secutiry link to tidelift
  README.rst
Labels: Documentation

#6022 Update numpydoc
  requirements/doc.txt
Labels: Maintenance

#6023 Support Python 3.11
  .github/workflows/test.yml
  setup.py
Labels: Maintenance

#6024 Update linters
  .pre-commit-config.yaml
  requirements/developer.txt
Labels: Maintenance

#6027 Minor updates to expanders generator tests
  networkx/generators/tests/test_expanders.py
Labels: Maintenance

#6031 Update deprecations
  doc/developer/deprecations.rst
  networkx/conftest.py
Labels: Maintenance

#6037 Use scipy.sparse array datastructure
  networkx/algorithms/bipartite/matrix.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/betweenness_subset.py
  networkx/algorithms/chordal.py
  networkx/algorithms/tournament.py
  networkx/classes/coreviews.py
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
  networkx/conftest.py
  networkx/convert.py
  networkx/convert_matrix.py
  networkx/linalg/attrmatrix.py
  networkx/linalg/bethehessianmatrix.py
  networkx/linalg/graphmatrix.py
  networkx/linalg/laplacianmatrix.py
  networkx/linalg/modularitymatrix.py
Labels: Maintenance

#6039 Add missing asserts to tests
  networkx/readwrite/json_graph/tests/test_adjacency.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
  networkx/readwrite/json_graph/tests/test_node_link.py
  networkx/readwrite/json_graph/tests/test_tree.py
  networkx/tests/test_relabel.py
Labels: Maintenance

#6093 Update GML parsing/writing to allow empty lists/tuples as node attributes
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: Enhancement

#6106 Replace .A call with .toarray for sparse array in example.
  examples/drawing/plot_eigenvalues.py
Labels: Documentation

#6104 Tested boykov_kolmogorov and dinitz with cutoff
  networkx/algorithms/flow/tests/test_maxflow.py
Labels: Maintenance

#6098 Warn on unused visualization kwargs that only apply to FancyArrowPatch edges
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: Enhancement, Visualization

#5988 Fix weighted MultiDiGraphs in DAG longest path algorithms + add additional tests
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: Defect

#6114 Circular center node layout
  examples/drawing/plot_center_node.py
Labels: Visualization

#6146 Remove deprecated maxcardinality parameter from min_weight_matching
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/matching.py
  networkx/algorithms/tests/test_matching.py
Labels: Maintenance

#6139 Remove deprecated `find_cores`
  doc/release/report_functions_without_rst_generated.py
  networkx/algorithms/core.py
Labels: Maintenance

#6147 Remove deprecated project function from bipartite package.
  networkx/algorithms/__init__.py
  networkx/algorithms/bipartite/projection.py
Labels: Maintenance

#6159 Test on Python 3.11
  .github/workflows/test.yml
Labels: Maintenance
