Repository networkx/networkx, pull requests merged in 2022-06, with the labels that each got.

#5682 Remove unused logic in nonisomorphic_trees
  networkx/generators/nonisomorphic_trees.py
Labels: Enhancement

#5668 equitable_coloring: Get lazily first item instead of creating whole list
  networkx/algorithms/coloring/equitable_coloring.py
Labels: Enhancement

#5690 Update release requirements
  requirements/release.txt
Labels: Maintenance

#5689 Update developer requirements
  .pre-commit-config.yaml
  doc/release/contribs.py
  requirements/developer.txt
Labels: Maintenance

#5567 Clean up maximal_independent_set tests
  networkx/algorithms/tests/test_mis.py
Labels: Maintenance

#5693 importorskip scipy instead of numpy for total spanning tree
  networkx/algorithms/tree/tests/test_mst.py
Labels: Maintenance

#5701 Use inline math
  networkx/generators/community.py
Labels: Documentation

#5709 Update simple_cycles docstring w/ yields and examples
  networkx/algorithms/cycles.py
Labels: Documentation

#5710 Catch ':' explicitly while working with pydot
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
Labels: Defect

#5717 Revert "Add workaround for pytest failures on 3.11b2"
  .github/workflows/test.yml
Labels: Maintenance

#5715 Default to lightmode for documentation
  doc/conf.py
  networkx/algorithms/distance_measures.py
Labels: Documentation

#5718 Add durations flag to coverage run on CI.
  .github/workflows/coverage.yml
Labels: Maintenance

#5705 Recover order of layers in multipartite_layout when layers are sortable
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#5711 Update doc requirements
  requirements/doc.txt
Labels: Maintenance, Documentation

#5708 Touchups to MG and MDG edges docstrings.
  networkx/classes/multidigraph.py
  networkx/classes/multigraph.py
Labels: Documentation

#5721 Add PendingDeprecation for pydot
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/drawing/nx_pydot.py
Labels: Maintenance

#5728 Add example of topo_order kwarg to dag_longest_path
  networkx/algorithms/dag.py
Labels: Documentation

#4553 CI: add pytest-randomly workflow.
  .github/workflows/pytest-randomly.yml
Labels: Maintenance

#5737 Rm `to_numpy_recarray`
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
Labels: Maintenance

#5768 Remove deprecated decorator preserve_random_state
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/utils/decorators.py
  networkx/utils/tests/test_decorators.py
Labels: Maintenance

#5770 Remove decorator random_state
  doc/developer/deprecations.rst
  networkx/utils/decorators.py
  networkx/utils/tests/test_decorators.py
Labels: Maintenance

#5781 Change PyDot PendingDeprecation to Deprecation
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/drawing/nx_pydot.py
Labels: Maintenance

#5784 update cytoscape functions to drop old signature
  networkx/conftest.py
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/json_graph/tests/test_cytoscape.py
Labels: Maintenance

#5774 Replace node_classification subpackage with a module
  doc/developer/deprecations.rst
  doc/reference/algorithms/node_classification.rst
  networkx/algorithms/node_classification.py
  networkx/algorithms/node_classification/__init__.py
  networkx/algorithms/node_classification/hmn.py
  networkx/algorithms/node_classification/lgc.py
  networkx/algorithms/node_classification/utils.py
  networkx/algorithms/tests/test_node_classification_deprecations.py
  networkx/conftest.py
  setup.py
Labels: Maintenance

#5795 Compute `is_weakly_connected` lazily
  networkx/algorithms/components/weakly_connected.py
Labels: Enhancement

#5793 Compute `is_strongly_connected` lazily
  networkx/algorithms/components/strongly_connected.py
Labels: Enhancement

#5800 Fix typo in bipartite closeness_centrality and thought-o in tests
  networkx/algorithms/bipartite/centrality.py
  networkx/algorithms/bipartite/tests/test_centrality.py
Labels: Defect

#5809 Pydot layout fix
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
Labels: Defect

#5707 Check that nodes have "pos" attribute in geometric_edges
  networkx/generators/geometric.py
  networkx/generators/tests/test_geometric.py
Labels: Enhancement

#5663 Implement directed edge swap
  doc/reference/algorithms/swap.rst
  doc/release/release_dev.rst
  networkx/algorithms/swap.py
  networkx/algorithms/tests/test_swap.py
Labels: Enhancement

#5816 Temporary fix for failing tests w/ scipy1.9.
  networkx/algorithms/approximation/traveling_salesman.py
Labels: Maintenance

#5822 Fix #5817
  networkx/algorithms/approximation/traveling_salesman.py
Labels: Maintenance

#5258 Update relabel.py to preserve node order
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Enhancement

#5819 Update distance parameter description.
  networkx/algorithms/centrality/closeness.py
Labels: Documentation

#5835 Modify DAG example to show topological layout.
  examples/graph/plot_DAG_layouts.py
  examples/graph/plot_dag_layout.py
Labels: Documentation

#5802 Add keyword argument to `nx.ancestors` & `nx.descendants`
  networkx/algorithms/dag.py
Labels: Enhancement
