Repository networkx/networkx, pull requests merged in 2022-08, with the labels that each got.

#5903 Allow classes to relabel nodes -- casting
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Enhancement

#5914 Update lattice.py
  networkx/generators/lattice.py
Labels: Documentation

#5919 Add to about_us.rst
  doc/developer/about_us.rst
Labels: Documentation

#5923 Update precommit hooks
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/pytest-randomly.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  doc/README.md
  doc/_templates/dev_banner.html
  doc/_templates/eol_banner.html
  doc/_templates/layout.html
  doc/_templates/version.html
  examples/external/force/force.html
  requirements/developer.txt
Labels: Maintenance

#5924 Remove old Appveyor cruft
  networkx/conftest.py
  networkx/readwrite/graph6.py
  networkx/readwrite/sparse6.py
Labels: Maintenance

#5921 Allow unsortable nodes in approximation.treewidth functions
  networkx/algorithms/approximation/tests/test_treewidth.py
  networkx/algorithms/approximation/treewidth.py
Labels: Defect

#5902 Fix Louvain_partitions by yielding a copy of the sets in the partition gh-5901
  networkx/algorithms/community/louvain.py
  networkx/algorithms/community/tests/test_louvain.py
Labels: Defect

#5883 Replace LCA with naive implementations
  doc/reference/algorithms/lowest_common_ancestors.rst
  doc/release/release_dev.rst
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/tests/test_lowest_common_ancestors.py
Labels: Maintenance

#5932 Add function bfs_layers to docs
  doc/reference/algorithms/traversal.rst
  networkx/algorithms/euler.py
  networkx/algorithms/traversal/breadth_first_search.py
Labels: Documentation

#5933 Bump nodelink args deprecation expiration to v3.2
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/json_graph/node_link.py
Labels: Maintenance

#5912 Update mapping logic in `relabel_nodes`
  doc/release/release_dev.rst
  networkx/relabel.py
  networkx/tests/test_relabel.py
Labels: Maintenance

#5928 Propose to make new node_link arguments keyword only.
  networkx/readwrite/json_graph/node_link.py
Labels: Enhancement

#5910 Arf layout
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: Enhancement

#5629 Add Mehlhorn Steiner approximations
  networkx/algorithms/approximation/steinertree.py
  networkx/algorithms/approximation/tests/test_steinertree.py
Labels: Enhancement

#5474 Updated networkx/classes/function.py . Solves Issue #5463
  networkx/classes/function.py
Labels: Documentation
