Repository networkx/networkx, pull requests merged in 2022-01, with the labels that each got.

#5247 Minor changes to speed up asynchronous label propagation for community detection.
  networkx/algorithms/community/label_propagation.py
Labels: Enhancement

#5240 Docstrings for the small.py module
  networkx/generators/small.py
Labels: Documentation

#5272 Update sphinx
  requirements/doc.txt
Labels: Maintenance

#5273 Update year
  LICENSE.txt
  README.rst
Labels: Maintenance

#5263 Update minimum dependencies (pygraphviz, lxml, pydot)
  requirements/extra.txt
Labels: Maintenance

#5275 Update gexf website link in documentation
  networkx/readwrite/gexf.py
Labels: Maintenance, Documentation

#5274 Update numpydoc
  doc/release/migration_guide_from_2.x_to_3.0.rst
  doc/release/release_2.6.rst
  doc/tutorial.rst
  networkx/algorithms/approximation/traveling_salesman.py
  requirements/doc.txt
Labels: Maintenance

#4909 Initial setup of lazy_import functions.
  networkx/__init__.py
  networkx/lazy_imports.py
  networkx/tests/test_lazy_imports.py
  networkx/utils/misc.py
Labels: Maintenance

#5262 Deprecate scipy sparse matrix conversion functions
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/conftest.py
  networkx/convert_matrix.py
  networkx/tests/test_convert_scipy.py
Labels: Maintenance

#5086 Fix lowest_common_ancestors (issue #4942)
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/tests/test_lowest_common_ancestors.py
Labels: Defect

#5282 Make small graph generator node test more specific.
  networkx/generators/tests/test_small.py
Labels: Maintenance

#5267 Use from_dict_of_lists instead of make_small_graph in generators.small
  networkx/generators/small.py
  networkx/generators/tests/test_small.py
Labels: Maintenance

#5284 Fix: Update louvain_partitions for threshold (update mod to new_mod in each level)
  networkx/algorithms/community/louvain.py
  networkx/algorithms/community/tests/test_louvain.py
Labels: Defect

#5288 Fixing Tarjan's strongly connected components algorithm implementation to have O(|E|+|V|) time complexity instead of O(|E|^2/V)
  networkx/algorithms/components/strongly_connected.py
Labels: Enhancement

#5285 Weighted karate club graph
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_louvain.py
  networkx/algorithms/community/tests/test_modularity_max.py
  networkx/algorithms/non_randomness.py
  networkx/algorithms/tests/test_non_randomness.py
  networkx/generators/social.py
Labels: Enhancement
