Repository networkx/networkx, pull requests merged in 2023-12, with the labels that each got.

#7098 Add doc total_spanning_tree_weight
  doc/reference/linalg.rst
Labels: type: Documentation

#6858 Implementation of $S^1$ model
  doc/reference/generators.rst
  networkx/generators/geometric.py
  networkx/generators/tests/test_geometric.py
Labels: type: Enhancements

#7040 Image (3D RGB data) segmentation by spectral clustering with 3D illustrations
  examples/algorithms/plot_image_segmentation_spectral_graph_partiion.py
  requirements/example.txt
Labels: type: Documentation

#7141 update triadic_census documentation for undirected graphs - issue 4386
  networkx/algorithms/triads.py
Labels: type: Documentation

#6968 Dinitz correction
  networkx/algorithms/flow/dinitz_alg.py
Labels: type: Bug fix

#7066 Compare graphs for generator functions when running tests with backend
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/operators/product.py
  networkx/algorithms/regular.py
  networkx/algorithms/triads.py
  networkx/classes/tests/test_backends.py
  networkx/generators/classic.py
  networkx/generators/ego.py
  networkx/generators/lattice.py
  networkx/utils/backends.py
Labels: type: Enhancements

#6926 Add Kirchhoff index / Effective graph resistance
  doc/reference/algorithms/distance_measures.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: type: Enhancements

#7152 DOC: fix URL econded links and doc references
  doc/reference/algorithms/dag.rst
  networkx/algorithms/cycles.py
  networkx/algorithms/dag.py
Labels: type: Documentation

#6584 Changed return types of shortest path methods to improve consistency
  networkx/algorithms/centrality/reaching.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/tests/test_unweighted.py
  networkx/algorithms/shortest_paths/unweighted.py
Labels: type: Enhancements

#6417 adding test coverage for isomorphism when using digraphs
  networkx/algorithms/isomorphism/tests/test_isomorphism.py
Labels: type: Maintenance

#7157 Remove usage of `__networkx_plugin__` (use `__networkx_backend__` instead)
  networkx/utils/backends.py
Labels: type: Maintenance

#7162 DOC: consistent spelling of neighbor and rename vars
  networkx/algorithms/approximation/treewidth.py
  networkx/algorithms/centrality/voterank_alg.py
  networkx/algorithms/cluster.py
  networkx/algorithms/coloring/greedy_coloring.py
  networkx/algorithms/coloring/tests/test_coloring.py
  networkx/algorithms/community/asyn_fluid.py
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/louvain.py
  networkx/algorithms/core.py
  networkx/algorithms/dominating.py
  networkx/algorithms/graph_hashing.py
  networkx/algorithms/isomorphism/ismags.py
  networkx/algorithms/isomorphism/vf2pp.py
  networkx/algorithms/matching.py
  networkx/algorithms/planar_drawing.py
  networkx/algorithms/similarity.py
  networkx/algorithms/sparsifiers.py
  networkx/algorithms/summarization.py
  networkx/algorithms/tests/test_mis.py
  networkx/classes/graph.py
  networkx/generators/duplication.py
  networkx/generators/line.py
  networkx/generators/random_graphs.py
Labels: type: Maintenance

#7167 DOC: add reference to fast_label_propagation_communities
  doc/reference/algorithms/community.rst
Labels: type: Documentation

#7160 MAINT: use ruff format instead of black
  .pre-commit-config.yaml
  networkx/algorithms/assortativity/correlation.py
  networkx/algorithms/isomorphism/ismags.py
  networkx/algorithms/isomorphism/tests/test_vf2pp_helpers.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/tests/test_bridges.py
  networkx/utils/tests/test_misc.py
Labels: type: Maintenance

#7163 updated See also sec of argmap class
  networkx/utils/decorators.py
Labels: type: Documentation

#7159 Modify GML test to fix invalid octal character warning.
  networkx/readwrite/tests/test_gml.py
Labels: type: Bug fix

#7169 DOC : updated examples in mincost.py
  networkx/algorithms/flow/mincost.py
Labels: type: Documentation

#7161 Ensure warnings related to changes in shortest_path returns are visible to users
  doc/developer/deprecations.rst
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/unweighted.py
  networkx/conftest.py
Labels: type: Maintenance

#5849 Sync up behavior of is_{type} for empty graphs
  networkx/algorithms/chordal.py
  networkx/algorithms/components/tests/test_strongly_connected.py
  networkx/algorithms/components/tests/test_weakly_connected.py
  networkx/algorithms/dag.py
  networkx/algorithms/distance_regular.py
  networkx/algorithms/regular.py
  networkx/algorithms/tests/test_dag.py
  networkx/algorithms/tests/test_distance_regular.py
  networkx/algorithms/tests/test_euler.py
  networkx/algorithms/tests/test_regular.py
  networkx/algorithms/tree/tests/test_recognition.py
Labels: type: Maintenance

#7110 Added `NodeNotFound` exceptions to `_apply_prediction` and `simrank`, and ignored isolated nodes in `panther_similarity`
  networkx/algorithms/link_prediction.py
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_link_prediction.py
  networkx/algorithms/tests/test_similarity.py
Labels: type: Maintenance

#7171 Document the walk_type argument default in directed_laplacian and similar functions.
  networkx/algorithms/centrality/laplacian.py
  networkx/linalg/laplacianmatrix.py
Labels: type: Documentation

#7114 DOC: Add plots to classic graph generators docs
  doc/conf.py
  networkx/generators/classic.py
Labels: type: Documentation

#7182 Fix not_implemented_for decorator for is_regular and related functions
  networkx/algorithms/approximation/maxcut.py
  networkx/algorithms/approximation/tests/test_maxcut.py
  networkx/algorithms/community/asyn_fluid.py
  networkx/algorithms/community/tests/test_asyn_fluid.py
  networkx/algorithms/distance_regular.py
  networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
  networkx/algorithms/isomorphism/tree_isomorphism.py
  networkx/algorithms/tests/test_distance_regular.py
Labels: type: Maintenance

#7019 New PR for Fixes minimal d-separator function failing to handle cases where no d-separators exist
  doc/developer/deprecations.rst
  doc/reference/algorithms/d_separation.rst
  networkx/algorithms/d_separation.py
  networkx/algorithms/tests/test_d_separation.py
  networkx/conftest.py
Labels: type: Enhancements

#6558 Fix all_node_cuts output for complete graphs
  networkx/algorithms/connectivity/kcutsets.py
  networkx/algorithms/connectivity/tests/test_kcutsets.py
Labels: type: Maintenance

#7198 Fix a tiny typo in `structuralholes.py::local_constraint` docstring
  networkx/algorithms/structuralholes.py
Labels: type: Documentation

#7197 Added `subgraph_is_monomorphic` and `subgraph_monomorphisms_iter` in docs
  doc/reference/algorithms/isomorphism.vf2.rst
Labels: type: Documentation
