Repository networkx/networkx, pull requests merged in 2023-09, with the labels that each got.

#6841 Modify `s_metric` `normalized` default so function doesn't raise
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/smetric.py
  networkx/algorithms/tests/test_smetric.py
  networkx/conftest.py
Labels: type: Bug fix

#6900 MAINT: Make GEXF and graphml writer work with numpy 2.0
  networkx/readwrite/gexf.py
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_graphml.py
Labels: type: Maintenance

#6457 Error handling for invalid prufer sequence `from_prufer_sequence`: issue #6420
  networkx/algorithms/tree/coding.py
Labels: type: Bug fix

#6907 fix doc build errors/warnings
  examples/algorithms/plot_subgraphs.py
  networkx/algorithms/smetric.py
  networkx/readwrite/text.py
Labels: type: Documentation

#6917 DOC: stray backtick and double instead of simple backtick.
  networkx/algorithms/polynomials.py
Labels: type: Documentation

#6901 DOC: Add example for self loop multidigraph in contraction
  networkx/algorithms/minors/contraction.py
Labels: type: Documentation

#6895 Fix sphinx docs rendering of dispatched functions
  doc/conf.py
  networkx/utils/backends.py
Labels: type: Documentation

#6908 Rename function `join` as `join_trees`
  doc/developer/deprecations.rst
  doc/reference/algorithms/tree.rst
  networkx/algorithms/tree/operations.py
  networkx/algorithms/tree/tests/test_operations.py
Labels: type: Maintenance

#6905 API: Add a decorator to deprecate positional args
  networkx/classes/function.py
  networkx/classes/graph.py
  networkx/classes/graphviews.py
  networkx/classes/tests/test_coreviews.py
  networkx/classes/tests/test_subgraphviews.py
  networkx/utils/decorators.py
Labels: type: API

#6894 FIX: Better default behaviour for percolation centrality with no node attrs
  networkx/algorithms/centrality/percolation.py
  networkx/algorithms/centrality/tests/test_percolation_centrality.py
Labels: type: Bug fix

#6880 Add time series Visibility Graph generator
  doc/reference/generators.rst
  examples/graph/plot_visibility_graph.py
  networkx/generators/__init__.py
  networkx/generators/tests/test_time_series.py
  networkx/generators/time_series.py
Labels: type: Enhancements

#6933 add missing `join` deprecation stuff to release_dev and conftest
  doc/release/release_dev.rst
  networkx/conftest.py
Labels: type: Maintenance

#6939 Expire deprecation for `attrs` kwarg in node_link module
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/json_graph/tests/test_node_link.py
Labels: type: API

#5634 added more examples on graphical degree sequence
  networkx/algorithms/graphical.py
Labels: type: Documentation

#6936 MAINT: Use importlib.resources instead of file dunder to access files
  networkx/algorithms/flow/tests/test_maxflow_large_graph.py
  networkx/algorithms/flow/tests/test_mincost.py
  networkx/algorithms/flow/tests/test_networksimplex.py
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
  networkx/generators/atlas.py
Labels: type: Maintenance

#6937 DOC, MAINT: Deduplicate docs instructions.
  CONTRIBUTING.rst
  doc/README.rst
Labels: type: Maintenance

#6758 Random trees & forests
  doc/developer/about_us.rst
  doc/developer/deprecations.rst
  doc/reference/generators.rst
  doc/release/release_dev.rst
  networkx/algorithms/tests/test_distance_measures.py
  networkx/conftest.py
  networkx/generators/tests/test_trees.py
  networkx/generators/trees.py
Labels: type: Enhancements

#6942 Minor touchup to the sort_neighbors deprecation.
  doc/reference/algorithms/traversal.rst
  networkx/algorithms/traversal/breadth_first_search.py
Labels: type: Documentation

#6940 Rm deprecated `create_using` kwarg from scale_free_graph
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/generators/directed.py
  networkx/generators/tests/test_directed.py
Labels: type: API

#6816 Make position part of the API for geometric_edges
  networkx/generators/geometric.py
  networkx/generators/tests/test_geometric.py
Labels: type: API

#5171 Warning comment for float weights in betweenness.py
  networkx/algorithms/centrality/betweenness.py
Labels: type: Documentation, floating-point

#6943 Undeprecate literal_(de)stringizer
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/gml.py
Labels: Discussion, type: API

#6950 Add support for tuple-nodes to default gml parser
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: type: Enhancements

#6954 Make new dtype param for incidence_matrix kwarg-only.
  networkx/linalg/graphmatrix.py
Labels: type: API

#6955 Make weight and seed for `fast_label_propagation_communities` kwarg only
  networkx/algorithms/community/label_propagation.py
Labels: type: API

#6929 Add Kemeny's constant
  doc/reference/algorithms/distance_measures.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: type: Enhancements

#6959 DOC: Misc typos.
  doc/reference/linalg.rst
  networkx/algorithms/operators/product.py
  networkx/linalg/algebraicconnectivity.py
Labels: type: Documentation

#6963 FIX: MultiDiGraphs keys got lost in weighted shortest paths
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: type: Bug fix

#6773 Update numpydoc
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#6967 Fixing typo in effective_size documentation
  networkx/algorithms/structuralholes.py
Labels: type: Documentation

#6925 Speedup resistance_distance
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: type: Enhancements

#6964 fix examples in tournament.py
  networkx/algorithms/tournament.py
Labels: type: Documentation
