Repository networkx/networkx, pull requests merged in 2023-05, with the labels that each got.

#6674 MAINT: minor coverage cleanup.
  networkx/algorithms/approximation/clique.py
Labels: Maintenance

#6675 Rm unreachable code for validating input
  networkx/algorithms/approximation/connectivity.py
Labels: Maintenance

#6647 Add Greedy Coloring Example to Gallery
  examples/algorithms/plot_greedy_coloring.py
Labels: Documentation

#6680 Pin sphinx<7 as temporary fix for doc CI failures
  requirements/doc.txt
Labels: Maintenance

#6651 Remove `topo_order` kwarg from `is_semiconnected` without deprecation.
  doc/release/release_dev.rst
  networkx/algorithms/components/semiconnected.py
Labels: Defect

#5094 Example of improving test granularity related to #5092
  networkx/generators/tests/test_random_graphs.py
Labels: Maintenance

#6692 Add linting to contributor guide.
  CONTRIBUTING.rst
Labels: Documentation

#6715 Stabilize test of approximation.connected_components
  networkx/algorithms/approximation/tests/test_kcomponents.py
Labels: Defect
