Repository networkx/networkx, pull requests merged in 2023-07, with the labels that each got.

#6775 update the OSMnx example
  examples/geospatial/plot_osmnx.py
Labels: Maintenance

#6776 Minor fixups to clear up numpy deprecation warnings
  networkx/algorithms/centrality/katz.py
  networkx/algorithms/distance_measures.py
Labels: Maintenance

#6648 Rewrite NXEP 3
  doc/developer/nxeps/nxep-0003.rst
Labels: NXEP

#6788 Fix minimum_cycle_basis and change to return cycle instead of set
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_cycles.py
Labels: Defect

#6789 Refix minimum_cycle_basis and scipy.sparse conversions and add tests
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_cycles.py
  networkx/convert_matrix.py
Labels: Defect

#6797 Add label-check workflow
  .github/workflows/label-check.yml
Labels: type: Maintenance

#6799 Use dependabot
  .github/dependabot.yml
Labels: type: Maintenance

#6802 Attach milestone to merged PRs
  .github/workflows/milestone-merged-prs.yaml
Labels: type: Maintenance

#6785 deprecate Edmonds class
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/tree/tests/test_branchings.py
  networkx/conftest.py
Labels: type: API

#6258 Update calculation of triangles
  networkx/algorithms/cluster.py
Labels: type: Enhancements

#5959 Add single_source_all_shortest_paths and all_pairs_all_shortest_paths
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/unweighted.py
Labels: type: Enhancements

#6815 number_of_walks might use a weighted edge attribute
  networkx/algorithms/tests/test_walks.py
  networkx/algorithms/walks.py
Labels: type: Bug fix

#6812 Add preserve_all_attrs to convert_from_nx to make it concise
  networkx/algorithms/bipartite/projection.py
  networkx/algorithms/dag.py
  networkx/algorithms/minors/contraction.py
  networkx/algorithms/operators/all.py
  networkx/algorithms/operators/binary.py
  networkx/algorithms/tree/mst.py
  networkx/relabel.py
  networkx/utils/backends.py
Labels: type: Maintenance

#6814 Make weight part of the API for functions which had default assumptions
  networkx/algorithms/centrality/second_order.py
  networkx/algorithms/centrality/tests/test_second_order_centrality.py
  networkx/algorithms/minors/contraction.py
  networkx/algorithms/minors/tests/test_contraction.py
  networkx/algorithms/similarity.py
  networkx/algorithms/tests/test_similarity.py
  networkx/algorithms/walks.py
Labels: type: API

#6818 Remove survey banner
  doc/conf.py
Labels: type: Documentation
