Repository networkx/networkx, pull requests merged in 2023-11, with the labels that each got.

#7079 Fix annoying split strings on same line
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/centrality/katz.py
  networkx/algorithms/coloring/greedy_coloring.py
  networkx/algorithms/covering.py
  networkx/algorithms/richclub.py
  networkx/algorithms/tests/test_planar_drawing.py
  networkx/drawing/nx_agraph.py
  networkx/generators/community.py
  networkx/generators/interval_graph.py
  networkx/readwrite/adjlist.py
  networkx/readwrite/graph6.py
  networkx/readwrite/multiline_adjlist.py
  networkx/readwrite/sparse6.py
Labels: type: Maintenance

#7083 Remove nbconvert upper pin (revert #6984)
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#7077 Add a step to CI to check for warnings at import time.
  .github/workflows/test.yml
Labels: type: Maintenance

#7073 [A-star] Added expansion pruning via cutoff if cutoff is provided
  networkx/algorithms/shortest_paths/astar.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
Labels: type: Enhancements, type: API

#7084 Make HITS raise exceptions consistent with power iterations
  networkx/algorithms/link_analysis/hits_alg.py
  networkx/algorithms/link_analysis/tests/test_hits.py
Labels: type: API

#6973 Handle edge cases for greedy_modularity_communities
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/tests/test_modularity_max.py
Labels: type: Bug fix

#7086 DOC: Add docstrings to filter view functions
  networkx/classes/filters.py
Labels: type: Documentation

#7075 DOC: Add docstrings to Filter mapping views
  networkx/classes/coreviews.py
Labels: type: Documentation

#6976 Added few tests for /generators/duplication.py and /generators/geomet…
  networkx/generators/geometric.py
  networkx/generators/tests/test_duplication.py
  networkx/generators/tests/test_geometric.py
Labels: type: Maintenance

#7096 Test on Python 3.13-dev
  .github/workflows/test.yml
Labels: type: Maintenance

#7061 DEP: Deprecate random_triad
  doc/developer/deprecations.rst
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
  networkx/conftest.py
Labels: type: API

#6706 DOCS: Fix internal links to other functions in isomorphvf2
  networkx/algorithms/isomorphism/isomorphvf2.py
Labels: type: Documentation

#7092 FIX: Match the doc description while copying over data
  networkx/algorithms/operators/binary.py
  networkx/algorithms/operators/tests/test_binary.py
Labels: type: Bug fix

#6995 added note for the triangle inequality case in TSP
  networkx/algorithms/approximation/traveling_salesman.py
Labels: type: Documentation

#7103 Add note about importance of testing to contributor guide
  doc/developer/new_contributor_faq.rst
Labels: type: Documentation

#7104 Proposal to add centrality overview to mentored projects.
  doc/developer/projects.rst
Labels: type: Documentation

#5473 Improve documentation of Component Algorithms
  networkx/algorithms/components/connected.py
Labels: type: Documentation

#6261 Changed arguments list of GraphMLWriterLxml.dump()
  networkx/readwrite/graphml.py
Labels: type: Maintenance

#5061 Add dot io to readwrite
  doc/reference/readwrite/dot.rst
  doc/reference/readwrite/index.rst
Labels: type: Documentation

#7109 `write_graphml`: Small fix for object type description on `TypeError` exception
  networkx/readwrite/graphml.py
Labels: type: Maintenance

#7113 Add Python versions to release notes
  doc/_static/version_switcher.json
  doc/release/release_3.2.1.rst
  doc/release/release_3.2.rst
Labels: type: Documentation

#6401 DOC: Turn on inline plots in graph generators docstrings
  doc/conf.py
  networkx/generators/classic.py
Labels: type: Documentation

#7116 Fix duplicate numbering in contributor guide
  CONTRIBUTING.rst
Labels: type: Documentation

#7027 updated functions in `core.py`
  networkx/algorithms/core.py
  networkx/algorithms/tests/test_core.py
Labels: type: Maintenance

#7115 DOC: remove unnecessary 'or' in planted_partition_graph
  networkx/generators/community.py
Labels: type: Documentation

#7125 DOC: Link methods in functions to base Graph methods/properties
  networkx/classes/function.py
Labels: type: Documentation

#6694 fix: Include singleton/trivial paths in all_simple_paths & other functions
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/simple_paths.py
  networkx/algorithms/tests/test_cycles.py
  networkx/algorithms/tests/test_simple_paths.py
Labels: type: Bug fix

#7111 label check on push and change check name
  .github/workflows/label-check.yml
Labels: type: Maintenance

#7121 DEP : adding `not_implemented_for("multigraph”)` to `k_core`, `k_shell`, `k_crust` and `k_corona`
  doc/developer/deprecations.rst
  networkx/algorithms/core.py
  networkx/algorithms/tests/test_core.py
  networkx/conftest.py
Labels: type: Maintenance
