Repository networkx/networkx, pull requests merged in 2023-03, with the labels that each got.

#5572 Remove pdf latex builds of docs
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
Labels: Maintenance

#6450 Add docstring for dorogovtsev_goltsev_mendes generator
  networkx/generators/classic.py
Labels: Documentation

#6471 tweak _dispatch to allow G keyword. Add test.
  networkx/classes/backends.py
  networkx/classes/tests/test_backends.py
Labels: Defect

#6493 Fix reference formatting in generator docstring.
  networkx/generators/classic.py
Labels: Documentation

#6478 Fix len operation of UnionAtlas
  networkx/classes/coreviews.py
  networkx/classes/tests/test_coreviews.py
Labels: Defect

#6519 Use generator to limit memory footprint of read_graph6.
  networkx/readwrite/graph6.py
Labels: Enhancement
