Repository networkx/networkx, pull requests merged in 2023-08, with the labels that each got.

#6827 Relax threshold in test of `betweenness_centrality`
  networkx/algorithms/tests/test_threshold.py
Labels: type: Maintenance

#6832 Add @nx._dispatch to {single_source,all_pairs}_all_shortest_paths, cd_index
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/tests/test_time_dependent.py
  networkx/algorithms/time_dependent.py
Labels: type: Maintenance

#6831 ci: Add distribution verification checks to nightly wheel upload
  .github/workflows/nightly.yml
Labels: type: Maintenance

#6837 GML: added support for reading multi-line values
  networkx/readwrite/gml.py
  networkx/readwrite/tests/test_gml.py
Labels: type: Bug fix

#6845 MAINT: fix link to nightly releases wheels
  .github/workflows/nightly-release-test.yml
Labels: type: Maintenance

#6852 Don't test numpy2 nightlies
  .github/workflows/nightly-release-test.yml
Labels: type: Maintenance

#6857 MAINT: replace numpy aliases in scipy namespace.
  networkx/linalg/laplacianmatrix.py
  networkx/tests/test_lazy_imports.py
Labels: type: Maintenance

#6727 Unpin scipy upperbound for tests
  .github/workflows/test.yml
Labels: type: Maintenance

#6854 Unpin numpy nightly wheels
  .github/workflows/nightly-release-test.yml
  networkx/conftest.py
Labels: type: Maintenance

#6860 fix: make messages readable
  networkx/algorithms/approximation/steinertree.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/drawing/nx_pydot.py
  networkx/generators/line.py
Labels: type: Maintenance, type: Documentation

#6859 Revert "Pin sphinx<7 as temporary fix for doc CI failures (#6680)"
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#6835 Move benchmarks inside main repo
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/benchmark_algorithms.py
  benchmarks/benchmarks/benchmark_classes.py
  benchmarks/benchmarks/utils.py
  requirements/benchmarking.txt
Labels: type: Enhancements

#6867 add docs for source input of dfs_predecessor and dfs_successor
  networkx/algorithms/traversal/depth_first_search.py
Labels: type: Documentation

#6866 Avoid directed_laplacian_matrix causing nans in some cases.
  networkx/linalg/laplacianmatrix.py
Labels: type: Bug fix

#6840 Change `_dispatch` to a class instead of a closure
  .github/workflows/test.yml
  networkx/algorithms/operators/tests/test_binary.py
  networkx/classes/tests/dispatch_interface.py
  networkx/classes/tests/test_backends.py
  networkx/conftest.py
  networkx/utils/backends.py
Labels: type: Maintenance

#6879 ENH -- Replaced for-loops in :function:`rescale_layout` with numpy vectorized methods.
  networkx/drawing/layout.py
Labels: type: Enhancements, Visualization

#6878 Move random_state decorators before `@nx._dispatch`
  networkx/algorithms/approximation/clustering_coefficient.py
  networkx/algorithms/approximation/distance_measures.py
  networkx/algorithms/approximation/maxcut.py
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/current_flow_betweenness.py
  networkx/algorithms/coloring/greedy_coloring.py
  networkx/algorithms/community/asyn_fluid.py
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/louvain.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/mis.py
  networkx/algorithms/smallworld.py
  networkx/algorithms/sparsifiers.py
  networkx/algorithms/swap.py
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/tree/mst.py
  networkx/algorithms/triads.py
  networkx/generators/spectral_graph_forge.py
  networkx/linalg/algebraicconnectivity.py
Labels: type: Maintenance

#6882 Clarify that basis generates simple cycles only
  networkx/algorithms/cycles.py
Labels: type: Documentation

#6843 Fast label propagation algorithm for community detection
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/community/tests/test_label_propagation.py
Labels: type: Enhancements

#6794 updating TSP example docs
  examples/drawing/plot_tsp.py
Labels: type: Documentation

#6892 Add test about zero weight cycles and fix goldberg-radzik
  doc/release/release_dev.rst
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: type: Bug fix

#6887 ENH: let users set a default value in get_attr methods
  doc/release/release_dev.rst
  networkx/classes/function.py
  networkx/classes/tests/test_function.py
Labels: type: API
