Repository networkx/networkx, pull requests merged in 2023-04, with the labels that each got.

#6598 corrections to docstring of `weisfeiler_lehman_subgraph_hashes`
  networkx/algorithms/graph_hashing.py
Labels: Documentation

#6600 Fixed method description in ismags.py
  networkx/algorithms/isomorphism/ismags.py
Labels: Documentation

#6614 Minor docs/test maintenance
  doc/developer/about_us.rst
  doc/developer/teams.inc
  networkx/algorithms/boundary.py
  networkx/conftest.py
Labels: Maintenance

#6611 Fix module docstring format for ismags reference article.
  doc/reference/algorithms/isomorphism.ismags.rst
  networkx/algorithms/isomorphism/ismags.py
Labels: Documentation

#6617 Resolve NXEP4 with justification for not implementing it.
  doc/developer/nxeps/nxep-0004.rst
Labels: NXEP

#6623 Fix links in laplacian_centrality and laplacian_matrix
  networkx/algorithms/centrality/laplacian.py
  networkx/linalg/laplacianmatrix.py
Labels: Documentation

#6474 Fixing DOT format for to_agraph()
  networkx/drawing/nx_agraph.py
  networkx/drawing/tests/test_agraph.py
Labels: Defect, Visualization

#6635 Replacing codecov Python CLI with gh action.
  .github/workflows/coverage.yml
  requirements/test.txt
Labels: Maintenance

#6634 Bump pyupgrade minimum Python version to 3.9.
  ruff.toml
Labels: Maintenance
