Repository networkx/networkx, pull requests merged in 2023-02, with the labels that each got.

#6407 Fix pre-commit on Python 3.10
  .pre-commit-config.yaml
Labels: Maintenance

#6303 Update installation test instructions
  CONTRIBUTING.rst
Labels: Documentation

#6142 Added new tests in test_clique.py
  networkx/algorithms/tests/test_clique.py
Labels: outreachy-review

#6424 Fix docstring heading title.
  networkx/readwrite/text.py
Labels: Documentation

#5563 Gallery example for Maximum Independent Set
  examples/algorithms/plot_maximum_independent_set.py
Labels: Documentation

#6434 Fix reference in line.py-inverse_line_graph
  networkx/generators/line.py
Labels: Documentation

#6437 Add documentation building to contributor guide
  CONTRIBUTING.rst
  doc/Makefile
  doc/conf.py
Labels: Documentation

#6451 Reset deploy-action param names for latest version.
  .github/workflows/deploy-docs.yml
Labels: Maintenance

#6399 Doc upgrade paley graph
  networkx/generators/expanders.py
Labels: Documentation

#6455 Added two tests for convert_numpy
  networkx/tests/test_convert_numpy.py
Labels: Maintenance

#5831 Clean up similarity.py and use dataclasses for storing state
  networkx/algorithms/similarity.py
Labels: Maintenance
