Repository networkx/networkx, pull requests merged in 2023-10, with the labels that each got.

#6969 MAINT: Scipy nightly failing with np alias
  networkx/algorithms/distance_measures.py
Labels: type: Maintenance

#6977 Fix a reference
  networkx/generators/classic.py
Labels: type: Documentation

#6978 Add missing parameter to snap_aggregation docstring
  networkx/algorithms/summarization.py
Labels: type: Documentation

#6982 Add for testing new pydata-sphinx-theme PR
  doc/_static/version_switcher.json
Labels: type: Maintenance

#6981 MAINT: Disable building delaunay geospatial example temporarily
  doc/conf.py
  examples/geospatial/fix_plot_delaunay.py
Labels: type: Maintenance

#6984 Revert "MAINT: Disable building delaunay geospatial example temporarily"
  doc/conf.py
  examples/geospatial/plot_delaunay.py
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#6948 Enhancements change default join trees 6947
  networkx/algorithms/tree/coding.py
  networkx/algorithms/tree/operations.py
  networkx/algorithms/tree/tests/test_operations.py
Labels: type: Maintenance

#6985 Update developer deprecation todo list
  doc/developer/deprecations.rst
Labels: type: Documentation

#6953 API: Rm default value from time_delta for cd_index.
  networkx/algorithms/tests/test_time_dependent.py
  networkx/algorithms/time_dependent.py
Labels: type: API

#6911 Add "networkx.plugin_info" entry point and update docstring
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
  doc/conf.py
  networkx/utils/backends.py
Labels: type: Documentation

#6957 Deprecate strongly_connected_components_recursive
  doc/developer/deprecations.rst
  doc/release/release_dev.rst
  networkx/algorithms/components/strongly_connected.py
  networkx/algorithms/components/tests/test_strongly_connected.py
  networkx/conftest.py
Labels: type: API

#6938 Handle edge cases in Laplacian centrality
  networkx/algorithms/centrality/laplacian.py
  networkx/algorithms/centrality/tests/test_laplacian_centrality.py
Labels: type: Bug fix

#6876 Allow graph generators and conversion functions to be dispatched
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/bipartite/matrix.py
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/core.py
  networkx/algorithms/graphical.py
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/threshold.py
  networkx/algorithms/tournament.py
  networkx/algorithms/tree/coding.py
  networkx/algorithms/tree/operations.py
  networkx/classes/tests/test_backends.py
  networkx/convert.py
  networkx/convert_matrix.py
  networkx/drawing/nx_agraph.py
  networkx/drawing/nx_pydot.py
  networkx/generators/atlas.py
  networkx/generators/classic.py
  networkx/generators/cographs.py
  networkx/generators/community.py
  networkx/generators/degree_seq.py
  networkx/generators/directed.py
  networkx/generators/duplication.py
  networkx/generators/expanders.py
  networkx/generators/geometric.py
  networkx/generators/harary_graph.py
  networkx/generators/internet_as_graphs.py
  networkx/generators/intersection.py
  networkx/generators/interval_graph.py
  networkx/generators/joint_degree_seq.py
  networkx/generators/lattice.py
  networkx/generators/mycielski.py
  networkx/generators/nonisomorphic_trees.py
  networkx/generators/random_clustered.py
  networkx/generators/random_graphs.py
  networkx/generators/small.py
  networkx/generators/social.py
  networkx/generators/sudoku.py
  networkx/generators/time_series.py
  networkx/generators/trees.py
  networkx/generators/triads.py
  networkx/readwrite/adjlist.py
  networkx/readwrite/edgelist.py
  networkx/readwrite/gexf.py
  networkx/readwrite/gml.py
  networkx/readwrite/graph6.py
  networkx/readwrite/graphml.py
  networkx/readwrite/json_graph/adjacency.py
  networkx/readwrite/json_graph/cytoscape.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/json_graph/tree.py
  networkx/readwrite/leda.py
  networkx/readwrite/multiline_adjlist.py
  networkx/readwrite/p2g.py
  networkx/readwrite/pajek.py
  networkx/readwrite/sparse6.py
  networkx/utils/backends.py
Labels: type: Enhancements

#6987 Generate requirements files from pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
  requirements/README.md
  requirements/default.txt
  requirements/developer.txt
  requirements/doc.txt
  requirements/extra.txt
  requirements/test.txt
  tools/generate_pyproject.toml.py
  tools/generate_requirements.py
  tools/pyproject.toml.in
Labels: type: Maintenance

#6988 Use trusted publisher
  .github/workflows/release.yml
  doc/developer/release.rst
Labels: type: Maintenance

#6989 Prefer "backend" instead of "plugin"
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
  doc/conf.py
  networkx/classes/tests/dispatch_interface.py
  networkx/conftest.py
  networkx/utils/backends.py
  pyproject.toml
Labels: type: Maintenance

#6630 adding a formula that ignores self-loops at the each level of directed louvain algorithm
  networkx/algorithms/community/louvain.py
  networkx/algorithms/community/tests/test_louvain.py
Labels: type: Bug fix

#6993 CI: Pin scientific-python/upload-nightly-action to 0.2.0
  .github/workflows/nightly.yml
Labels: type: Maintenance

#6992 document graph type; add links; rm unused import
  networkx/algorithms/community/asyn_fluid.py
  networkx/algorithms/community/kernighan_lin.py
  networkx/algorithms/community/lukes.py
  networkx/algorithms/community/modularity_max.py
  networkx/algorithms/community/quality.py
Labels: type: Documentation

#6997 Add 3.2rc0 release notes
  doc/release/release_dev.rst
Labels: type: Documentation

#7004 Update contributing guide for changelist workflow
  CONTRIBUTING.rst
Labels: type: Documentation

#7009 Support Python 3.12
  .github/workflows/test.yml
  pyproject.toml
Labels: type: Maintenance

#6990 Fix definition of $m$ parameter in docstring of `modularity` function
  networkx/algorithms/community/quality.py
Labels: type: Documentation

#7011 pip install nx-cugraph from git, not nightly wheels, for docs
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
Labels: type: Maintenance

#7013 updated docs of SA_tsp and TA_tsp
  networkx/algorithms/approximation/traveling_salesman.py
Labels: type: Documentation

#4890 adding extendability problem (2nd try)
  doc/reference/algorithms/bipartite.rst
  networkx/algorithms/bipartite/__init__.py
  networkx/algorithms/bipartite/extendability.py
  networkx/algorithms/bipartite/tests/test_extendability.py
Labels: type: Enhancements

#7012 Fix typos
  networkx/algorithms/centrality/eigenvector.py
  networkx/algorithms/community/tests/test_louvain.py
  networkx/algorithms/matching.py
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/tree/branchings.py
  networkx/generators/time_series.py
  networkx/utils/backends.py
Labels: type: Maintenance

#6941 Rm deprecated clique helper functions
  networkx/algorithms/clique.py
  networkx/algorithms/tests/test_clique.py
Labels: type: API

#7024 Fix ```is_k_edge_connected``` for case of k=2
  networkx/algorithms/connectivity/edge_augmentation.py
  networkx/algorithms/connectivity/tests/test_edge_augmentation.py
Labels: type: Bug fix

#7029 Update release process
  doc/developer/release.rst
Labels: type: Documentation

#7030 Fix listing of release notes on Releases page
  doc/release/index.rst
Labels: type: Bug fix

#7034 Fix syntax warning from bad escape sequence.
  networkx/algorithms/operators/product.py
Labels: type: Bug fix

#7028 Drop Python 3.9 support
  .github/workflows/deploy-docs.yml
  .github/workflows/nightly-release-test.yml
  .github/workflows/test.yml
  INSTALL.rst
  benchmarks/asv.conf.json
  networkx/algorithms/link_analysis/hits_alg.py
  networkx/algorithms/lowest_common_ancestors.py
  networkx/conftest.py
  networkx/convert.py
  networkx/convert_matrix.py
  networkx/drawing/nx_latex.py
  networkx/readwrite/gml.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/text.py
  networkx/relabel.py
  networkx/utils/backends.py
  networkx/utils/misc.py
  networkx/utils/tests/test_decorators.py
  pyproject.toml
Labels: type: Maintenance

#7041 Fix triangles to avoid using `is` to compare nodes
  networkx/algorithms/cluster.py
  networkx/algorithms/similarity.py
Labels: type: Bug fix

#6825 fix: Explicitly check for None/False in edge_attr during import from np
  networkx/convert_matrix.py
Labels: type: Maintenance

#7042 fix extendability function name in bipartite.rst
  doc/reference/algorithms/bipartite.rst
Labels: type: Documentation

#7048 Minor doc cleanups to remove doc build warnings
  doc/reference/algorithms/clique.rst
  doc/release/index.rst
  networkx/algorithms/bipartite/extendability.py
Labels: type: Documentation

#6999 Add Tadpole graph
  doc/reference/generators.rst
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Enhancements

#7043 Add favicon
  doc/_static/README.md
  doc/_static/favicon.ico
  doc/conf.py
Labels: type: Maintenance

#7053 Remove unused code resistance_distance
  networkx/algorithms/distance_measures.py
Labels: type: Maintenance

#7056 Fix error message for `nx.mycielski_graph(0)`
  networkx/generators/mycielski.py
Labels: type: Bug fix

#7055 Fix names of small graphs
  networkx/generators/small.py
Labels: type: Maintenance

#7057 Disallow negative number of nodes in `complete_multipartite_graph`
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Bug fix

#7062 Improve error messages for misconfigured backend treatment
  networkx/conftest.py
  networkx/lazy_imports.py
Labels: type: Maintenance

#7072 DOC: Add example to generic_bfs_edges to demonstrate the `neighbors` param
  networkx/algorithms/traversal/breadth_first_search.py
Labels: type: Documentation

#7071 MAINT: Fixup union exception message.
  networkx/algorithms/operators/all.py
Labels: type: Maintenance

#7049 MAINT: Minor touchups to tadpole and lollipop graph
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Maintenance

#7074 Add `@not_implemented_for("directed")` to `number_connected_components`
  networkx/algorithms/components/connected.py
Labels: type: Maintenance

#7076 remove unused code
  networkx/algorithms/distance_measures.py
Labels: type: Maintenance

#7060 DEP: Deprecate the all_triplets one-liner.
  doc/developer/deprecations.rst
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
  networkx/conftest.py
Labels: type: API

#7059 Minor touchups to the beamsearch module
  networkx/algorithms/traversal/beamsearch.py
  networkx/algorithms/traversal/tests/test_beamsearch.py
Labels: type: Maintenance

#7058 Hierarchical clustering layout gallery example
  examples/drawing/plot_clusters.py
Labels: type: Documentation

#6294 Fixed an error in the documentation of the katz centrality
  networkx/algorithms/centrality/katz.py
Labels: type: Documentation
