Repository networkx/networkx, pull requests merged in 2024-07, with the labels that each got.

#7524 Fixed the citation in `dominance.py` [Issue #7522]
  networkx/algorithms/dominance.py
  networkx/algorithms/tests/test_dominance.py
Labels: type: Documentation

#7473 Clarify generation number in `dorogovtsev_goltsev_mendes_graph()`
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Documentation

#7538 Fix CI installation of nx-cugraph in docs workflow
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
Labels: type: Maintenance

#7532 add: nodes attribute is modifiable
  networkx/readwrite/json_graph/node_link.py
Labels: type: Enhancements

#7535 Minor doc/test tweaks for dorogovtsev_goltsev_mendes
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Maintenance

#7363 Enable config to be used as context manager
  networkx/utils/configs.py
  networkx/utils/tests/test_config.py
Labels: type: Enhancements, Dispatching

#7415 Expires the `random_tree` deprecation
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/generators/tests/test_trees.py
  networkx/generators/trees.py
Labels: type: API

#7420 Expire deprecation for strongly_connected_components_recursive.
  doc/developer/deprecations.rst
  doc/reference/algorithms/component.rst
  networkx/algorithms/components/strongly_connected.py
  networkx/algorithms/components/tests/test_strongly_connected.py
  networkx/conftest.py
Labels: type: API

#7542 CI: Add timeout limit to coverage job
  .github/workflows/coverage.yml
Labels: type: Maintenance

#7537 Update images used in docs build workflow.
  .circleci/config.yml
Labels: type: Maintenance

#7417 Expire deprecated `sort_neighbors` param in `generic_bfs_edges`
  doc/developer/deprecations.rst
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/tests/test_bfs.py
Labels: type: API

#7418 Rm deprecated normalized param from s_metric.
  doc/developer/deprecations.rst
  networkx/algorithms/smetric.py
  networkx/algorithms/tests/test_smetric.py
Labels: type: API

#7226 WIP : removing parallelisation related TODO comments
  networkx/algorithms/efficiency_measures.py
  networkx/algorithms/isolate.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/algorithms/tournament.py
  networkx/algorithms/vitality.py
Labels: type: Maintenance

#7541 FIX: scipy 1d indexing tripped up numpy?
  networkx/algorithms/centrality/flow_matrix.py
Labels: type: Maintenance

#7419 Expire deprecated nx.join in favor of join_trees.
  doc/developer/deprecations.rst
  doc/reference/algorithms/tree.rst
  networkx/algorithms/tree/operations.py
  networkx/conftest.py
Labels: type: API

#7540 Minor touchups to node_link functions
  networkx/readwrite/json_graph/node_link.py
Labels: type: Maintenance

#7539 Minor updates to colliders v_structures tests
  networkx/algorithms/tests/test_dag.py
  networkx/conftest.py
Labels: type: Maintenance

#7447 Remove depercated Edmonds class for 3.4
  doc/developer/deprecations.rst
  doc/reference/algorithms/tree.rst
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/tree/tests/test_branchings.py
  networkx/conftest.py
  networkx/tests/test_all_random_functions.py
Labels: type: API

#7448 Remove depercated MultiDiGraph_EdgeKey for 3.4
  doc/developer/deprecations.rst
  networkx/algorithms/tree/branchings.py
  networkx/algorithms/tree/tests/test_branchings.py
  networkx/classes/tests/dispatch_interface.py
  networkx/conftest.py
Labels: type: API

#7548 Update sphinx gallery config to enable sphinx build caching
  doc/conf.py
  networkx/conftest.py
Labels: type: Maintenance

#7508 Update geospatial gallery dependencies
  requirements/example.txt
Labels: type: Maintenance

#7545 More accurate NodeNotFound error message.
  networkx/algorithms/shortest_paths/astar.py
  networkx/algorithms/shortest_paths/tests/test_unweighted.py
  networkx/algorithms/shortest_paths/unweighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: type: Maintenance

#7465 Fix reading edgelist when delimiter is whitespace, e.g. tab
  networkx/algorithms/bipartite/edgelist.py
  networkx/algorithms/bipartite/tests/test_edgelist.py
  networkx/readwrite/adjlist.py
  networkx/readwrite/edgelist.py
  networkx/readwrite/multiline_adjlist.py
  networkx/readwrite/tests/test_adjlist.py
  networkx/readwrite/tests/test_edgelist.py
Labels: type: Bug fix

#7552 Update ruff config
  .pre-commit-config.yaml
  pyproject.toml
Labels: type: Maintenance

#7551 Add changelist config
  pyproject.toml
Labels: type: Maintenance

#7454 Added code to handle multi-graph in mst
  networkx/algorithms/tree/mst.py
  networkx/algorithms/tree/tests/test_mst.py
Labels: type: Enhancements, Needs review

#7498 Enable caching by default
  networkx/utils/configs.py
Labels: type: Enhancements

#7558 #7546 More detail error message for pydot
  networkx/drawing/nx_pydot.py
Labels: type: Enhancements

#7561 Fix installing nx-cugraph in deploy docs CI
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
Labels: type: Maintenance

#7556 Add `Introspection` section to backends docs
  networkx/utils/backends.py
Labels: type: Documentation, Dispatching

#7567 DOC: Added `default_config` in `get_info`'s description
  networkx/utils/backends.py
Labels: type: Documentation, Dispatching

#7514 Prettify `README.rst`
  README.rst
Labels: type: Documentation

#7494 Ensure we always raise for unknown backend in `backend=`
  .github/workflows/test.yml
  networkx/algorithms/operators/tests/test_binary.py
  networkx/classes/tests/dispatch_interface.py
  networkx/conftest.py
  networkx/utils/backends.py
  networkx/utils/tests/test_backends.py
  pyproject.toml
Labels: type: Bug fix, Dispatching

#7572 DOC: Fix typo in the code snippet provided in the docstring of nx_pydot.pydot_layout().
  networkx/drawing/nx_pydot.py
Labels: type: Documentation

#7574 Fix installation instructions for `default` extras in README
  README.rst
Labels: type: Documentation
