Repository networkx/networkx, pull requests merged in 2024-06, with the labels that each got.

#7459 CI: Add GitHub artifact attestations to package distribution
  .github/workflows/release.yml
Labels: type: Maintenance

#7477 Change docs of `shortest_path_length` so return is number instead of int
  networkx/algorithms/shortest_paths/generic.py
Labels: type: Documentation

#7481 Use intersphinx_registry to manage intersphinx mapping.
  doc/conf.py
  pyproject.toml
  requirements/doc.txt
Labels: type: Documentation

#7480 chore: fix some comments
  networkx/algorithms/link_prediction.py
  networkx/generators/geometric.py
  networkx/utils/misc.py
Labels: type: Documentation

#7493 Fix test error when `scipy` is unavailable
  networkx/algorithms/polynomials.py
  networkx/conftest.py
Labels: type: Maintenance

#7492 MAINT: Renaming `LoopbackDispatcher` to `LoopbackBackendInterface` and `dispatcher` to `backend_interface`
  networkx/classes/tests/dispatch_interface.py
  networkx/utils/tests/test_backends.py
  pyproject.toml
Labels: type: Maintenance, Dispatching

#7503 CI: update action that got moved org
  .github/workflows/circleci.yml
Labels: type: Maintenance

#7506 Fix dispatch tests when using numpy 2
  networkx/utils/backends.py
Labels: type: Bug fix, Dispatching

#7507 Update momepy
  requirements/example.txt
Labels: type: Maintenance

#7512 Fix pygraphviz install on Windows
  .github/workflows/test.yml
Labels: type: Maintenance

#7511 strong product docs update
  networkx/algorithms/operators/product.py
Labels: type: Documentation

#7404 Refactoring and enhancing user-facing `Backend and Configs` docs
  doc/reference/backends.rst
  networkx/utils/backends.py
  networkx/utils/configs.py
Labels: type: Documentation, Dispatching

#7518 MAINT: Made `plot_image_segmentation_spectral_graph_partition` example compatible with scipy 1.14.0
  examples/algorithms/plot_image_segmentation_spectral_graph_partition.py
Labels: type: Maintenance

#7398 [ENH, BUG]: added `colliders` and `v_structures` and deprecated `compute_v_structures` in `dag.py`
  doc/developer/deprecations.rst
  doc/reference/algorithms/dag.rst
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
  networkx/conftest.py
Labels: type: Bug fix, type: API
