Repository networkx/networkx, pull requests merged in 2024-08, with the labels that each got.

#7586 Fix weakly_connected_components() performance on graph view
  networkx/algorithms/components/connected.py
  networkx/algorithms/components/weakly_connected.py
Labels: type: Enhancements

#7588 Fix `nx_pydot.graphviz_layout` for nodes with quoted/escaped chars
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
Labels: type: Maintenance, Visualization

#7543 Forceatlas2
  doc/reference/drawing.rst
  networkx/drawing/layout.py
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_layout.py
Labels: type: Enhancements, Visualization

#7592 Add missing metadata to v3.3 release notes
  doc/release/release_3.3.rst
Labels: type: Documentation

#7591 avoid iteration and use boolean indexing
  networkx/algorithms/similarity.py
Labels: type: Enhancements

#7599 DOC: Rm redundant module from autosummary.
  doc/tutorial.md
Labels: type: Maintenance

#7604 Correct the members of steering council
  doc/developer/teams.inc
Labels: type: Documentation

#7573 Update numpydoc (1.8)
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#7596 Bump minimum pydot version to 3.0.
  pyproject.toml
  requirements/extra.txt
Labels: type: Maintenance

#7594 CI: Include Python 3.13 in nightly wheel tests
  .github/workflows/nightly-release-test.yml
Labels: type: Maintenance

#7606 pydot - Remove Colon Check on Strings
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
  pyproject.toml
  requirements/extra.txt
Labels: type: Maintenance

#7583 Hide edges with a weight of None in simple_paths
  networkx/algorithms/simple_paths.py
  networkx/algorithms/tests/test_simple_paths.py
Labels: type: Enhancements

#7595 Improved running time for harmonic centrality
  benchmarks/benchmarks/benchmark_harmonic_centrality.py
  networkx/algorithms/centrality/harmonic.py
  networkx/algorithms/centrality/tests/test_harmonic_centrality.py
Labels: type: Enhancements, run:benchmark

#7569 Add remove attribute functions
  networkx/classes/function.py
  networkx/classes/tests/test_function.py
Labels: type: Enhancements, Needs review

#7610 Prevent `to_agraph` from modifying graph argument
  networkx/drawing/nx_agraph.py
Labels: type: Bug fix

#7553 MAINT: Do not use requirements files in circle CI
  .circleci/config.yml
  pyproject.toml
  requirements/example.txt
Labels: type: Maintenance

#7495 Do not use requirements file in github workflow.
  .github/workflows/benchmark.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/lint.yml
  .github/workflows/mypy.yml
  .github/workflows/nightly-release-test.yml
  .github/workflows/pytest-randomly.yml
  .github/workflows/test.yml
Labels: type: Maintenance

#7568 Log "can/should run" and caching in dispatch machinery
  networkx/utils/backends.py
Labels: type: Enhancements, Dispatching

#7570 Individualize drawing attributes
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Enhancements, Needs review, Visualization

#7614 `weisfeiler_lehman_graph_hash`: add `not_implemented_for("multigraph")` decorator
  networkx/algorithms/graph_hashing.py
Labels: type: Maintenance

#7616 Update teams doc by running `tools/team_list.py`
  doc/developer/teams.inc
Labels: type: Maintenance
