Repository networkx/networkx, pull requests merged in 2024-01, with the labels that each got.

#7194 Fix online docs for `_dispatch`
  networkx/utils/backends.py
Labels: type: Documentation

#7192 Remove `"networkx.plugins"` and `"networkx.plugin_info"` entry-points
  networkx/utils/backends.py
Labels: type: Maintenance

#7175 DOC : Updated docs for panther_similarity
  networkx/algorithms/similarity.py
Labels: type: Documentation

#7195 Fix warnings when building docs
  doc/developer/projects.rst
  networkx/algorithms/community/label_propagation.py
  networkx/algorithms/distance_measures.py
  networkx/algorithms/similarity.py
  networkx/classes/function.py
  networkx/generators/expanders.py
Labels: type: Documentation

#7203 Update test suite for Pytest v8
  networkx/algorithms/components/tests/test_strongly_connected.py
  networkx/drawing/tests/test_agraph.py
Labels: type: Maintenance

#7204 Undeprecate ``nx_pydot`` now that pydot is actively maintained again
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/drawing/nx_pydot.py
  networkx/drawing/tests/test_pydot.py
  pyproject.toml
  requirements/extra.txt
Labels: type: Maintenance

#7209 Future-proofing and improve tests
  networkx/algorithms/centrality/group.py
  networkx/conftest.py
  networkx/generators/expanders.py
Labels: type: Maintenance

#7217 Drop old dependencies per SPEC 0
  pyproject.toml
  requirements/default.txt
Labels: type: Maintenance

#7216 Update pygraphviz
  pyproject.toml
  requirements/extra.txt
Labels: type: Maintenance

#7210 Refactor geometric_soft_configuration_model tests for performance
  networkx/generators/tests/test_geometric.py
Labels: type: Maintenance

#7202 feat: drop the use of node attribute "first_nbr" in PlanarEmbedding
  networkx/algorithms/planar_drawing.py
  networkx/algorithms/planarity.py
  networkx/algorithms/tests/test_planarity.py
Labels: type: Enhancements

#7130 Improve docs for optimal_edit_paths
  networkx/algorithms/similarity.py
Labels: type: Documentation

#7211 Fix random_spanning_tree() for single node and empty graphs
  networkx/algorithms/tree/mst.py
  networkx/algorithms/tree/tests/test_mst.py
Labels: type: Bug fix

#6798 PlanarEmbedding.remove_edge() now updates removed edge's neighbors
  networkx/algorithms/planarity.py
  networkx/algorithms/tests/test_planarity.py
Labels: type: Bug fix

#7220 DOC: build with nx-parallel extra documentation information
  .circleci/config.yml
  .github/workflows/deploy-docs.yml
Labels: type: Documentation

#3709 Add functions to compute Schultz and Gutman Index
  doc/reference/algorithms/wiener.rst
  networkx/algorithms/__init__.py
  networkx/algorithms/tests/test_wiener.py
  networkx/algorithms/wiener.py
Labels: type: Enhancements

#7221 Replace tempfile with tmp_path fixture in test suite.
  networkx/algorithms/bipartite/tests/test_edgelist.py
  networkx/drawing/tests/test_agraph.py
  networkx/drawing/tests/test_pydot.py
  networkx/readwrite/tests/test_adjlist.py
  networkx/readwrite/tests/test_edgelist.py
  networkx/readwrite/tests/test_gml.py
  networkx/readwrite/tests/test_graph6.py
  networkx/readwrite/tests/test_graphml.py
  networkx/readwrite/tests/test_pajek.py
  networkx/readwrite/tests/test_sparse6.py
Labels: type: Maintenance

#7229 Fixed typo in tensor product documentation (Fixes #7228)
  networkx/algorithms/operators/product.py
Labels: type: Documentation

#6426 updated test_directed_edge_swap #5814
  networkx/algorithms/swap.py
  networkx/algorithms/tests/test_swap.py
Labels: type: Maintenance

#6560 Add example for cycle detection
  examples/algorithms/plot_cycle_detection.py
Labels: type: Documentation

#7232 Bump copyright year for 2024.
  LICENSE.txt
  README.rst
Labels: type: Maintenance

#5830 Divisive community algorithms
  doc/reference/algorithms/community.rst
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/divisive.py
  networkx/algorithms/community/tests/test_divisive.py
Labels: type: Enhancements

#7241 add seed to graph creation
  networkx/algorithms/tests/test_swap.py
Labels: type: Bug fix

#7242 add seed to tests of fast_label_propatation_communities
  networkx/algorithms/community/tests/test_label_propagation.py
Labels: type: Bug fix

#7227 Added feature modular graph product
  doc/reference/algorithms/operators.rst
  networkx/algorithms/operators/product.py
  networkx/algorithms/operators/tests/test_product.py
Labels: type: Enhancements, type: API

#7196 ENH : added `sort_neighbors` to all functions in `depth_first_search.py`
  networkx/algorithms/traversal/breadth_first_search.py
  networkx/algorithms/traversal/depth_first_search.py
  networkx/algorithms/traversal/tests/test_dfs.py
Labels: type: Enhancements

#7146 New graph generator for the Kneser graph
  doc/reference/generators.rst
  networkx/generators/classic.py
  networkx/generators/tests/test_classic.py
Labels: type: Enhancements

#7254 Update general_k_edge_subgraphs docstring.
  networkx/algorithms/connectivity/edge_kcomponents.py
Labels: type: Documentation

#7260 Improving test coverage for Small.py
  networkx/generators/tests/test_small.py
Labels: type: Maintenance

#7212 Fix rich_club_coefficient() for single node and empty graphs
  networkx/algorithms/richclub.py
  networkx/algorithms/tests/test_richclub.py
  networkx/classes/function.py
  networkx/classes/tests/test_function.py
Labels: type: Bug fix

#7251 Test for symmetric edge flow betweenness partition
  networkx/algorithms/community/tests/test_divisive.py
Labels: type: Maintenance
