Repository networkx/networkx, pull requests merged in 2024-04, with the labels that each got.

#7380 Fix pygraphviz tests causing segmentation faults in backend test
  networkx/utils/backends.py
Labels: type: Maintenance

#7386 Add dispatching to broadcasting.py
  networkx/algorithms/broadcasting.py
Labels: type: Maintenance

#7388 Update test suite to handle when scipy is not installed
  .github/workflows/test.yml
  networkx/algorithms/community/tests/test_divisive.py
  networkx/algorithms/tests/test_cycles.py
  networkx/algorithms/tests/test_distance_measures.py
  networkx/algorithms/tree/tests/test_mst.py
  networkx/conftest.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Maintenance

#7390 Rm deprecated np.row_stack in favor of vstack.
  networkx/drawing/layout.py
Labels: type: Maintenance

#7391 Fix exception for `del config[key]`
  networkx/utils/configs.py
  networkx/utils/tests/test_config.py
Labels: type: Maintenance

#7389 Move the backend docs and connect the config docs. Both in a single sidebar entry.
  doc/reference/backends.rst
  doc/reference/index.rst
  doc/reference/utils.rst
  networkx/utils/backends.py
  networkx/utils/configs.py
  networkx/utils/tests/test_backends.py
Labels: type: Documentation

#7394 Document missing shortest_path functions
  doc/reference/algorithms/shortest_paths.rst
  doc/release/release_3.3.rst
Labels: type: Documentation

#7375 Optimal Edit Paths Return Section Improved
  networkx/algorithms/similarity.py
Labels: type: Documentation

#7367 Simplify flow func augmentation logic in `connectivity` module
  networkx/algorithms/connectivity/connectivity.py
Labels: type: Maintenance

#7403 A few more doctest skips for mpl/np dependencies.
  networkx/conftest.py
Labels: type: Maintenance

#7399 Fix graph name attribute for `complete_bipartite_graph`
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/bipartite/tests/test_generators.py
Labels: type: Bug fix

#7406 Remove repetitive words
  CONTRIBUTING.rst
  networkx/algorithms/graph_hashing.py
  networkx/readwrite/text.py
Labels: type: Maintenance

#7378 FilterAdjacency: __len__ is recalculated unnecessarily #7377
  networkx/classes/coreviews.py
  networkx/classes/filters.py
Labels: type: Maintenance

#7412 Add a `nodelist` feature to `from_numpy_array`
  networkx/convert_matrix.py
  networkx/tests/test_convert_numpy.py
  networkx/tests/test_convert_pandas.py
Labels: type: Enhancements

#7414 Expires the `forest_str` deprecation
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/tests/test_text.py
  networkx/readwrite/text.py
Labels: type: API

#7393 Add check for empty graphs in `flow_hierarchy`
  networkx/algorithms/hierarchy.py
  networkx/algorithms/tests/test_hierarchy.py
Labels: type: Maintenance

#7421 Minor updates to simple_cycles docstring.
  networkx/algorithms/cycles.py
Labels: type: Documentation

#7426 Remove import warnings during to_networkx_graph conversion
  networkx/convert.py
Labels: type: Bug fix

#7425 Use nodelist feature of from_numpy_array.
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
Labels: type: Maintenance

#7411 Cleanup remaining usages of deprecated `random_tree` in package
  examples/algorithms/plot_lca.py
  networkx/algorithms/tests/test_cycles.py
  networkx/algorithms/tests/test_swap.py
  networkx/tests/test_all_random_functions.py
Labels: type: Maintenance

#7424 Prioritize edgelist representations in `to_networkx_graph`
  benchmarks/benchmarks/benchmark_to_networkx_graph.py
  networkx/classes/reportviews.py
  networkx/classes/tests/test_reportviews.py
  networkx/convert.py
Labels: type: Enhancements, Discussion
