Repository networkx/networkx, pull requests merged in 2024-05, with the labels that each got.

#7437 Update tests for macOS Sonoma v14
  .github/workflows/test.yml
Labels: type: Maintenance

#7435 Update doc requirements
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#7434 DOC: Clarifying `NetworkXPointlessConcept` exception
  networkx/exception.py
Labels: type: Documentation

#7416 DOC: updated `pairs.py`
  networkx/algorithms/assortativity/pairs.py
Labels: type: Documentation

#7441 Update pygraphviz
  pyproject.toml
  requirements/extra.txt
Labels: type: Maintenance

#7445 Fix nx.from_pandas_edgelist so edge keys are not added as edge attributes and edge keys
  networkx/convert_matrix.py
  networkx/tests/test_convert_pandas.py
Labels: type: Bug fix

#7449 Add docstring example for directed tree.
  networkx/generators/trees.py
Labels: type: Documentation

#7432 retain adjacency order in nx-loopback copy of networkx graph
  networkx/classes/digraph.py
  networkx/classes/graph.py
  networkx/classes/tests/dispatch_interface.py
  networkx/utils/backends.py
Labels: type: Maintenance

#7461 DEV: Add files generated by benchmarking to .gitignore.
  .gitignore
Labels: type: Maintenance

#7300 Adds initial debug logging calls to _dispatchable
  networkx/utils/backends.py
Labels: type: Enhancements, Dispatching

#7471 Remove redundant graph copy in `algorithms.bridges.bridges()`
  networkx/algorithms/bridges.py
Labels: type: Maintenance
