Repository networkx/networkx, pull requests merged in 2024-09, with the labels that each got.

#7619 Fix dispatch docs formatting
  networkx/utils/backends.py
Labels: type: Documentation

#7422 Implementing iterative removal of non_terminal_leaves in Steiner Tree approximation
  networkx/algorithms/approximation/steinertree.py
  networkx/algorithms/approximation/tests/test_steinertree.py
Labels: type: Bug fix

#7565 Add `edges` keyword/deprecate `link` keyword arguments in `JSON` input-output
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/json_graph/tests/test_node_link.py
Labels: type: API

#7620 added nx-parallel gsoc project
  doc/developer/projects.rst
Labels: type: Enhancements

#7621 Add to Contributor List
  doc/developer/about_us.rst
Labels: type: Documentation

#7350 Add single node with self loop check to local and global reaching centrality
  networkx/algorithms/centrality/reaching.py
  networkx/algorithms/centrality/tests/test_reaching.py
Labels: type: Maintenance

#5251 Harmonic diameter
  doc/reference/algorithms/distance_measures.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: type: Enhancements

#7549 Only allow connected graphs in `eigenvector_centrality_numpy`
  benchmarks/benchmarks/benchmark_algorithms.py
  networkx/algorithms/centrality/eigenvector.py
  networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
Labels: type: Bug fix, run:benchmark

#6355 Full test coverage for maxflow in issue #6029
  networkx/algorithms/flow/maxflow.py
  networkx/algorithms/flow/tests/test_maxflow.py
Labels: type: Maintenance

#7625 CI: Fix typo in nightly run pip install
  .github/workflows/nightly-release-test.yml
Labels: type: Bug fix, type: Maintenance

#7634 Example fix for issue 7633
  examples/algorithms/plot_maximum_independent_set.py
Labels: type: Documentation

#7639 DOC: Bring back plausible for docs
  doc/conf.py
Labels: type: Maintenance

#7631 Update minimum dependencies (SPEC 0)
  pyproject.toml
  requirements/default.txt
Labels: type: Maintenance

#7652 Revert breaking change to `node_link_*` link defaults
  doc/developer/deprecations.rst
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/json_graph/tests/test_node_link.py
Labels: type: API

#7644 Fix: Correct community color assignment in Girvan-Newman community detection.
  examples/algorithms/plot_girvan_newman.py
Labels: type: Documentation

#7626 Updated docstring for generators/karate_club_graph()
  networkx/generators/social.py
Labels: type: Documentation
