Repository networkx/networkx, pull requests merged in 2024-11, with the labels that each got.

#7708 Mv changelist to release deps.
  pyproject.toml
  requirements/developer.txt
  requirements/release.txt
Labels: type: Maintenance

#7668 Drop support for Python 3.10
  .github/workflows/lint.yml
  .github/workflows/mypy.yml
  .github/workflows/nightly-release-test.yml
  .github/workflows/nightly.yml
  .github/workflows/pytest-randomly.yml
  .github/workflows/test.yml
  INSTALL.rst
  benchmarks/asv.conf.json
  pyproject.toml
  requirements/developer.txt
Labels: type: Maintenance, run:benchmark

#7681 Re-submission of gh-7087 with better file provenance
  examples/3d_drawing/plot_3d_animation_basic.py
  examples/3d_drawing/plot_3d_animation_walk.py
  examples/3d_drawing/plot_3d_rotation_animation.py
Labels: type: Documentation

#7702 perf: optimise `random_k_out_graph`
  networkx/generators/directed.py
  networkx/generators/tests/test_directed.py
Labels: type: Enhancements

#7711 Update minimum dependencies (SPEC 0)
  pyproject.toml
  requirements/default.txt
Labels: type: Maintenance

#7453 trophic_levels now checks for paths from each node to a basal node
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/centrality/trophic.py
Labels: type: Bug fix

#7691 Clausets local community detection algorithm
  doc/reference/algorithms/community.rst
  networkx/algorithms/community/__init__.py
  networkx/algorithms/community/local.py
  networkx/algorithms/community/tests/test_local.py
Labels: type: Enhancements

#7715 Remove print statements and comments from test suite
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
  networkx/algorithms/approximation/tests/test_treewidth.py
  networkx/algorithms/assortativity/tests/test_mixing.py
  networkx/algorithms/assortativity/tests/test_neighbor_degree.py
  networkx/algorithms/bipartite/tests/test_generators.py
  networkx/algorithms/centrality/tests/test_laplacian_centrality.py
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/connectivity/tests/test_kcutsets.py
  networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
  networkx/algorithms/tests/test_chains.py
  networkx/algorithms/tests/test_similarity.py
  networkx/classes/tests/test_graphviews.py
  networkx/classes/tests/test_reportviews.py
  networkx/classes/tests/test_special.py
  networkx/drawing/tests/test_latex.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Maintenance

#7721 Fix TSP weight parameter issues
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
  networkx/algorithms/approximation/traveling_salesman.py
Labels: type: Bug fix, Needs review

#7729 Fix for filtered MultiGraph views from `edge_subgraph` (#7724).
  networkx/classes/coreviews.py
  networkx/classes/tests/test_subgraphviews.py
Labels: type: Bug fix

#7736 `find_asteroidal_triple` improvement
  networkx/algorithms/asteroidal.py
Labels: type: Enhancements

#7730 Fix code formatting of some examples
  networkx/algorithms/bipartite/generators.py
  networkx/algorithms/centrality/subgraph_alg.py
  networkx/generators/geometric.py
  networkx/readwrite/leda.py
Labels: type: Documentation

#7718 Add Python fallback to random_k_out_graph + document dependencies
  networkx/generators/directed.py
Labels: type: Maintenance

#7742 Fix sphinx warnings from numpydoc parsing.
  networkx/algorithms/community/local.py
Labels: type: Maintenance

#7746 MAINT: Updating geospatial example to be compatible with `osmnx=2.0.0`
  examples/geospatial/plot_osmnx.py
  pyproject.toml
  requirements/example.txt
Labels: type: Maintenance
