Repository networkx/networkx, pull requests merged in 2024-10, with the labels that each got.

#7585 Allow dispatch machinery to fall back to networkx
  networkx/algorithms/components/tests/test_connected.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
  networkx/algorithms/tests/test_structuralholes.py
  networkx/classes/graph.py
  networkx/conftest.py
  networkx/utils/backends.py
  networkx/utils/configs.py
  networkx/utils/tests/test_backends.py
  networkx/utils/tests/test_config.py
Labels: type: Enhancements, run:benchmark, Dispatching

#7635 modified product.py to raise NodeNotFound when 'root is not in H'
  networkx/algorithms/operators/product.py
  networkx/algorithms/operators/tests/test_product.py
Labels: type: Maintenance

#7661 Support Python 3.13
  .github/workflows/test.yml
  pyproject.toml
Labels: type: Maintenance

#5672 Add `create_using` parameter for random graphs.
  networkx/generators/duplication.py
  networkx/generators/random_graphs.py
  networkx/generators/tests/test_duplication.py
  networkx/generators/tests/test_random_graphs.py
  networkx/utils/misc.py
Labels: type: Enhancements

#7611 Updates documentation to include details about using NetworkX with backends.
  INSTALL.rst
  doc/backends.md
  doc/conf.py
  doc/index.rst
  doc/reference/backends.rst
  doc/reference/configs.rst
  doc/reference/index.rst
  doc/tutorial.md
  networkx/utils/backends.py
  networkx/utils/configs.py
Labels: type: Documentation, Dispatching

#7627 Add examples section to `to_scipy_sparse_array`
  networkx/convert_matrix.py
  networkx/linalg/graphmatrix.py
Labels: type: Documentation

#7667 Use official Python 3.13 release
  .github/workflows/test.yml
Labels: type: Maintenance

#7622 Add examples to docstrings of subgraph_(iso/monomorphism) methods
  networkx/algorithms/isomorphism/isomorphvf2.py
Labels: type: Documentation

#7497 Add config option to disable warning when using cached value
  networkx/utils/backends.py
  networkx/utils/configs.py
  networkx/utils/tests/test_config.py
Labels: type: Enhancements, Dispatching

#7669 Remove old deprecation decorator
  networkx/classes/graphviews.py
  networkx/utils/decorators.py
Labels: type: Maintenance

#7672 MAINT: delay loading of backend_info to after imports
  networkx/__init__.py
  networkx/utils/__init__.py
  networkx/utils/backends.py
  networkx/utils/configs.py
Labels: type: Maintenance

#7679 Fix docstrings of dispatchable functions
  networkx/__init__.py
  networkx/utils/backends.py
Labels: type: Bug fix, Dispatching

#7682 Fix doc warnings from recently added docs
  doc/backends.md
  doc/tutorial.md
  networkx/utils/configs.py
Labels: type: Maintenance

#7685 Fix draw_networkx_nodes return type
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Bug fix

#7683 Add disclaimer about LLM driven PRs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
Labels: type: Documentation

#7673 MAINT: wrapping `partial` with `staticmethod()` in `test_link_prediction.py`
  networkx/algorithms/tests/test_link_prediction.py
Labels: type: Maintenance

#7647 Updating `pip install`s in benchmarking workflow
  .github/workflows/benchmark.yml
  requirements/benchmarking.txt
Labels: type: Maintenance, run:benchmark

#7694 set nx-arangodb link to github
  doc/backends.md
Labels: type: Documentation

#7695 Update `_raise_on_directed` to work with `create_using` pos arg
  networkx/drawing/tests/test_pylab.py
  networkx/generators/small.py
  networkx/generators/tests/test_small.py
Labels: type: Bug fix
