Repository networkx/networkx, pull requests merged in 2024-12, with the labels that each got.

#7726 Add more tests for `nx.lowest_common_ancestor`
  networkx/algorithms/tests/test_lowest_common_ancestors.py
Labels: type: Maintenance

#7753 BUG: fixed the `if` condition in `asadpour_atsp`
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
  networkx/algorithms/approximation/traveling_salesman.py
Labels: type: Bug fix

#7754 Update `shortest_path` and `single_target_shortest_path_length` for 3.5
  doc/developer/deprecations.rst
  networkx/algorithms/centrality/reaching.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/tests/test_unweighted.py
  networkx/algorithms/shortest_paths/unweighted.py
  networkx/conftest.py
Labels: type: Maintenance

#7749 Add examples for custom graph in the doc of `soft_random_geometric_graph` and `thresholded_random_geometric_graph`
  networkx/conftest.py
  networkx/generators/geometric.py
Labels: type: Documentation

#7739 Implement Bar ConnectionStyle for labels
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Bug fix, Visualization

#7757 Gallery example: bipartite a/b-core motif
  examples/algorithms/plot_bipartite_motif_abcore.py
Labels: type: Documentation

#7737 Parametrize edge_subgraph multigraph test.
  networkx/classes/tests/test_subgraphviews.py
Labels: type: Maintenance

#7741 Add blurb about pytest-mpl dependency to contributing guide.
  CONTRIBUTING.rst
Labels: type: Documentation

#7636 Add `weight` to harmonic_diameter
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tests/test_distance_measures.py
Labels: type: Enhancements

#7731 Densest Subgraph Problem: Greedy Peeling and Greedy++ Implementations
  doc/reference/algorithms/approximation.rst
  networkx/algorithms/approximation/__init__.py
  networkx/algorithms/approximation/density.py
  networkx/algorithms/approximation/tests/test_density.py
Labels: type: Enhancements

#7637 Minor updates to `single_source_shortest_path_length` docstring
  networkx/algorithms/shortest_paths/unweighted.py
Labels: type: Documentation

#7762 single_source_all_shortest_paths: don't loop over all nodes
  networkx/algorithms/shortest_paths/generic.py
Labels: type: Enhancements, Needs PR

#7773 Added a note to the contributor guideline to avoid numpy scalars as a…
  CONTRIBUTING.rst
Labels: type: Documentation

#7778 Add filters for LOBPCG convergence warnings
  networkx/conftest.py
Labels: type: Maintenance

#7779 Correcting the example given under subgraph_is_monomorphic.py
  networkx/algorithms/isomorphism/isomorphvf2.py
Labels: type: Documentation
