Repository networkx/networkx, pull requests merged in 2025-03, with the labels that each got.

#7880 added 2 projects for GSoC 2025
  doc/developer/projects.rst
Labels: type: Documentation, GSoC

#7885 ruff check --select=PD002 --fix --unsafe-fixes
  networkx/algorithms/centrality/group.py
Labels: type: Maintenance

#7859 Activate pycodestyle in linting pre-commit
  examples/algorithms/plot_image_segmentation_spectral_graph_partition.py
  examples/drawing/plot_knuth_miles.py
  examples/graph/plot_morse_trie.py
  networkx/algorithms/approximation/tests/test_traveling_salesman.py
  networkx/algorithms/assortativity/tests/test_correlation.py
  networkx/algorithms/assortativity/tests/test_mixing.py
  networkx/algorithms/bipartite/tests/test_matrix.py
  networkx/algorithms/centrality/tests/test_eigenvector_centrality.py
  networkx/algorithms/centrality/tests/test_trophic.py
  networkx/algorithms/connectivity/connectivity.py
  networkx/algorithms/connectivity/cuts.py
  networkx/algorithms/connectivity/disjoint_paths.py
  networkx/algorithms/link_analysis/tests/test_hits.py
  networkx/algorithms/link_analysis/tests/test_pagerank.py
  networkx/algorithms/shortest_paths/tests/test_astar.py
  networkx/algorithms/shortest_paths/tests/test_dense_numpy.py
  networkx/algorithms/tests/test_distance_measures.py
  networkx/algorithms/tests/test_graph_hashing.py
  networkx/algorithms/tests/test_lowest_common_ancestors.py
  networkx/algorithms/tests/test_similarity.py
  networkx/algorithms/tests/test_tournament.py
  networkx/algorithms/traversal/tests/test_dfs.py
  networkx/algorithms/tree/tests/test_branchings.py
  networkx/classes/tests/test_function.py
  networkx/classes/tests/test_graphviews.py
  networkx/drawing/tests/test_agraph.py
  networkx/drawing/tests/test_pylab.py
  networkx/generators/line.py
  networkx/generators/tests/test_expanders.py
  networkx/linalg/tests/test_algebraic_connectivity.py
  networkx/linalg/tests/test_attrmatrix.py
  networkx/linalg/tests/test_bethehessian.py
  networkx/linalg/tests/test_graphmatrix.py
  networkx/linalg/tests/test_laplacian.py
  networkx/linalg/tests/test_modularity.py
  networkx/linalg/tests/test_spectrum.py
  networkx/readwrite/gexf.py
  networkx/readwrite/graphml.py
  networkx/readwrite/tests/test_gml.py
  networkx/readwrite/tests/test_graphml.py
  networkx/readwrite/tests/test_sparse6.py
  networkx/tests/test_all_random_functions.py
  networkx/tests/test_convert_numpy.py
  networkx/tests/test_convert_scipy.py
  networkx/tests/test_lazy_imports.py
  networkx/utils/tests/test_misc.py
  pyproject.toml
Labels: type: Maintenance

#7888 Correct sphinx warnings from doc build
  doc/developer/projects.rst
  doc/reference/configs.rst
  networkx/algorithms/approximation/density.py
Labels: type: Maintenance

#7703 Add missing usebounds param descr to distance docstrings.
  networkx/algorithms/distance_measures.py
Labels: type: Documentation

#7347 `effective_size` of nodes with only self-loop edges is undefined
  networkx/algorithms/structuralholes.py
  networkx/algorithms/tests/test_structuralholes.py
Labels: type: Maintenance

#7900 Add examples to graph_atlas_g docstring.
  networkx/generators/atlas.py
Labels: type: Documentation

#7249 Faster Implementation of Structural Holes
  networkx/algorithms/structuralholes.py
  networkx/algorithms/tests/test_structuralholes.py
  networkx/conftest.py
Labels: type: Enhancements

#7915 Add missing `weight` and `gravity` attribute to `forceatlas2_layout` docstring
  networkx/drawing/layout.py
Labels: type: Documentation

#7910 Fixed the return type from an empty dict to an empty set
  networkx/algorithms/connectivity/cuts.py
  networkx/algorithms/connectivity/tests/test_cuts.py
Labels: type: Bug fix

#7918 Add `edge_attrs="weight"` to `forceatlas2_layout` dispatch decorator
  networkx/drawing/layout.py
Labels: type: Bug fix, Dispatching

#7834 Fix graph_hash iteration counts and DiGraph handling
  networkx/algorithms/graph_hashing.py
  networkx/algorithms/tests/test_graph_hashing.py
Labels: type: Bug fix

#7883 DOC: docstring changes to `to_dict_of_dicts` and `attr_matrix` and input name change in `min_fill_in_heuristic`
  networkx/algorithms/approximation/treewidth.py
  networkx/convert.py
  networkx/linalg/attrmatrix.py
Labels: type: Maintenance

#7917 Improve runtime of number_of_nonisomorphic_trees().
  networkx/generators/nonisomorphic_trees.py
  networkx/generators/tests/test_nonisomorphic_trees.py
Labels: type: Enhancements

#7901 Refactored the working of chordless_cycles to handle self loops
  networkx/algorithms/cycles.py
  networkx/algorithms/tests/test_cycles.py
Labels: type: Bug fix

#7908 Fix bc scale with k endpoints
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/centrality/tests/test_betweenness_centrality.py
Labels: type: Bug fix

#7939 Update layout.py
  networkx/drawing/layout.py
Labels: type: Maintenance

#7928 DOC: Update first docstring example and add a serialization example.
  networkx/readwrite/json_graph/cytoscape.py
Labels: type: Documentation

#7914 Fix write_gexf timeformat for dynamic Graphs
  networkx/readwrite/gexf.py
  networkx/readwrite/tests/test_gexf.py
Labels: type: Enhancements

#7943 DOC: Remove myself from the mentor list for projects
  doc/developer/projects.rst
Labels: type: Documentation

#7920 Tree isomorphism input validation
  networkx/algorithms/isomorphism/tests/test_tree_isomorphism.py
  networkx/algorithms/isomorphism/tree_isomorphism.py
Labels: type: Maintenance

#7884 Tweaks and notes from a dive into backends.py
  networkx/utils/backends.py
  networkx/utils/tests/test_backends.py
Labels: type: Maintenance, Dispatching

#7852 Consolidate could_be_isomorphic
  networkx/algorithms/isomorphism/isomorph.py
  networkx/algorithms/isomorphism/tests/test_isomorphism.py
Labels: type: Enhancements, Discussion
