Repository networkx/networkx, pull requests merged in 2025-08, with the labels that each got.

#6893 3d facebook plot example
  examples/3d_drawing/plot_facebook_3d.py
Labels: type: Documentation

#8138 enh: short-circuit in `is_regular` for directed graphs
  networkx/algorithms/regular.py
  networkx/algorithms/tests/test_regular.py
Labels: type: Enhancements

#8186 fix: resolve failure to pickle.loads(pickle.dumps(PlanarEmbedding()))
  networkx/algorithms/planarity.py
Labels: type: Bug fix

#8198 MAINT: remove `try except` for `tomllib` in `generate_requirements`
  tools/generate_requirements.py
Labels: type: Maintenance

#8210 STY: Variable rename proposal in bidirectional_dijkstra
  networkx/algorithms/shortest_paths/weighted.py
Labels: type: Maintenance

#8211 BUG: Raise on directed graphs in `nx.find_cliques_recursive`
  networkx/algorithms/clique.py
  networkx/algorithms/tests/test_clique.py
Labels: type: Bug fix

#8166 Improve docs for `all_neighbors()`
  networkx/classes/function.py
Labels: type: Documentation

#8187 Adding shortest-paths documentation
  doc/reference/algorithms/shortest_paths.rst
Labels: type: Documentation
