Repository networkx/networkx, pull requests merged in 2025-02, with the labels that each got.

#7814 Fix `with nx.config(backend_priority=backends):`
  networkx/utils/configs.py
  networkx/utils/tests/test_config.py
Labels: type: Bug fix

#7799 Add a subplot fixture to automate test cleanup.
  networkx/drawing/tests/test_pylab.py
Labels: type: Maintenance

#7819 MAINT: use nx.layout instead of importing layouts.
  networkx/drawing/nx_pylab.py
Labels: type: Maintenance

#7818 MAINT: Move stub func in the correct scope for pickle test
  networkx/utils/tests/test_backends.py
Labels: type: Maintenance

#7821 Ensure standard import conventions are used
  .pre-commit-config.yaml
  doc/conf.py
  doc/reference/randomness.rst
  examples/algorithms/plot_blockmodel.py
  examples/drawing/plot_eigenvalues.py
  examples/graph/plot_visibility_graph.py
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/tests/test_regular.py
  networkx/classes/tests/test_digraph_historical.py
  networkx/classes/tests/test_graph_historical.py
  networkx/conftest.py
  networkx/convert.py
  networkx/generators/expanders.py
  networkx/generators/tests/test_directed.py
  networkx/utils/misc.py
Labels: type: Maintenance

#7822 Clean up pygrep pre-commit for import convention checks
  .pre-commit-config.yaml
Labels: type: Maintenance

#7756 Bipartite layout nodes optional
  doc/reference/drawing.rst
  networkx/drawing/layout.py
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/test_layout.py
  networkx/drawing/tests/test_pylab.py
Labels: type: Enhancements, Visualization

#7830 Expire d_separated and minimum_d_separator functions.
  doc/developer/deprecations.rst
  networkx/algorithms/d_separation.py
  networkx/algorithms/tests/test_d_separation.py
  networkx/conftest.py
Labels: type: API

#7828 Expire all_triplets deprecation.
  doc/developer/deprecations.rst
  doc/reference/algorithms/triads.rst
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
  networkx/conftest.py
Labels: type: API

#7829 Expire random_triad deprecation.
  doc/developer/deprecations.rst
  doc/reference/algorithms/triads.rst
  networkx/algorithms/tests/test_triads.py
  networkx/algorithms/triads.py
  networkx/conftest.py
  networkx/tests/test_all_random_functions.py
Labels: type: API

#7826 Deprecate graph_could_be_isomorphic
  doc/developer/deprecations.rst
  networkx/algorithms/isomorphism/isomorph.py
  networkx/algorithms/isomorphism/tests/test_isomorphism.py
  networkx/algorithms/tests/test_threshold.py
  networkx/generators/tests/test_classic.py
  networkx/generators/tests/test_small.py
Labels: type: API

#7833 Don't use `assert` when using `pytest.raises`
  networkx/algorithms/tests/test_link_prediction.py
  networkx/algorithms/tests/test_threshold.py
Labels: type: Maintenance

#7823 DOC: Add details about more grants
  doc/developer/about_us.rst
Labels: type: Documentation

#7776 Refactor: Moving backend docs from `backends.py` to `backends.rst`
  doc/reference/backends.rst
  networkx/utils/backends.py
Labels: type: Documentation, Dispatching

#7837 Update doc requirements
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#7839 Update developer requirements
  pyproject.toml
  requirements/developer.txt
Labels: type: Maintenance

#7840 MAINT: Minus not underscore in the dep package name
  pyproject.toml
  requirements/doc.txt
Labels: type: Maintenance

#7835 Update readwrite docstrings for the `path` parameter
  examples/drawing/plot_chess_masters.py
  networkx/algorithms/bipartite/edgelist.py
  networkx/drawing/nx_agraph.py
  networkx/drawing/nx_latex.py
  networkx/drawing/nx_pydot.py
  networkx/readwrite/adjlist.py
  networkx/readwrite/edgelist.py
  networkx/readwrite/gexf.py
  networkx/readwrite/gml.py
  networkx/readwrite/graph6.py
  networkx/readwrite/graphml.py
  networkx/readwrite/leda.py
  networkx/readwrite/multiline_adjlist.py
  networkx/readwrite/p2g.py
  networkx/readwrite/pajek.py
  networkx/readwrite/sparse6.py
Labels: type: Maintenance, type: Documentation

#7832 Fix docstring example of `nx.generate_random_paths(index_map=...)`
  networkx/algorithms/similarity.py
Labels: type: Maintenance, type: Documentation

#7770 Densest Subgraph Problem: FISTA based algorithm + Large scale tests.
  networkx/algorithms/approximation/density.py
  networkx/algorithms/approximation/tests/test_density.py
Labels: type: Enhancements

#7843 Expire total_spanning_tree_weight deprecation
  doc/developer/deprecations.rst
  doc/reference/linalg.rst
  networkx/algorithms/approximation/traveling_salesman.py
  networkx/algorithms/tree/mst.py
  networkx/conftest.py
  networkx/linalg/laplacianmatrix.py
Labels: type: API

#7824 Dispatch `get_node_attributes` and a few more from `nx.classes.function`
  networkx/classes/function.py
  networkx/utils/backends.py
Labels: type: Enhancements, Dispatching

#7846 Adds NVIDIA Corporation to list of supporters
  doc/developer/about_us.rst
Labels: type: Documentation

#7845 Fix use of triple backticks in docstrings
  networkx/algorithms/d_separation.py
  networkx/convert_matrix.py
Labels: type: Maintenance, type: Documentation

#7838 Add paragraph about university classes to mentored projects
  doc/developer/projects.rst
Labels: type: Documentation

#7847 Expire deprecation of create kwarg in nonisomorphic_trees.
  doc/developer/deprecations.rst
  networkx/conftest.py
  networkx/generators/nonisomorphic_trees.py
  networkx/generators/tests/test_nonisomorphic_trees.py
Labels: type: API

#7849 Fix pygraphviz_layout example
  networkx/drawing/nx_agraph.py
Labels: type: Documentation

#7853 Add .mailmap file to consilidate contributors.
  .mailmap
Labels: type: Maintenance

#7855 Faster `could_be_isomorphic` and `number_of_cliques`
  networkx/algorithms/clique.py
  networkx/algorithms/isomorphism/isomorph.py
Labels: type: Enhancements

#7854 Add test-extras to optional dependencies.
  CONTRIBUTING.rst
  pyproject.toml
  requirements/README.md
  requirements/test-extras.txt
Labels: type: Documentation

#7844 TST: Refactor example test case generation functions.
  networkx/algorithms/approximation/tests/test_density.py
Labels: type: Maintenance

#7796 Fix handling of faux_infinite values in network_simplex
  networkx/algorithms/flow/networksimplex.py
  networkx/algorithms/flow/tests/test_networksimplex.py
Labels: type: Bug fix

#7858 Refactor network_simplex test of faux_infinity.
  networkx/algorithms/flow/tests/test_networksimplex.py
Labels: type: Maintenance

#7861 Change CRLF format of two files
  examples/graph/plot_mst.py
  networkx/algorithms/flow/tests/test_networksimplex.py
Labels: type: Maintenance

#7863 Fix some typos
  benchmarks/benchmarks/benchmark_to_networkx_graph.py
  doc/developer/nxeps/nxep-0003.rst
  doc/reference/backends.rst
  doc/release/release_3.3.rst
  doc/release/release_3.4.rst
  doc/tutorial.md
  examples/3d_drawing/plot_3d_animation_walk.py
  examples/algorithms/plot_bipartite_motif_abcore.py
  networkx/algorithms/community/local.py
  networkx/convert_matrix.py
  networkx/drawing/layout.py
Labels: type: Maintenance

#7866 doc: hash size are in bytes
  networkx/algorithms/graph_hashing.py
Labels: type: Documentation

#7862 Pre commit hooks to check line endings and trailing whitespace
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  doc/developer/about_us.rst
  doc/developer/new_contributor_faq.rst
  doc/developer/nxeps/nxep-0002.rst
  doc/developer/nxeps/nxep-0004.rst
  doc/developer/projects.rst
  doc/developer/release.rst
  doc/reference/glossary.rst
  doc/reference/readwrite/dot.rst
  doc/release/migration_guide_from_2.x_to_3.0.rst
  doc/release/release_2.7.rst
  doc/release/release_3.0.rst
  doc/release/report_functions_without_rst_generated.sh
  examples/geospatial/extended_description.rst
  networkx/algorithms/tree/mst.py
  networkx/linalg/tests/test_laplacian.py
Labels: type: Maintenance

#7869 MAINT: replace the SHAs for blame and move the changes within pre-commit.
  .git-blame-ignore-revs
  .pre-commit-config.yaml
Labels: type: Maintenance

#7860 Rm stray instances of sparse matrices from test suite.
  networkx/algorithms/bipartite/tests/test_matrix.py
Labels: type: Maintenance

#7864 Remove unused imports
  doc/release/contribs.py
  networkx/algorithms/cycles.py
  networkx/algorithms/flow/tests/test_maxflow_large_graph.py
  networkx/algorithms/flow/tests/test_mincost.py
  networkx/algorithms/flow/tests/test_networksimplex.py
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/algorithms/matching.py
  networkx/algorithms/operators/tests/test_binary.py
  networkx/algorithms/shortest_paths/generic.py
  networkx/algorithms/shortest_paths/unweighted.py
  networkx/algorithms/tests/test_smallworld.py
  networkx/conftest.py
  networkx/convert.py
  networkx/drawing/nx_agraph.py
  networkx/drawing/nx_latex.py
  networkx/generators/atlas.py
  networkx/generators/trees.py
  networkx/linalg/algebraicconnectivity.py
  networkx/readwrite/gml.py
  networkx/readwrite/text.py
  networkx/tests/test_lazy_imports.py
  networkx/utils/configs.py
  networkx/utils/decorators.py
  networkx/utils/misc.py
Labels: type: Maintenance

#7857 Add square_clustering to algorithm benchmarks.
  benchmarks/benchmarks/benchmark_algorithms.py
Labels: type: Enhancements

#7878 Remove unnecessary `dict(...)` for SSSP algos that return dicts
  examples/basic/plot_properties.py
  examples/drawing/plot_random_geometric_graph.py
  networkx/algorithms/flow/maxflow.py
  networkx/algorithms/shortest_paths/tests/test_generic.py
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/tests/test_dominance.py
  networkx/generators/ego.py
  networkx/utils/rcm.py
Labels: type: Maintenance

#7881 DOC: Clean up mentored projects page: move visualization project to completed section
  doc/developer/projects.rst
Labels: type: Documentation
