Repository networkx/networkx, pull requests merged in 2025-05, with the labels that each got.

#8016 Minor follow-up to gh-8002 tests
  networkx/algorithms/tests/test_similarity.py
Labels: type: Maintenance

#7938 Add linting for line length in docstrings and comments
  examples/drawing/plot_tsp.py
  networkx/algorithms/community/quality.py
  networkx/algorithms/distance_measures.py
  networkx/algorithms/isomorphism/tests/test_vf2pp.py
  networkx/algorithms/isomorphism/tests/test_vf2pp_helpers.py
  networkx/algorithms/isomorphism/vf2pp.py
  networkx/algorithms/lowest_common_ancestors.py
  networkx/algorithms/operators/all.py
  networkx/algorithms/operators/binary.py
  networkx/algorithms/shortest_paths/dense.py
  networkx/algorithms/traversal/edgebfs.py
  networkx/algorithms/traversal/edgedfs.py
  networkx/algorithms/tree/operations.py
  networkx/drawing/layout.py
  networkx/generators/expanders.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/p2g.py
  networkx/utils/configs.py
  pyproject.toml
Labels: type: Maintenance

#7589 New draw API
  doc/reference/drawing.rst
  networkx/drawing/nx_pylab.py
  networkx/drawing/tests/baseline/test_display_complex.png
  networkx/drawing/tests/baseline/test_display_empty_graph.png
  networkx/drawing/tests/baseline/test_display_house_with_colors.png
  networkx/drawing/tests/baseline/test_display_labels_and_colors.png
  networkx/drawing/tests/baseline/test_display_shortest_path.png
  networkx/drawing/tests/test_pylab.py
Labels: Visualization, type: API

#8025 Add sg_execution_times.rst to gitignore
  .gitignore
Labels: type: Maintenance

#8027 Support both pydot v3 and pydot v4.
  networkx/drawing/nx_pydot.py
Labels: type: Maintenance

#8032 Clarifying backend graph class interface is_directed+is_multigraph
  doc/reference/backends.rst
Labels: type: Documentation

#8034 Fix bug when assigning list to `nx.config.backend_priority`
  networkx/utils/configs.py
  networkx/utils/tests/test_config.py
Labels: type: Bug fix

#8038 Update copyright license years
  LICENSE.txt
  README.rst
Labels: type: Maintenance

#7978 BiRank Algorithm Implementation
  doc/reference/algorithms/bipartite.rst
  networkx/algorithms/bipartite/__init__.py
  networkx/algorithms/bipartite/link_analysis.py
  networkx/algorithms/bipartite/tests/test_link_analysis.py
  networkx/algorithms/link_analysis/pagerank_alg.py
  networkx/conftest.py
Labels: type: Enhancements

#8047 Fix all sphinx build warnings
  doc/reference/backends.rst
  doc/release/release_dev.rst
  networkx/drawing/nx_pylab.py
  networkx/readwrite/graph6.py
Labels: type: Maintenance, type: Documentation

#8043 Enforce correct graph types for graph matchers
  networkx/algorithms/isomorphism/isomorphvf2.py
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
Labels: type: Enhancements

#8048 Fix intermittent test failures in expander graph generator tests
  networkx/generators/expanders.py
  networkx/generators/tests/test_expanders.py
Labels: type: Maintenance

#7929 Refactor tree_isomorphism to improve code reuse and readability
  networkx/algorithms/isomorphism/tree_isomorphism.py
Labels: type: Maintenance

#8029 A minimal fix for `is_aperiodic`
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
Labels: type: Bug fix

#8042 Add a new gallery spring layout
  examples/drawing/plot_spring_layout.py
Labels: type: Documentation, Visualization

#8041 fix bug of _sparse_fruchterman_reingold and remove try/except idiom
  networkx/drawing/layout.py
  networkx/drawing/tests/test_layout.py
Labels: type: Bug fix

#8051 STY: Rm local variable remapping of heappush and heappop.
  networkx/algorithms/centrality/betweenness.py
  networkx/algorithms/shortest_paths/astar.py
  networkx/algorithms/shortest_paths/weighted.py
  networkx/algorithms/simple_paths.py
  networkx/algorithms/tree/mst.py
  networkx/utils/heaps.py
Labels: type: Maintenance

#8049 TST: Minor improvements to layout test suite
  networkx/drawing/tests/test_layout.py
Labels: type: Maintenance

#8055 Fix edge case in ISMAGS symmetry detection
  networkx/algorithms/isomorphism/ismags.py
  networkx/algorithms/isomorphism/tests/test_ismags.py
Labels: type: Bug fix

#8068 Minor refactor to cleanup/improve matching test suite
  networkx/algorithms/tests/test_matching.py
Labels: type: Maintenance

#8075 Fix typo in `min_edge_cover` docstring
  networkx/algorithms/covering.py
Labels: type: Documentation
