Repository networkx/networkx, pull requests merged in 2025-09, with the labels that each got.

#8089 Implement the algorithm to find the centroid(s) of a tree
  doc/reference/algorithms/tree.rst
  networkx/algorithms/distance_measures.py
  networkx/algorithms/tree/distance_measures.py
  networkx/algorithms/tree/tests/test_distance_measures.py
Labels: type: Enhancements

#8228 TST: add seed for `random_cograph` test
  networkx/generators/tests/test_cographs.py
Labels: type: Maintenance

#8234 Update links for broken testing badge in README.
  README.rst
Labels: type: Maintenance

#8168 Clarifying `@_dispatchable(name=`
  doc/release/release_3.5.rst
  networkx/utils/backends.py
Labels: type: Maintenance, Dispatching

#7856 DOC: Add examples to contracted_nodes.
  networkx/algorithms/minors/contraction.py
Labels: type: Documentation

#8226 TST: improve coverage for `generators/deg_seq.py`
  networkx/generators/degree_seq.py
  networkx/generators/tests/test_degree_seq.py
Labels: type: Testing

#8052 Mehlorn Steiner Tree
  networkx/algorithms/approximation/steinertree.py
  networkx/algorithms/approximation/tests/test_steinertree.py
Labels: type: Bug fix

#8251 TST: add coverage for `isomorphvf2`
  networkx/algorithms/isomorphism/tests/test_isomorphvf2.py
Labels: type: Testing

#8232 TST: ensure determinism in `nx_pylab` drawing tests
  networkx/drawing/tests/test_pylab.py
Labels: Visualization, type: Testing

#8201 DOC/MAINT: Use `itertools.pairwise` in `pairwise` and add docstring
  networkx/utils/misc.py
Labels: type: Maintenance

#8272 Rm outdated codecov badge from README
  README.rst
Labels: type: Maintenance

#8279 TST: test `topo_sort` skips visited nodes in `goldberg_radzik`
  networkx/algorithms/shortest_paths/tests/test_weighted.py
  networkx/algorithms/shortest_paths/weighted.py
Labels: type: Testing

#8281 Expire deprecation of compute_v_structures.
  doc/developer/deprecations.rst
  doc/reference/algorithms/dag.rst
  networkx/algorithms/dag.py
  networkx/algorithms/tests/test_dag.py
  networkx/conftest.py
Labels: type: API

#8282 Expire deprecation of link kwarg in node_link fns.
  doc/developer/deprecations.rst
  examples/external/javascript_force.py
  networkx/conftest.py
  networkx/readwrite/json_graph/node_link.py
  networkx/readwrite/json_graph/tests/test_node_link.py
Labels: type: API

#8289 Add iplotx to network drawing documentation
  doc/reference/drawing.rst
  examples/external/plot_iplotx.py
  pyproject.toml
  requirements/example.txt
Labels: type: Documentation
